### ISSUE TITLE
Initial application setup

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1]
**ACCEPTANCE CRITERIA**
- [ ] There is a rails application
- [ ] It uses lando for local database development
- [ ] There is an rspec based test suite
- [ ] The test suite runs on CI for each commit
- [ ] The CI status is on a badge in the README
- [ ] The README contains instructions enough that a new staff member can get this application running locally

**Comment by hackartisan** [comment]
You might take a look at https://github.com/pulibrary/rails-template
