### ISSUE TITLE
Install DataDog

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1000]
Instructions for rails configuration here: https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#railshanami-applications

Princeton Ansible configuration:  May just need apm enabled (or might need a rails/ruby typed check configuration)
https://github.com/pulibrary/princeton_ansible/blob/b4a8eb0a31886aefa921e2edc8d4c266be627234/group_vars/libstatic/production.yml#L20-L22
Acceptance criteria:

- [x] Install DataDog for PDC Describe (Likely to be in princeton-ansible)
- [x] Set it up enough that we can do basic application performance monitoring (In the application)
- [x] I can go to the APM dashboard in datadog and see how long the operations are taking
- [x] We do not generate errors when running locally 
- [x] We don't produce more logs than we actually need
- [x] There is a link to the dashboard in either the RDSS-handbook (applications page?) or the pdc-describe readme

Example of error:
```
E, [2023-05-16T09:36:57.571485 #70339] ERROR -- ddtrace: [ddtrace] (/Users/colec/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/ddtrace-1.11.1/lib/ddtrace/transport/http/client.rb:37:in `rescue in send_request') Internal error during Datadog::Transport::HTTP::Client request. Cause: Errno::ECONNREFUSED Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for 127.0.0.1:8126) Location: /Users/colec/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock'
```

**Comment by jrgriffiniii** [comment]
https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby#rails offers some documentation regarding how it may be best to integrate this into Rails applications for focused tracing.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1000?planning-poker) with Zenhub @bess @jrgriffiniii @kelynch @mccalluc

**Comment by kelynch** [comment]
Closing in favor of https://github.com/pulibrary/pdc_describe/issues/1135

**Comment by bess** [comment]
Re-opening, because we need both DataDog and Sensu
