### ISSUE TITLE
Give hh4079 access to Princeton Plasma Physics Laboratory on PDC Describe staging for testing

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1003]
Hannah Hadley needs access to Princeton Plasma Physics Laboratory submissions on staging for PPPL UX Testing meetings starting on 2023/02/27.

**Comment by hhkitsune** [comment]
Ideally, please get me access this week so I can set up the test submission for Stan. Thanks!

**Comment by carolyncole** [comment]
Done via: https://pdc-describe-staging.princeton.edu/describe/collections/
