### ISSUE TITLE
Describe Form: Delete files + Failsafe and new Upload

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1021]
## Description

The user experience of uploading or deleting files should feel more intuitive and reflect what users have likely encountered for other software applications. In ticket #1010, we explained that we want both file addition and file deletion, and described where these features should be located on the files feature. This ticket covers the details for how we expect the delete feature should work. Please see the images below.

## Image shows files that were uploaded to a submission
![Screen Shot 2023-03-01 at 2 00 57 PM](https://user-images.githubusercontent.com/50670293/222272238-b148af2a-fdd9-41cb-ab61-d7597b203457.jpeg)

#### A thick black "X" appears to show which files have been selected for deletion. These files will not delete until "save work" has been selected. This provides a fail-safe against accidental deletion. We use a thick black "X"  because it will be inclusive of visual differences, but still very noticeable. 

Note: We may need additional help text to explain that save work is selected to confirm deletion.
![Screen Shot 2023-03-01 at 2 01 09 PM](https://user-images.githubusercontent.com/50670293/222272466-84eea811-cd62-43ec-bd33-c08b293051f1.jpeg)

#### The submitter makes a correction by unchecking the README file they do not want to delete
![Screen Shot 2023-03-01 at 2 01 23 PM](https://user-images.githubusercontent.com/50670293/222273763-e47d1f3e-0121-4f85-a0c7-5de659e44cbc.jpeg)

## Image shows the Paints.xls file was deleted

![Screen Shot 2023-03-01 at 2 01 36 PM](https://user-images.githubusercontent.com/50670293/222275916-ca6bba46-06ac-4f61-b890-3b3dd4c6fa82.jpeg)

#### Please assume the submitter had used the "add new files" button to add this file. This button will work in the same way as uploading files during the submission process.

![Screen Shot 2023-03-01 at 2 01 50 PM](https://user-images.githubusercontent.com/50670293/222276254-a7c80989-d605-4631-9af5-a6186f35896c.jpeg)

## Acceptance Criteria
- [ ] Ticket #1010 is completed
- [ ] The "replace upload" feature is removed from the file listing
- [ ] A fail-safe is added for files that are selected for deletion
- [ ] The fail-safe appears as a visible thick, black "X" (or contact Hannah if you have another idea)
- [ ] A selected file may be de-selected
- [ ] Selected files will delete after selecting "save work"
- [ ] **Suggested:** We add help text to say that "Selected files will be deleted after saving work." (or a similar statement)
- [ ] New files may be added using the "add new files" button, which was changed in ticket #1010 
- [ ] Adding new files will occur in the same way as adding them during the submission process.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1021?planning-poker) with Zenhub @bess @jrgriffiniii
