### ISSUE TITLE
Describe Staging Access - Add Esme Cowles

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1024]
## Description

Please provide Esme Cowles with submitter access to the main research collection in PDC Describe staging. This is for user testing purposes.

## Acceptance criteria
- [x] Esme is added to PDC Describe staging as a submitter
- [x] Esme will be assigned to the the main research collection

**Comment by kelynch** [comment]
This should be completed.  @escowles can you confirm when you get a chance?

**Comment by escowles** [comment]
👍🏻 yep, I can login now — thanks!
