### ISSUE TITLE
Attempting to publish a Work without attached uploads should result in meaningful error message

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1036]
PDC Describe currently has a safeguard in place to prevent publishing a work without attached uploads. However, when this error is triggered, it just goes to a standard rails error page and it doesn't inform the user about what the problem is. Instead, attempting to publish a work without an attached upload should result in a meaningful error message. 

Error message reads: 
[pdc_describe/staging] StandardError: Attempting to publish a Work without attached uploads for 10.11578/1888278/210

## Backtrace

    line 626 of [PROJECT_ROOT]/app/models/work.rb: publish_precurated_files
    line 456 of [PROJECT_ROOT]/app/models/work.rb: publish
    line 205 of [PROJECT_ROOT]/app/controllers/works_controller.rb: approve

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/94781598)

**Comment by hectorcorrea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1036?planning-poker) with Zenhub @carolyncole @jrgriffiniii @Twade968
