### ISSUE TITLE
Extra prefix added to file re-uploaded

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1039]
Deleting a file in an S3 precuration bucket and adding a new file with the same name results in AWS giving a different name to the new file. Notice the `_2` in `015_2.txt` and the `_3` in `old-san-juan_3.jpg`, those suffixes were added by AWS after I deleted the original files and re-uploaded them.

![Screenshot 2023-03-30 at 12 22 01 PM](https://user-images.githubusercontent.com/568286/228901623-df60c3a6-9a4c-466d-8210-9556860a093b.png)

I *suspect* this is because of bucket versioning in S3 being enabled, but I am not 100% sure of this.

The code that does this is located in the [work](https://github.com/pulibrary/pdc_describe/blob/main/app/models/work.rb#L548-L569)

- [ ] Remove the code that is adding the _ number from the work
- [ ] Add a test to make sure adding the same file multiple times creates the same file name (This test may exists for the _# which would then just need to be changed)

**Comment by carolyncole** [comment]
Yes, versioning is turned on, so that we have a soft delete.

**Comment by carolyncole** [comment]
The new README code that utilizes S3 (not done just in testing) does not create the numbers.  I think we need to remove ActiveStorage (or what we do for it) from the system.
![Screenshot 2023-03-31 at 10 44 47 AM](https://user-images.githubusercontent.com/1599081/229153436-4e783d37-d0dd-4669-b364-109567af8c9a.png)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1039?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii @kelynch

**Comment by hectorcorrea** [comment]
Before addressing this issue let's confirm that it still happens after the changes that Carolyn and James did to remove ActiveStorage from the system (PRs https://github.com/pulibrary/pdc_describe/pull/1279 and https://github.com/pulibrary/pdc_describe/pull/1229)

**Comment by carolyncole** [comment]
I can not replicate this issue.  @hectorcorrea can you replicate this issue now?

**Comment by hectorcorrea** [comment]
Cannot replicate. Closing.
