### ISSUE TITLE
Describe Form: Limit number of times I can "add myself" as an author

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1045]
## Description

It was discovered in user testing that a depositor may add themselves more than once as an author. We would like users to only add themselves once, so we need some kind of limit applied to this action.

## Image shows I have added myself as an author multiple times
![Screen Shot 2023-04-04 at 10 06 25 AM](https://user-images.githubusercontent.com/50670293/229820126-e02e4ed0-78e6-4a3f-bf49-4e24d7c53006.jpeg)

## Acceptance Criteria
- [ ] Depositors can only add themselves one time as an author. The button will be disabled once it has been clicked
~~- [ ] They may add themselves back if they deleted themself, but shouldn't be able to add themselves multiple times to the record while they are already actively listed.~~ Not MVP we can ticket separately for post MVP

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1045?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii @kelynch

**Comment by carolyncole** [comment]
Closed by PR.  Follow up ticket has been created for second part of the request.
