### ISSUE TITLE
File Size: What is the Unit of Measurement?

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1047]
## Description

The file size is showing large numbers of an indeterminate unit of measurement that is smaller than mb. The image below shows a size of 2,166,561 which seems oddly large. The file uploaded is 2.2mb. We would ideally like to see a unit of measurement that is more conventional so users aren't confused by a larger (or smaller) than expected size.

## Image shows oddly sized file
![Screen Shot 2023-04-05 at 10 55 38 AM](https://user-images.githubusercontent.com/50670293/230121267-9e692585-a0e3-4fe5-a945-c4d7ca52609e.jpeg)

## Acceptance Criteria
- [ ] A unit of measurement is provided with the file size
- [ ] The unit of measurement used will be more conventional. For example, someone deposits a file that is 2.2mb and will render the same, as opposed to seeing a very large number.

## Implementation breadcrumbs
* https://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_to_human_size

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1047?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii @kelynch
