### ISSUE TITLE
Too many Princeton IDs in initial submission messages

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1048]
## Description
Test users have mentioned the initial messages sent after submitting an uncurated deposit show too many Princeton Ids. It was mentioned this visually clutters the messages and may obscure new messages from only one sender. It was posited that an @ with the group name might be used instead.

## Image shows wall of Princeton Ids in the messaging feature
![Screen Shot 2023-04-05 at 11 22 28 AM](https://user-images.githubusercontent.com/50670293/230128024-bde106a2-5b45-4920-a0c4-a043ee98aaae.jpeg)

## Acceptance Criteria
- [ ] The initial messages will show PDC pipeline grouping (example: "Princeton Research Data Service" or "Princeton Plasma Plastics Lab."
- [ ] All users in the appropriate pipelines with appropriate roles will still be informed of new submissions

**Comment by carolyncole** [comment]
Display the first two and then # others
```
@hhh409, @mcj12, and 11 others
```

**Comment by kelynch** [comment]
Referenced in https://github.com/pulibrary/pdc_describe/issues/1138

**Comment by kelynch** [comment]
Functionality for MVP:

"@hhh409, @mcj12, and 11 others" and when "11 others" is hovered over, the other display names appear in a tooltip

**Comment by carolyncole** [comment]
This ended up being easier changing the message to include the group code instead of just listing the first two.  Since this was the original ask in the ticket I ignored our "simplified" requirements
