### ISSUE TITLE
Globus URLs in descriptions do not work as expected

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1067]
Globus links in the objects we're migrating (e.g., https://dataspace.princeton.edu/handle/88435/dsp012j62s808w) from DataSpace do not work as expected. The URL is the same as the one in DataSpace, it did not change during the migration process. Seems like maybe the URL sort of works as long as you know how to use Globus well? 

## Acceptance Criteria
- [ ] Do we want to keep a URL in the description, or should these be put elsewhere? 
- [ ] If we want to keep the link, what link should be put here? 
- [ ] If the URL is correct but the interface is hard to understand, how should we tell someone how to download this data from Globus? Do we need a help page? 

![Screenshot 2023-04-14 at 4 03 09 PM](https://user-images.githubusercontent.com/65608/232149595-3763eacb-d5ed-4f24-99cd-42f65316a60d.png)
![Screenshot 2023-04-14 at 4 38 19 PM](https://user-images.githubusercontent.com/65608/232150222-91f668d8-9006-4cfd-bbf4-60b8c468129d.png)

**Comment by bess** [comment]
This is a question to bring up with the folks doing the data migration. We'll agree on a process as part of our migration plan.

**Comment by hectorcorrea** [comment]
Today we noticed that this could be because of the way Globus displays the data by default, i.e. one panel vs two panels. 

![Screenshot 2023-04-25 at 9 27 52 AM](https://user-images.githubusercontent.com/568286/234291956-6cf0b083-69bd-4920-954d-e63723d5b751.png)

**Comment by hhkitsune** [comment]
@bess Per PRDS, please remove this content about Globus from the description.

**Comment by kelynch** [comment]
When we migrate objects from DataSpace with Globus information from the description.

Separately, someone will need to indicate that this error may happen sometimes, and how to address it.  This could be a help screen/part of a training issue.

**Comment by bess** [comment]
PRDS is still discussing how to handle this usability issue.
