### ISSUE TITLE
Files appear to disappear if I withdraw and then re-publish a data set

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1081]
1. I submit a dataset and attach files
2. I complete it and approve it
3. I withdraw it (maybe there was a problem with it)
4. I fix the issue and re-submit it for approval
5. Now all my files appear to be gone because they were moved to post-curation. The work cannot be approved because it appears to have no works attached. 

The user is left with the impression that their files have disappeared.

* We could display post-curation files so the user knows their files were not deleted, and check post-curation when we're publishing.
* If we really want to remove the files when a work is withdrawn we should tell the user what is happening

```
I, [2023-04-19T18:04:34.948242 #9776]  INFO -- : [ebbfac16-4aff-47d3-874a-f0ce32f3745f] Completed 500 Internal Server Error in 67ms (ActiveRecord: 24.6ms | Allocations: 6571)
F, [2023-04-19T18:04:34.950087 #9776] FATAL -- : [ebbfac16-4aff-47d3-874a-f0ce32f3745f]
[ebbfac16-4aff-47d3-874a-f0ce32f3745f] StandardError (Attempting to publish a Work without attached uploads for 10.34770/xajd-5n64/274):
```

![Screenshot 2023-04-19 at 1 55 58 PM](https://user-images.githubusercontent.com/65608/233161676-517dadf6-d2b9-4a17-94ee-d6379a6a13c3.png)

**Comment by carolyncole** [comment]
Closing in favor of https://github.com/pulibrary/RDOS_Publishing/issues/24
