### ISSUE TITLE
Coveralls reporting is incorrect

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1084]
According to coveralls, our code coverage just dropped significantly. Coveralls is [reporting](https://coveralls.io/builds/59101877/source?filename=app%2Fmodels%2Fuser.rb) that our `User` model doesn't have any test coverage, but it definitely does: https://github.com/pulibrary/pdc_describe/blob/main/spec/models/user_spec.rb

![Screenshot 2023-04-20 at 10 56 00 AM](https://user-images.githubusercontent.com/65608/233405514-d726f09b-a4d5-4620-8b2a-87a10864fb1f.png)

**Comment by hectorcorrea** [comment]
I wonder if this is related to the SimpleCov change that I made here: https://github.com/pulibrary/pdc_describe/pull/1082/files#diff-053aa3ea46cb7c6a649e0d0fc592ce729b66e1d44be475516fd58857ba695862
