### ISSUE TITLE
Describe Staging: Error message when creating new submission

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1085]
## Description

A moderator/user was testing in describe staging and received an error message. The message appeared after the preliminary step (i.e., page to enter title, author and warning message) when selecting the continue button. Selecting the continue button should have brought the user to the metadata entry page with the tabs and draft DOI. She received an error message instead.

## Image shows error message 

![screenshot_2023-04-20_at_12 01 38_pm](https://user-images.githubusercontent.com/50670293/233429843-7d82670e-bc82-46f4-9eef-ff588000458e.png)

## Acceptance Criteria
- [x] Problem is diagnosed
- [x] Error message is resolved
- [x] User can access the form in staging as expected

**Comment by hectorcorrea** [comment]
There are several ERROR entries in the staging log around the time of the error that point to ActiveJob:

```
E, [2023-04-20T16:30:27.949860 #67207] ERROR -- : [51f57017-293d-4766-9571-130ef26dde89] [ActiveJob] [ActionMailer::MailDeliveryJob] [fc852c60-a9db-46d9-abb0-4cb750b50af2] Error performing ActionMailer::MailDeliveryJob (Job ID: fc852c60-a9db-46d9-abb0-4cb750b50af2) from Inline(default) in 27.49ms: Errno::ECONNREFUSED (Connection refused - connect(2) for 127.0.0.1:1025):
```

**Comment by bess** [comment]
I believe this is fixed now. The problem was a bug in the install script of the new servers we just put in place this week.

**Comment by hhkitsune** [comment]
Thanks both! I'll have Sarah check on her end and will report back.

**Comment by hhkitsune** [comment]
The user reported the issue as fixed. I will close this completed ticket.
