### ISSUE TITLE
Automating the creation of a DOI

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#109]
On the "Identifiers" tab, IFF the user is a collection admin or super admin, they get a button to mint a DOI. 

- [ ] We do not mint a DOI if one exists already
- [ ] When a DOI is minted its value is populated into the field 
- [ ] Evaluate the sul-dlss datacite gem to see if it makes this process easier

**Comment by hhkitsune** [comment]
@bess I have started to detail this process in tickets #135 and #136. I will be checking with Matt and Neggin about details for steps 2 and 3 of this process, but those steps can also be expected to have tickets.

**Comment by hectorcorrea** [comment]
This process has been completed. The remaining work is now on issue #196
