### ISSUE TITLE
Access issue on Globus folder

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1090]
Notice: This is really an issue with a DataSpace dataset, but since it is a Globus problem I am tracking it here.

Accessing the Globus link for this dataset: https://dataspace.princeton.edu/handle/88435/dsp01qz20sw67s gives intermittent access denied errors.

Globus link: https://app.globus.org/file-manager?destination_id=dc43f461-0ca7-4203-848c-33a9fc00a464&destination_path=%2Fhycg-af09%2F

Sometimes going to the link shows the data as expected: 
![globus-ok](https://user-images.githubusercontent.com/568286/234051145-435e9827-943c-4916-a9a2-0dbe379a53ee.png)

But other times it gives an access error:
![globus-error](https://user-images.githubusercontent.com/568286/234051261-36f20310-fc15-4e51-a314-67597b0d7bd4.png)

**Comment by hectorcorrea** [comment]
Opened a ticket with Globus Support: https://support.globus.org/hc/en-us/requests/368239

**Comment by hectorcorrea** [comment]
Running the self-diagnostic tool `sudo globus-connect-server self-diagnostic` as suggested by the Globus support shows several errors related to a library needed by Python: `libffi.so`:

```
== diagnostic: systemctl status gcs_manager --no-pager --lines 10 ==
● gcs_manager.service - GCS Manager WSGI Service
     Loaded: loaded (/lib/systemd/system/gcs_manager.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-04-24 17:31:50 UTC; 2min 1s ago
TriggeredBy: ● gcs_manager.socket
    Process: 1464 ExecStart=/opt/globus/bin/gunicorn --workers 4 --preload api_app -t 120 (code=exited, status=1/FAILURE)
   Main PID: 1464 (code=exited, status=1/FAILURE)

Apr 24 17:31:50 prds-dataspace-dtn1 gunicorn[1464]:     import ctypes
Apr 24 17:31:50 prds-dataspace-dtn1 gunicorn[1464]:   File "/opt/globus-python/lib/python3.9/ctypes/__init__.py", line 8, in <module>
Apr 24 17:31:50 prds-dataspace-dtn1 gunicorn[1464]:     from _ctypes import Union, Structure, Array
Apr 24 17:31:50 prds-dataspace-dtn1 gunicorn[1464]: ImportError: libffi.so.6: cannot open shared object file: No such file or directory
Apr 24 17:31:50 prds-dataspace-dtn1 systemd[1]: gcs_manager.service: Main process exited, code=exited, status=1/FAILURE
Apr 24 17:31:50 prds-dataspace-dtn1 systemd[1]: gcs_manager.service: Failed with result 'exit-code'.
Apr 24 17:31:50 prds-dataspace-dtn1 systemd[1]: Failed to start GCS Manager WSGI Service.
Apr 24 17:31:50 prds-dataspace-dtn1 systemd[1]: gcs_manager.service: Start request repeated too quickly.
Apr 24 17:31:50 prds-dataspace-dtn1 systemd[1]: gcs_manager.service: Failed with result 'exit-code'.
Apr 24 17:31:50 prds-dataspace-dtn1 systemd[1]: Failed to start GCS Manager WSGI Service.
```

**Comment by kayiwa** [comment]
The fix for this should come from upstream Globus. I'd caution against hacking the perl implementation on the node(s). [Fix for this issue](https://support.globus.org/hc/en-us/requests/368239) came from Globus Support but I continue to see odd behavior from Globus itself.

**Comment by hectorcorrea** [comment]
Thank you @kayiwa. I can confirm that access to the dataset that started this issue is at least now constant.

**Comment by hectorcorrea** [comment]
I've copied to Google drive the details of the ticket in Globus, including the commands that Francis ran (although I did not include our attachments). The PDF is here: https://drive.google.com/file/d/1_KcPvIW9YY-39rGyJyrrmQz6EKKjn8xu/view?usp=share_link
