### ISSUE TITLE
dataspace-dev is down

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1095]
While attempting to write a DataSpace query for data migration I noticed that dataspace-dev is giving a 502 bad gateway error.

I checked that I'm on VPN, and in the US Northeast region. I've tried a `dsbounce` but no change in behavior.

![Screenshot 2023-04-26 at 9.37.01 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/84a2b858-1afe-4089-99c8-a6db7a4881e9) 

![Screenshot 2023-04-26 at 9.38.04 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/4927aebd-fd94-4502-a5db-4eee83efb4be)

**Comment by bess** [comment]
Tried a `dsrestart` and no joy.
Rebooting the server.

**Comment by kayiwa** [comment]
This was a DNS issue. I've made the dev loadbalancer use a fixed lease.
