### ISSUE TITLE
Identify 3 - 5 library PDFs

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#11]
- [x] They should come from different fields
- [x] Include any that are highly visible or politically important
- [x] Record the object handles, with links to dataspace, in a document in this project

**Comment by kelynch** [comment]
Five objects are available here - https://docs.google.com/document/d/18ZkBldqWxIIR1UA6qMY87RnGFTKU9HG3EJzodzzFf2A/edit#bookmark=id.o3vcemdfz6qb
