### ISSUE TITLE
Be able to attach files < 100Mb

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#110]
- [x] The form has the ability to attach up to 20 files, of < 100Mb each
- [x] Files that are submitted will be stored in the pre-curation S3 bucket for now.
- [x] The files are visible and downloadable from the show screen
- [x] There is a clear difference between pre-curated data and post-curated data 
- [x] Once pre-curated data has been submitted, it is visible in a pre-curated data section on the dataset show page
- [x] AWS S3 Buckets should use environment variables for the `staging` and `production` environments
- [x] Files are stored in S3 using the original (or very similar) filenames that the user submitted.

**Comment by jrgriffiniii** [comment]
Thank you for your patience regarding my progress on this. Regarding my updates for this issue, I have the following:

> The form has the ability to attach up to 20 files, of < 100Mb each

I need to ensure that this validation for up to 20 files is in place, however https://github.com/pulibrary/pdc_describe/pull/220 ensures that multiple files can be updated and replaced

> Files that are submitted will be stored in the pre-curation S3 bucket for now.
[...]
>  AWS S3 Buckets should use environment variables for the staging and production environments

I am addressing this in the next pull request(s)

> The files are visible and downloadable from the show screen
> There is a clear difference between pre-curated data and post-curated data
> Once pre-curated data has been submitted, it is visible in a pre-curated data section on the dataset show page

The files themselves are visible, however, there needs to be clearer disambiguation between pre-curated and curated data

**Comment by jrgriffiniii** [comment]
It was clarified during a meeting held on 07/15/22 that the files stored on disk *must* be human-readable, and stored within a human- navigable directory tree.

**Comment by jrgriffiniii** [comment]
The following error is encountered when testing this within the `staging` environment:

https://app.honeybadger.io/projects/99214/faults/87146315

**Comment by jrgriffiniii** [comment]
I have just tested this successfully from my local environment:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/a19dea8d-3c74-4b44-a96f-3e2ff62d3a6e)

**Comment by jrgriffiniii** [comment]
The following error is being logged on the NGINX Plus nodes:

```
2022/08/04 14:55:32 [error] 1972398#1972398: *16920700 client intended to send too large body: 3069284 bytes, client: 172.20.203.68, server: pdc-describe-staging.princeton.edu, request: "POST /describe/works/56/file-upload HTTP/2.0", host: "pdc-describe-staging.princeton.edu", referrer: "https://pdc-describe-staging.princeton.edu/describe/works/56/file-upload"
2022/08/04 14:55:32 [error] 1972398#1972398: *16920700 output on closed stream while sending to client, client: 172.20.203.68, server: pdc-describe-staging.princeton.edu, request: "GET /describe/packs/js/application-261dcf4715ff79a9c038.js HTTP/2.0", upstream: "http://128.112.204.77:80/describe/packs/js/application-261dcf4715ff79a9c038.js", host: "pdc-describe-staging.princeton.edu", referrer: "https://pdc-describe-staging.princeton.edu/describe/works/56/file-upload"
```

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/princeton_ansible/issues/3197 is necessary to resolve the NGINX Plus errors.
