### ISSUE TITLE
Dspace migration in provenance log

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1109]
We want to see the dspace files migrated as part of the work activity.
An UploadSnapshot should be created also so we do not double count the migrated files

The work activity should include  "Files Migrated: <#files> "  instead of 
![Screenshot 2023-05-01 at 3 49 58 PM](https://user-images.githubusercontent.com/1599081/235519354-4f8660d1-b432-4b18-87a9-6548ba875caf.png)

Acceptance criteria

- [x] The Migration can be done from the UI so we know who did it for the work activity
- [x]  Migrated files show as one line in the work activity
- [x] The Files do not get listed in the Files Added by unknown user
- [x] Automated tests for the above scenarios

**Comment by bess** [comment]
![Screenshot 2023-05-03 at 10 11 16 AM](https://user-images.githubusercontent.com/65608/235941572-d63bd60f-7423-400b-96e9-203ef7eff0c7.png)

**Comment by carolyncole** [comment]
We could hide some of the migration provenance from the user (possibly roll it up) so it looks more like 👆

Can we roll up all migration steps into one (approve, metadata, files).  This could be a separate ticket or part of this one.  How do do this...

**Comment by kelynch** [comment]
Whoever added the metadata and whoever hit the file migration button should be recorded (not necessarily displayed in the UI).

We will need to produce proof that files that were in DataSpace were migrated intact to PDC Describe if we get audited.  We can use checksums for this.

We should record all activities in the system and be able to tag them as "migration" so they do not show up in the UI.

**Comment by carolyncole** [comment]
https://github.com/pulibrary/pdc_describe/pull/1162/files Should complete this work.
