### ISSUE TITLE
Migration process failing for directories

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1120]
The automated migration process is mostly working, but it is failing for the directory objects with the error `Aws::S3::Errors::MalformedXML: The XML you provided was not well-formed or did not validate against our published schema`

![Screenshot 2023-05-04 at 1 25 14 PM](https://user-images.githubusercontent.com/65608/236285014-e135ab66-de81-4762-a118-d43cfd834c30.png)

**Comment by carolyncole** [comment]
They run in the rails console just fine.  I believe sidekiq is not picking up the new code.  Will look into adding capistrano-sidekiq gem.
