### ISSUE TITLE
Are we adding the right license.txt to the migrated objects? 

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1122]
![Screenshot 2023-05-04 at 2.11.59 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/0b7762ad-54b8-4029-bf01-c389ad4a7807)

**Comment by kelynch** [comment]
Per conversation on Slack just now, this is OK.  The "license.txt" file shown here is generated by DataSpace as part of the built-in DSpace "LicenseUtils" module, taking the language of the click-through license agreement in DataSpace and putting it into a flat text file that gets downloaded alongside the rest of the files in the bundle.  The license info in PDC Describe is recorded in the DataCite record.  We should keep this "license.txt" file that comes from DataSpace with the original object as part of the migration.
