### ISSUE TITLE
Describe Staging: Error message when trying to approve

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1129]
## Description

Describe staging provided an error message when we tried to approve a test submission.

## Image shows error message
![PDCfail](https://user-images.githubusercontent.com/50670293/236854754-8923fafb-2c2d-4903-9255-ff643734ab6e.png)

## Acceptance criteria
- [ ] Diagnose and fix the error
- [ ] Display a user friendly message rather than the default Rails error message
- [ ] We should be able to approve submissions in PDC staging -- to move from staging pre-curation to staging post curation -- in order to test the system.

**Comment by hectorcorrea** [comment]
It looks like the serialize to DataCite does not handle unknown types correctly. The log shows the following error:

```
I, [2023-05-08T14:50:10.435691 #1147]  INFO -- : [a6f7301d-aefa-4be9-b974-b95adee2d5f0] Processing by WorksController#approve as HTML
I, [2023-05-08T14:50:10.435843 #1147]  INFO -- : [a6f7301d-aefa-4be9-b974-b95adee2d5f0]   Parameters: {"authenticity_token"=>"[FILTERED]", "id"=>"69"}
I, [2023-05-08T14:50:10.475358 #1147]  INFO -- : [a6f7301d-aefa-4be9-b974-b95adee2d5f0] Loading S3 objects. Bucket: pdc-describe-staging-precuration. Prefix: 10.80021/0hj6-9f47/69/. Elapsed: 0.024303241 seconds
I, [2023-05-08T14:50:10.480323 #1147]  INFO -- : [a6f7301d-aefa-4be9-b974-b95adee2d5f0] Completed 500 Internal Server Error in 44ms (ActiveRecord: 6.7ms | Allocations: 6772)
F, [2023-05-08T14:50:10.482097 #1147] FATAL -- : [a6f7301d-aefa-4be9-b974-b95adee2d5f0]   
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] ArgumentError (Type cannot be nil):
[a6f7301d-aefa-4be9-b974-b95adee2d5f0]   
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/pdc_serialization/datacite.rb:133:in `new'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/pdc_serialization/datacite.rb:133:in `block in individual_contributors_from_work_resource'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/pdc_serialization/datacite.rb:132:in `map'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/pdc_serialization/datacite.rb:132:in `individual_contributors_from_work_resource'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/pdc_serialization/datacite.rb:91:in `new_from_work_resource'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/pdc_metadata/resource.rb:72:in `to_xml'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/work.rb:709:in `doi_attribute_xml'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/work.rb:716:in `doi_attributes'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/work.rb:689:in `publish_doi'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/models/work.rb:577:in `publish'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/controllers/works_controller.rb:213:in `approve'
[a6f7301d-aefa-4be9-b974-b95adee2d5f0] app/controllers/works_controller.rb:328:in `rescue_aasm_error'
```

**Comment by hectorcorrea** [comment]
We noticed that the additional contributors had a blank role, perhaps because the existing role in the record did not match the valid types in the DataCite gem. This is the root of the problem. Selecting a role (the drop down has the valid values) allowed the record to be approved.

**Comment by hectorcorrea** [comment]
I corrected several records that had bad or missing data for DataCite (see PR #1132) but noticed that there are two records in staging without a DOI, not even a draft DOI:
* https://pdc-describe-staging.princeton.edu/describe/works/277  
* https://pdc-describe-staging.princeton.edu/describe/works/289 

We should also update the code to handle the lack of data more gracefully rather than (as the screenshot shows) with an unhandled exception.

**Comment by carolyncole** [comment]
Closing in favor of #1153
