### ISSUE TITLE
Use something (recommended by Ops)  for monitoring

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1135]
## Acceptance Criteria

- [ ] Install Ops recommended Monitoring for PDC Describe (in princeton_ansible - https://github.com/pulibrary/princeton_ansible/issues/3021)
- [ ] Install Ops recommended Monitoring for Globus boxes
- [ ] Install Ops recommended Monitoring for PDC Discovery
- [ ] We monitor these things as a starting point:
  - [ ] ping check for system being alive 
  - [ ] application responds as expected on port 443 
  - [ ] [disk usage](https://github.com/pulibrary/pdc_describe/issues/1374)
  - [ ] database connectivity
  - [ ] sshd
  - [ ] S3 connectivity 
  - [ ] ssl cert expiration date
  - [ ] CPU usage
  - [ ] memory usage  
  - [ ] sidekiq
- [ ] There is a link to the dashboard in either the RDSS-handbook (applications page?) or the pdc-describe readme
         https://lib-monitor.princeton.edu/c/~/n/default/events?q=event.check.state%20!=%20passing
             Asks for two factor without telling you! We need to scope the above url to our project and passing or not.

**Comment by kelynch** [comment]
Parts of this completed, documented in https://github.com/pulibrary/rdss-handbook/blob/main/monitoring.md.

Closing this and will regroup with Operations on remaining tasks, to be separately ticketed.

**Comment by bess** [comment]
Reopening because we don't have another ticket that captures our need for sensu monitoring. I added sidekiq to the list here.

**Comment by bess** [comment]
We need monitoring for sidekiq because it can crash silently:

![Screenshot 2023-06-09 at 4 24 57 PM](https://github.com/pulibrary/pdc_describe/assets/65608/d71ccf5b-ae17-48e2-bd3d-bda823491904)

**Comment by jrgriffiniii** [comment]
The following `agents` have been created for `pdc-describe-prod` using `princeton_ansible`:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/96ad4ec7-c61b-4367-88f3-1590b71deaa9)

**Comment by jrgriffiniii** [comment]
There exists no accompanying `proxy` for these, I shall evaluate and look to create this now.

**Comment by jrgriffiniii** [comment]
From what I could best determine, `proxy` entities are created automatically from status checks invoked from the `backend`:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/e7291c6a-aa22-4e62-a5f4-78dea25dbc3c)

**Comment by jrgriffiniii** [comment]
There seem to be authorization issues when attempting to edit `ServiceComponents` which I have already created (for a `Service` which I have also created):

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/b8cc1059-d1de-4183-86ed-61bddc9390ef)

**Comment by jrgriffiniii** [comment]
I am now currently able to successfully create `ServiceComponents` which subscribe to alerts from `Agents`:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/17febe56-6e73-439b-8b1f-53671a6a3639)
![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/6d86da28-cac4-4732-b620-8e35c92c93e1)

**Comment by kelynch** [comment]
Follow-up work tracked on https://github.com/pulibrary/pdc_describe/issues/1374, closing.
