### ISSUE TITLE
Messaging: Remove "all curator" messages from the display

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1138]
## Description

When a deposit is made, the system sends out "@" based messaging to all the curators in a given group to alert them something has been created, ready for review, or has been published. These messages look cluttered because they include "@" handles for all curators in the group. Can we reduce this visually with a group handle or just not displaying all of the handles? It isn't necessary for users to see all of these handles.

Update: (5/19/23) Masked user test illustrated the problem with showing all of the handles. The tester felt intimidated by all of these unknown people seeing her draft submission. A message sent by the curator was obscured and not seen by the tester because of the visual clutter.   

## Image shows current messaging. See magenta line for the messages will "@" all curators handles.
![Screen Shot 2023-05-09 at 12 22 26 PM](https://github.com/pulibrary/pdc_describe/assets/50670293/ae45381f-2537-4981-9bd9-9ebbefd4a268)

## Acceptance Criteria
- [ ] The "all curator" messages will not appear in the messages column
- [ ] The curator group will still be notified

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1138?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii @kelynch
