### ISSUE TITLE
"Mismatching checksum": What's our process when we hit this? 

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1146]
This error was encountered during the data migration process for one of the fixture objects, but I don't know which one. Maybe we should adjust these [lines](https://github.com/pulibrary/pdc_describe/blob/a32b3c3ad3513298a66a4776c17a49ebe00c7307/app/services/pul_dspace_connector.rb#L93C9-L94): 

`Honeybadger.notify("Mismatching checksum #{filename} #{bitstream}")`

- [x] Update the error message to also include the ARK / DOI / database ID

Error:
 [pdc_describe/staging] Notice: Mismatching checksum /tmp/dspace_download/344/Fig2_deltaCsd6_7.tgz {"id"=>141090, "name"=>"Fig2_deltaCsd6_7.tgz", "handle"=>nil, "type"=>"bitstream", "link"=>"/rest/bitstreams/141090", "expand"=>["parent", "policies", "all"], "bundleName"=>"ORIGINAL", "description"=>nil, "format"=>"Archive", "mimeType"=>"application/x-compressed, application/x-tar", "sizeBytes"=>1434231956, "parentObject"=>nil, "retrieveLink"=>"/bitstreams/141090/retrieve", "checkSum"=>{"value"=>"4b82617fd4... #1146 

## Backtrace

    line 157 of [PROJECT_ROOT]/app/services/pul_dspace_data.rb: checksum_file
    line 47 of [PROJECT_ROOT]/app/services/pul_dspace_data.rb: block in download_bitstreams
    line 45 of [PROJECT_ROOT]/app/services/pul_dspace_data.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/95864344)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1146?planning-poker) with Zenhub @bess @hectorcorrea @kelynch

**Comment by carolyncole** [comment]
@jrgriffiniii is testing a quick fix.
Add to the migration ADR to move the files by hand to Globus and point to them in the record.

**Comment by kelynch** [comment]
Closing in favor of #1215
