### ISSUE TITLE
NameError: undefined local variable or method `dspace' when migrating DSpace content

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1147]
Error: 

 [pdc_describe/staging] NameError: undefined local variable or method `dspace' for #<PULDspaceData:0x00007f23e47893f8 @work=#<Work id: 344, work_type: "DATASET", state: "draft", collection_id: 1, created_by_user_id: 3, created_at: "2023-05-10 14:28:09.494188000 -0400", updated_at: "2023-05-10 14:55:31.526257000 -0400", metadata: {"titles"=>[{"title"=>"Distinct cytoskeletal proteins define zones of enhanced cell wall synthesis in Helicobacter pylori", "title_type"=>nil}], "description"=>"Helical cell shape... #1147 

## Backtrace

    line 103 of [PROJECT_ROOT]/app/services/pul_dspace_data.rb: migrate_dspace
    line 16 of [PROJECT_ROOT]/app/services/pul_dspace_data.rb: migrate
    line 7 of [PROJECT_ROOT]/app/controllers/work_migration_controller.rb: migrate

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/95864816)

This is against old code. 

- [ ] re run the fixture (find the ark from the spec by the title "Distinct cytoskeletal proteins define zones of enhanced cell wall synthesis in Helicobacter pylori"
       - Go onto QA and re-submit the data migration, by pressing the button again
       - The background job with send an error to HoneyBadger

- [ ] If this is still an error open a new ticket with the updated error log.

**Comment by carolyncole** [comment]
The dspace undefined variable may be fixed, but what is causing the underlying trigger of the error handling code still also should be fixed.
