### ISSUE TITLE
Work without a DOI

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1153]
We have seen one or two works without a DOI in PDC Describe staging. The most recent was this:

Describe record: https://pdc-describe-staging.princeton.edu/describe/works/355
Discovery record: https://pdc-discovery-staging.princeton.edu/discovery/catalog/doi- 

We think this has happened with this particular dataset before "Sowing the Seeds for More Usable Web Archives: A Usability Study of Archive-It"

- [ ] The validation should not allow a blank string for the DOI
- [ ] The fixtures should not need to set the DOI to nil for the system to mint a DOI.  An empty string should also work.
        See: for the ones that should be able to change https://github.com/pulibrary/pdc_describe/pull/970/files

**Comment by carolyncole** [comment]
This is likely related: https://github.com/pulibrary/pdc_describe/pull/970/files
