### ISSUE TITLE
Starting Submission: Error Message

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1154]
## Description

Halle, Hector and Hannah began a test submission. The screen seemed stuck for the begin submission page. Halle was able to see the submission started, then both Halle and Hannah received the error message below.

Update: Hector made the bitKlavier datasets halt, then service was returned.

**Attempt No.2:**
Tried uploading the README, which appeared to be uploaded, selected continue. The form stalled when selecting continue and the error message happened again.

## Image shows error message
![pdc-loading-error_2023-05-12](https://github.com/pulibrary/pdc_describe/assets/50670293/62816f27-d910-4f3e-a8d8-6ac27304fea4)

## Acceptance Criteria
- [ ] Diagnose issue(s)
- [ ] Return service to normal state

**Comment by hectorcorrea** [comment]
We looked at this issue and the culprit seems to be a background job that is maxing out the CPU (and perhaps memory) on the staging boxes. 

We'll look at our current server configuration (CPU, memory, and number of servers) and come up with a plan to grow it to support the expected load.

**Comment by bess** [comment]
We think this should be addressed by this ticket: https://github.com/pulibrary/pdc_describe/issues/1155

**Comment by bess** [comment]
This issue isn't happening right now, so I'm closing this ticket.
