### ISSUE TITLE
Error when loading works with large number of files

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1156]
Loading a work that has a lot of files sometimes gives a JavaScript error as shown in the following screenshot.

Notice that the AJAX call to `/file-list` took a long time (I think 2 minutes) before it returned an error rather than the expected JSON response. You can also see that the response is what the load balancer shows rather than an "Rails" error message.

![Screenshot 2023-05-12 at 2 29 10 PM](https://github.com/pulibrary/pdc_describe/assets/568286/8bcd4603-3b01-4e74-bfca-c6d1fedec592)

We should figure out why these calls are taking so long (we already optimized this code) and we should handle this error more gracefully. 

Note: This error happened after the load issues reported in https://github.com/pulibrary/pdc_describe/issues/1154 and after Francis/Alicia biggie-size the servers -- the servers were not overloaded at the time of this issue.

**Comment by bess** [comment]
More insight on 16 May:
@carolyncole Did some testing that indicates that this has something to do with snapshot creation. Test this by deleting the UploadSnapshot for bitKlavier and then reloading the show page.

**Comment by hectorcorrea** [comment]
The culprit seems to be that our custom JSON serialization is including a reference to the work for every file in the work. For example, if a work has 3 files the serialization will include 3 files, but each of those 3 files will have a reference back to the work and therefore to the 3 files again. 

For a small number of files this goes unnoticed, but for large number of files (say 2000 files) this becomes a huge problem!

![Screenshot 2023-06-08 at 9 19 21 PM](https://github.com/pulibrary/pdc_describe/assets/568286/6e46cdea-792e-47d6-8280-972e88de64bf)
