### ISSUE TITLE
File uploader: missing one file

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1157]
## Description

Using the edit button, I opened a record that was already submitted to the curators. I proceeded to add two .jpg to the submission. Only the second file was uploaded. See image.

#### Files added to the uploader at one time in "Edit" mode after the record was submitted for review.
1. house-gd82355ded_1920.jpg (806kb; was uploaded first; does not appear in record)
2. explosion-gaed94f876_1280.png (472kb; was uploaded second; does appear in record)

## Image shows the second file was uploaded

![Screen Shot 2023-05-12 at 2 43 10 PM 2](https://github.com/pulibrary/pdc_describe/assets/50670293/9c08cbce-1159-4c24-a2e9-0c9b6ab96d1a)

The uploader widget will replace any files that the user selects with a new set of files until the click the save button.  There is no additive ability with the widget.

We propose to change the label above the button to reflect this
![Screenshot 2023-05-24 at 11.28.27 AM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/022d5b82-c825-499e-800a-4df5e70e59e3)

## Acceptance Criteria
- [ ] "Add More Files" will change to "Choose files to attach to this work"

**Comment by kelynch** [comment]
Verify whether this has been addressed already.
