### ISSUE TITLE
Update/add new ORCID IDs for PPPL

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1161]
Per [Chun's comment on this issue](https://github.com/pulibrary/pdc_describe/issues/127#issuecomment-1545828840) and a conversation on Slack, update/import 70 ORCID IDs to PDC Describe for PPPL researchers.

## Resources: 
* [ORCID Import documentation](https://github.com/pulibrary/pdc_describe/blob/main/docs/orcid_import.md)
* [search_netid repository](https://github.com/pulibrary/search_netid)

## Acceptance criteria

- [x]  New ORCID IDs are added to PDC Describe users appropriately based on the ORCID Import documentation (Kate developed this workflow initially, please consult them if you have questions).

- [x] Update the code if it does not update existing ones, or create the new ones

- [x] ORCID Import documentation is updated if needed to reflect how to follow it
- [x] Run in staging and production

**Comment by astrochun** [comment]
I've added the additional ORCID. We just need the NetID's.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1161?planning-poker) with Zenhub @bess @hectorcorrea @kelynch

**Comment by hectorcorrea** [comment]
Ran code as indicated in the instructions, fixed a couple of bugs (see linked PRs), ran update in staging and confirmed that new records look correct.

**Comment by hectorcorrea** [comment]
Records have been updated in production as well.

**Comment by hectorcorrea** [comment]
User page shows the current data: https://pdc-describe-prod.princeton.edu/describe/users/

**Comment by hectorcorrea** [comment]
@astrochun thanks for the heads up, I'll make a note to re-run the process next week.
