### ISSUE TITLE
Update codebase to refer to deletion_marker instead of tombstone

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1171]
There are [several references to "tombstone"](https://github.com/search?q=repo%3Apulibrary%2Fpdc_describe%20tombstone&type=code) states in the codebase.  To align with [inclusive language norms](https://github.com/pulibrary/pul-it-handbook/blob/main/norms/inclusive_language.md) in PUL IT, update references to "tombstones" to instead be called "deletion_markers."

- [ ] Change the three references to `tombstone` to `deletion_marker`

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1171?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii @kelynch
