### ISSUE TITLE
Fetching of S3 files in Work model

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1192]
There seem to be several methods in the Work model that do similar things when it comes to fetching files from S3. Some of them seem to be duplicates and/or with naming that is not quite as accurate today as it was when they written.

I think we should have one method for fetching from pre-curation and one that fetches from post-curation *regardless* of the status of the work. If I call post-curation I would expect files from post-curation to be fetched, where as the current code has logic that will decide to read from post curation or not depending on the status of the work.

Perhaps we should keep a method that have the smarts to account for the state when fetching files, there is probably a good reason for the existing logic, but since now we have legit reasons to fetch from pre or post curation at will it would be best to refactor the existing methods. 

Some of the methods to consider:
* pre_curation_uploads_fast
* post_curation_s3_resources
* post_curation_uploads
* s3_files 
* uploads
* pre_curation_uploads

**Comment by carolyncole** [comment]
May be closed by #1144
