### ISSUE TITLE
Describe Form: Datacite 4.4 (Mandatory Properties)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#120]
## Description

Datacite 4.4 mandatory properties/subproperties are required to mint DOIs. RDSS has expressed wanting to add Datacite schema to Describe in chucks to validate properties and be certain these are properly implemented. Mandatory properties have been identified to be implemented and tested first, because they will be necessary to implement other requested features, such as minting a DOI. 

### Reference

Datacite 4.4 Schema 
- [documents and examples](https://schema.datacite.org/meta/kernel-4.4/)
- [support documentation](https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties)   

## Acceptance Criteria 
- [x] Mandatory properties will be available in the describe form for research data
- [x] Mandatory sub-properties of the mandatory properties will also be available.
- [x] Controlled vocabularies will be applied to properties or subproperties as described in the Datacite schema 4.4 documentation. (Please reach out to Hannah if you are unsure about how these should be applied.) Other properties infomation can be freely written in to the field.
- [x] The applied properties and subproperties should be validated.

**Comment by hhkitsune** [comment]
This may duplicate components of other tickets. I was trying to capture the outcome of Friday's meeting, so please feel welcome to adjust, merge, or close as needed.

**Comment by carolyncole** [comment]
We believe that this ticket can be closed as the required metadata for Datacite can be entered and additional metadata fields will be ticketed separately.
