### ISSUE TITLE
Bug?: Submission is frozen for an extended period of time

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1258]
I had uploaded a very small file, 16MB and it took so long that I had thought it was frozen. It eventually went through, but was confused.

<img width="1338" alt="Screen Shot 2023-06-09 at 10 45 28 AM" src="https://github.com/pulibrary/pdc_describe/assets/20305734/b9a5cf7d-7c66-44e4-afe8-588372fb9605">

**Comment by hectorcorrea** [comment]
This was very likely slowness during the upload process. 

We've made a few enhancements to this, mainly going directly to AWS rather than using Active Storage during the upload process (see https://github.com/pulibrary/pdc_describe/pull/1279). Not sure if that closes this issue, but it might.

**Comment by kelynch** [comment]
Closing for now; will open a new ticket if/when this is encountered during acceptance testing.
