### ISSUE TITLE
Funders without award numbers produces error

### ISSUE THREAD

**Issue by Twade968** [pulibrary/pdc_describe#1261]
When adding a new funder without the award number the test fails. I have validated in the datacite schema that it is legal to have a funder without an award number. (see https://support.datacite.org/docs/schema-optional-properties-v43#193-awardnumber)

![Screenshot 2023-06-09 at 3 35 55 PM](https://github.com/pulibrary/pdc_describe/assets/81339170/048e10c7-2edc-4d98-9cb6-2fb7948a947e)

Acceptance Criteria
- [ ] add Max-Planck-Princeton Center for Plasma Physics (MPCC) to the "non-axisymmetric spec"

**Comment by kelynch** [comment]
This was addressed separately.

**Comment by hectorcorrea** [comment]
See PR https://github.com/pulibrary/pdc_describe/issues/1360
