### ISSUE TITLE
Curator questions/corrections for migration specs in pdc-staging

### ISSUE THREAD

**Issue by Twade968** [pulibrary/pdc_describe#1262]
**bitKlavier spec**

- [ ] There is an extra file present in the PDC file list. The extra file is titled “The bitKlavier Grand.pdf.txt.” This is not present in the DataSpace version or in Globus. Is PDC converting pdfs into text files during the migration?---(Halle ([@hb0344](https://github.com/hb0344)) at May 12, 2023 12:35)
- [ ] Will PDC still have collections? For example, in DataSpace, this item would have been part of the bitKlavier collection---(Halle ([@hb0344](https://github.com/hb0344)) at May 12, 2023 12:25)

**CKavity Library spec**

- [ ] there appears to be an extra README that was added to this record in PDC (README.txt.txt). This is not present in the Dataspace record---(Halle ([@hb0344](https://github.com/hb0344)) at May 12, 2023 10:26)
- [ ]  there is a difference in Publisher between this record and the corresponding one in DataSpace.---(Halle ([@hb0344](https://github.com/hb0344)) at May 12, 2023 10:24)

**Sowing the Seeds spec**

- [ ]  There is no publisher information listed in the DataSpace record, however, in PDC, it is listed as Princeton University. Does the migration automatically add a publisher if there isn’t any?---(Halle ([@hb0344](https://github.com/hb0344)) at May 11, 2023 16:47)
- [ ]  The related publication information from DataSpace did not copy over into PDC---(Halle ([@hb0344](https://github.com/hb0344)) at May 11, 2023 16:37)
- [ ]  In DataSpace, the publication year is listed as 2019 for this dataset, however in PDC, it is listed as 2023---(Halle ([@hb0344](https://github.com/hb0344)) at May 11, 2023 16:35)

**Comment by kelynch** [comment]
Resolved separately as part of migration (curators and others fix metadata in production).
