### ISSUE TITLE
HTML/JavaScript comment showing on the page

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1286]
When creating a new submission one of our HTML/JS comments is showing on the page:

![Screenshot 2023-06-23 at 1 13 07 PM](https://github.com/pulibrary/pdc_describe/assets/568286/2acc3ab0-10f2-4e5a-81a7-99cbf609179b)

**Comment by carolyncole** [comment]
LOL!  I totally did that...
