### ISSUE TITLE
Creator field display changes & Help Text

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1293]
## Description
(Kate; 6/28/23) Creators field display changes per meeting with Hannah today.

This ticket outlines visual changes to the Creators property set in the Describe form. We are making changes to better guide users to perform the mandatory steps without feeling anxious if they do not have additional information for the other options, such as the ROR. The fields are moved so the required fields (i.e., given and family name) come first. Larger asterisks will show next to the "Creators," "Given name," and "Family name" fields. We are also disambiguating the button for the help text by changing the "?" to "See more" and taking some of the essential help text out from behind this feature. The "See more" button will be used to hide lengthy help, rather than hiding all help text.

## Wireframe shows visual changes to the Creators property set

![Screen Shot 2023-06-28 at 4 41 22 PM](https://github.com/pulibrary/pdc_describe/assets/50670293/80237b40-f259-43c6-b209-2b154b60b778)

## Acceptance Criteria
- [ ] Larger asterisks for required fields (~24px use multiple of em)
- [x] Field order changing as follows (required fields marked with "*")
  - Creator * 
    - Given name * 
    - Family name * 
    - ORCiD
    - Affiliation
    - ROR

**Comment by hhkitsune** [comment]
My apologies for leaving the "ORCID" field out of the wireframe. As Kate had mentioned, it should go after the "Family Name" field.

**Comment by carolyncole** [comment]
Finally got https://github.com/pulibrary/pdc_describe/pull/1322 to pass
