### ISSUE TITLE
Check all 4 Globus boxes in honeybadger

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1300]
From our June 2023 globus outage: ACTION ITEM: We notice that we’re checking 3 out of 4 globus boxes in Honeybadger - we should check all 4 (documentation to add a site [here](https://github.com/pulibrary/rdss-handbook/blob/main/globus.md#monitoring))

## ACCEPTANCE CRITERIA
- [x] All four globus boxes are monitored by honeybadger

**Comment by carolyncole** [comment]
https://app.honeybadger.io/projects/103564/sites
