### ISSUE TITLE
Diagnose why pdc-describe-staging.princeton.edu is inaccessible for certain IP addresses/IP address ranges over the VPN

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pdc_describe#1301]
This was encountered during a meeting held on 07/07/23 by @bess, and I am afraid that I could not reproduce this:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/43eae306-6231-47d7-949b-4670b3dbac0c)

**Comment by kelynch** [comment]
Ongoing known issue with Princeton VPN for shifting IP ranges; closing.
