### ISSUE TITLE
Unknown user displayed in change history

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1329]
Change history is displaying "Unknown user" rather than the actual user name even for changes to files within PDC Describe. 

See this work as an example: https://pdc-describe-staging.princeton.edu/describe/works/422 -- although all the files were added and deleted within PDC Describe the change history displays "unknown user"

![Screenshot 2023-07-13 at 3 53 29 PM](https://github.com/pulibrary/pdc_describe/assets/568286/08097da7-0335-4255-95ac-1f391f02d2b0)

**Comment by hectorcorrea** [comment]
I wonder if the issue was introduced in this PR: https://github.com/pulibrary/pdc_describe/pull/1317/files - I said that because the issue is new-ish and the code in this PR references UNKNOWN_USER, not because I had debug the issue/code.

**Comment by carolyncole** [comment]
I believe 1371 closes this issue
