### ISSUE TITLE
Make provenance log manual entry available to appropriate users

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1341]
Provenance log is only visible to users configured in https://github.com/pulibrary/pdc_describe/blob/main/config/provenance_message_writers.yml.

Revisit this configuration and add appropriate users from RDSS and PRDS.  Kate will get a list and add to this ticket.

* Curators and moderators
* RDSS team?

**Comment by hhkitsune** [comment]
Adding some thoughts on access:

- RDSS should have access for testing and development. 
- PRDS and (potentially) others with moderator status should have access only after ticket #1336 is completed. This ticket provides labeling that will keep the log clean to read.
