### ISSUE TITLE
Not getting emails when I am @ in a comment

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1350]
@astrochun sent me 3 notifications yesterday and followed up via slack.

It could be related to this error:
https://app.honeybadger.io/projects/99214/faults/96805213

Or it could be something else, but I do not have an email for the @cac9 in these works:
  *  https://pdc-describe-prod.princeton.edu/describe/works/46
  * https://pdc-describe-prod.princeton.edu/describe/works/47
  * https://pdc-describe-prod.princeton.edu/describe/works/44

**Comment by carolyncole** [comment]
It was an enabling problem.  I wonder if we should email folks by default and force them to turn them off...

**Comment by astrochun** [comment]
> Hmm. I'm fairly sure there were periods that I had the notifications
> enabled and didn't receive any. Though there was a time when I noticed that
> my notification checkbox was disabled a mere few days after I enabled it.
>

I've at-ed a few folks during some of the fixture testing that should have
resulted in emails to Tyler and Bess.

**Comment by hectorcorrea** [comment]
@carolyncole This is the ticket that I created: https://github.com/pulibrary/pdc_describe/issues/1364 - not much on it, other than a reminder to look into it.
