### ISSUE TITLE
DOIs are incorrect in the following records

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1351]
https://pdc-describe-prod.princeton.edu/describe/works/46 - Should be blank so we mint a new one
https://pdc-describe-prod.princeton.edu/describe/works/44 - should be blank so we mint a new one
https://pdc-describe=prod.princeton.edu/describe/works/47 - Possibly needs to be set to 10.11578/1888269

I need to check with @astrochun on the last one.

**Comment by astrochun** [comment]
So it turns out that one of the dataset has a DOI from PRDS (rare exception). I spoke with @neggink about this.

Can you redo:
Data for "The value of fusion energy to a decarbonized United States electric grid"

and have the DOI set to `10.34770/f8em-3c49`
