### ISSUE TITLE
Email notification settings are being reset

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1364]
@astrochun reported the following

"FYI: It seems that everytime a new version is push to prod, the email notification checkbox is reset."

**Comment by carolyncole** [comment]
I do not see any point where the code disables the notifications on re deploy.  I'm wondering if some of the times with either rest the system, or updated the groups may have made it seem like things were being reset

**Comment by astrochun** [comment]
It seems to be fine now. Let's just monitor and reopen if the problem persists.
