### ISSUE TITLE
Error in download link for file

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1366]
This work in production https://pdc-describe-prod.princeton.edu/describe/works/64 shows two files, but clicking on any of the links gives the error message shown below.

# Show page
![Screenshot 2023-07-21 at 3 58 33 PM](https://github.com/pulibrary/pdc_describe/assets/568286/928fc87b-33e1-4e54-ac0e-ff34b6c923df)

# Error 
Error displayed when clicking on one of file links
![Screenshot 2023-07-21 at 4 00 29 PM](https://github.com/pulibrary/pdc_describe/assets/568286/12cbcdf8-00c5-47a9-b13b-45d04ddcbff7)

**Comment by kelynch** [comment]
This error occurs when a submitter who is not an admin views an unfinished submission's show page and tries to download the file.

The submitter of the object itself can still download the file, and moderators/admins can download the file.  I was able to replicate this error locally by submitting a file as one non-admin user, then logging in as another non-admin user and trying to download from the show page like the one in the screenshot above.

Small PR for the missing translation incoming.
