### ISSUE TITLE
Describe Form: New Submission Status Bar

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#137]
## Description

The new submission section of the Describe Form will feature a status bar that shows the end-user where they are at in the process of creating the submission. The status bar shouldn't have too many steps and will fill in with an accent color that shows where the user is at in this process. I have suggested steps in the image below (see left of red arrow), but we can modify these if needed. 

(note: Please reach out to Hannah if you have other thoughts or ideas for how the status bar may display. Your creativity and knowledge are much appreciated to help refine this feature!) 

### Here is a description of the suggested steps:

**Describe**
- In this section, the end-user will enter their information to metadata fields.

**Deposit**
- In this section, the end-user will either attach their smaller submission of files to the form or let the curators know where/how they may find and access the submission of files. Smaller submission that are attached to the form will have a pipeline to either the curatorial workstation or a staging area. This is the half-way point of the process and end-users will return to the main page after completing it. They will return once the curators have reviewed their submission.

**Review**
- End-users will receive a note on the main page that they have messages to review. They will open their draft submission and the status bar will show they are now in review. They will be able to read messages from the curators and write back (and forth) if needed. They will also be able to submit or re-submit small files.

**Completed**
- Once the curator has approved the submission and it has been pushed to published, the status bar will show that the submission has been completed. End-users may still message a curator if they wish to request changes made to their published submission.

![Screen Shot 2022-05-23 at 1 33 46 PM](https://user-images.githubusercontent.com/50670293/169888373-f5f64ae5-b414-4340-a152-60a93fde1ce9.jpeg)

## Acceptance Criteria

- [ ] A status bar will show users where they are at within the new submission section of the form.
- [ ] The status bar will be simple (with few steps), so the process doesn't feel too complicated.
- [ ] The status bar will have an attractive accent color that is noticeable on the page, but not too loud.

**Comment by hectorcorrea** [comment]
The HTML/CSS for the "submission status bar" is now available here: https://github.com/pulibrary/pdc_describe/blob/main/app/views/works/_wizard_progress.html.erb

It is already in use for [Step 0](https://github.com/pulibrary/pdc_describe/pull/141) and [Step 1](https://github.com/pulibrary/pdc_describe/pull/141).
