### ISSUE TITLE
405 Not Allowed error when Migrating Data

### ISSUE THREAD

**Issue by kconnellmail** [pulibrary/pdc_describe#1372]
Edited & then tried to migrate Dataspace files for https://pdc-describe-prod.princeton.edu/describe/works/50 & it resulted in a 405 Not Allowed Error.

**Comment by carolyncole** [comment]
I will try out the new release (pushing the button) to see how this works now...  After that test hopefully we can close this ticket

**Comment by carolyncole** [comment]
I went ahead and tried migrating on production:
I![Screenshot 2023-08-02 at 1.36.42 PM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/97ff927a-f00b-436b-9d1a-3fc025118ebe)!

the dspace job is currently processing:
![Screenshot 2023-08-02 at 1.36.22 PM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/254a169c-83db-4605-a822-cdb487519074)

**Comment by kconnellmail** [comment]
So it worked for you?  Great.  I was thinking it might have something to do
with my account settings/permissions.  Either way, Bess Sadler told me this
project is hold for now anyway, so perhaps now it's a moot point.  Thanks!
KPC

**Comment by carolyncole** [comment]
@kconnellmail We updated the software to put the processing in the background.  It has been running now for 30 minutes.  It was never going to complete in the time a web request allows...

**Comment by carolyncole** [comment]
Unfortunately putting the work in the background did not solve the problem with this record.  The system fails to download 2_23_2017_0.archive.tar.gz I'm going to do a bit more digging...

**Comment by carolyncole** [comment]
Last issue: 2_23_2017_2.archive.tar.gz which is too big at 6.18 GB for a standard upload, is not being migrated.   Need to look into uploading with multipart. The other files are now in the record.

**Comment by kconnellmail** [comment]
Whoa.  Big file.  Thanks for the update.  Make sure Bess Sadler knows about
this?
