### ISSUE TITLE
Disk space monitoring in production servers

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1374]
The disks in `pdc-describe-prod1` and `pdc-describe-prod2` filled up yesterday, `df -a` showed no available space under `/dev/mapper/ubuntu--vg-ubuntu--lv`

We noticed that folder `/tmp/dataspace_download` had some large files and we deleted it. That recovered about 30% of disk space on the partition.

We should monitor disk space on these boxes and get alerted when they are running low on disk. 

We should also make sure the migration process cleans up files after the migration completes and handle the case when there are errors in the migration process. It looks like the migration won't delete files if there are errors: https://github.com/pulibrary/pdc_describe/blob/main/app/services/pul_dspace_migrate.rb#L110-L113

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1374?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii

**Comment by jrgriffiniii** [comment]
This must be delayed until `isinga`, and it was confirmed during the RDSS check-in meeting for 08/31/23 that disk space monitoring is not desired for Datadog.

**Comment by acozine** [comment]
Currently monitored by Sensu. Will be moved to our new monitoring platform by the end of October.

**Comment by carolyncole** [comment]
Ran [the instructions](https://github.com/pulibrary/pul-it-handbook/blob/main/services/checkmk.md) for adding the servers to checkmk
```
ansible-playbook playbooks/utils/checkmk_add_local_checks.yml --ask-vault-pass --limit pdc_describe_production -e checkmk_folder=linux/rdss
ansible-playbook playbooks/utils/checkmk_agent.yml --ask-vault-pass --limit pdc_describe_production -e checkmk_folder=linux/rdss
```

<img width="1512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0t6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6272a61bc8e2a3813d072e4df3af44555875de1/Screenshot%202024-09-05%20at%201.08.55%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 1.08.55 PM.png" />
