### ISSUE TITLE
Notification Dashboard for each user

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1381]
As a user I would like a spot where I can go and see all notifications that have been sent to me.

For the moment we are just going to produce a paginated list that includes all the notifications sorted newest first.

Later this dashboard may include filtering by group, or search.  That is not part of this ticket.

Completion Criteria:

- [ ] When I am logged in I get a link under my user for notifications
- [ ] When I am logged out I can not get to notifications
- [ ] When I am a super admin I can see others notifications (maybe not right now)
- [ ] When I click on the link I am taken to a paginated page of notifications.  
- [ ] The notifications uses data tables so it looks similar to other pages in the system

**Comment by kelynch** [comment]
PRDS would like this too.
