### ISSUE TITLE
Bug: Unable to use "Migrate files" button

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1389]
I'm not sure why, but both @ErinEMcC and I created a few new dataset from the dropdown menu in the upper right. However, we don't see a button to migrate the files. When we try to edit the metadata, we get prompted to upload a README. Perhaps we are doing something wrong, but this was perplexing. I include a screenshot for one of the datasets we started last week.

<img width="1499" alt="Screen Shot 2023-07-31 at 12 42 19 PM" src="https://github.com/pulibrary/pdc_describe/assets/20305734/28f1e93a-5474-4d82-b29e-ea3b3ec4cc57">

For reference, I'm a "Moderator" on PPPL.

**Comment by carolyncole** [comment]
Test with new version to see if the update to background solves this issue.  Ref #1372

**Comment by astrochun** [comment]
> Test with new version to see if the update to background solves this issue. Ref #1372

I just tried v0.75.0 on prod and it seems to still be an issue.

**Comment by carolyncole** [comment]
@astrochun We updated the UI to have a specific Migrate option in the UI, so please choose that option next time you migrate an object.  Previously there was a migrate button next to the save which had to be hit for the migrate dataspace data to be present.  I'll set the flag on your recent works in production.

**Comment by carolyncole** [comment]
@astrochun I updated https://pdc-describe-prod.princeton.edu/describe/works/71 to be a migrated record.  you should now see the button.

**Comment by astrochun** [comment]
> @astrochun I updated https://pdc-describe-prod.princeton.edu/describe/works/71 to be a migrated record. you should now see the button.

@carolyncole so what is the problem?

**Comment by astrochun** [comment]
@carolyncole we now do see a "Migrate Dataset option". However, @ErinEMCC didn't know, so we have one more record that needs to be a Migrate Dataset: https://pdc-describe-prod.princeton.edu/describe/works/73
