### ISSUE TITLE
Describe Form: "Submit New" button

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#139]
## Description

The end-users homepage will feature a navigation button that allows them to create a new submission. If the button is selected, the end-user is taken to the page shown in ticket #135. Please see the example in the image below, upper-right side of the image.

![Screen Shot 2022-05-23 at 2 49 42 PM](https://user-images.githubusercontent.com/50670293/170039142-8fdb2b0f-b159-4e30-9758-ebb86dc8c351.jpeg)

## Acceptance Criteria

- [ ] There will be a navigation button on the end-users portion of the form that allows them to create a new submission.
- [ ] If the button is selected, the end-user will be taken to the page shown in ticket #135

**Comment by carolyncole** [comment]
There is a submit new button.  I believe this ticket remained open in error
