### ISSUE TITLE
Populate DOI in spreadsheet for PPPL items

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1390]
In the [migration spreadsheet](https://docs.google.com/spreadsheets/d/148EHw1FuYhd4kqov5UA04cpSekMGGlAy3zakBwuowFo/edit#gid=684248489), populate the DOI column for all PPPL works. 

## Acceptance criteria
- [x] All PPPL works have a DOI, fetched from the OSTI website
- [x] The DOI is for the dataset, not for the associated publication

**Comment by bess** [comment]
Finished by @astrochun

**Comment by astrochun** [comment]
This was done using a python script. See https://github.com/pulibrary/dspace-osti/pull/83
