### ISSUE TITLE
Dublin core input form

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#14]
- [ ] We have an input form that allows the description of theses, dissertations, and Library PDFs (use our fixture objects as a guide) using the latest Dublin Core schema (https://www.dublincore.org/2020/01/20/dublin_core_terms.ttl)
- [ ] Every object must go into a `Collection` where the `User` who is submitting has the role of `submitter`
- [ ] Field names use dublin core names so we can export as RDF or XML down the road and know we've got the right field name
- [ ] The form indicates what version of Dublin Core it is using and provides a link to the schema definition
- [ ] We do not need to implement every Dublin Core field, only the ones needed to describe the data sets in hand

**Comment by jrgriffiniii** [comment]
This is also going to be of value given that the DataSpace metadata to be migrated is already in Dublin Core.
