### ISSUE TITLE
AWS S3 bucket with strange folder

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1409]
There is a folder named "10-34770" in our precuration buckets `pdc-describe-prod-precuration` and `pdc-describe-staging-precuration`.

I am not sure what is creating this folder. The expected folder name is "10.34770" and that folder does exists, but I am not sure what is creating the one with the dash.

I think we should delete the "10-34770" from both buckets and see if it gets created again. It could be that it was created with a buggy version of the code and not longer an issue, but it could also indicate an existing bug in the code.

![Screenshot 2023-08-09 at 2 55 23 PM](https://github.com/pulibrary/pdc_describe/assets/568286/b0d2c76d-dada-45c5-b3df-f0e5fd83074e)

Completion criteria

- [ ] Investigate when the bucket get create by deleting it and running migration
- [ ] If the migration does not create it, try some additional tasks

**Comment by hectorcorrea** [comment]
Deleted the "10-34770" folder from pdc-describe-prod-precuration and pdc-describe-staging-precuration.

![Screenshot 2023-08-10 at 10 24 48 AM](https://github.com/pulibrary/pdc_describe/assets/568286/328a0b1d-e07f-4ba2-a1c3-6dbf3a1a8a2a)

![Screenshot 2023-08-10 at 10 25 01 AM](https://github.com/pulibrary/pdc_describe/assets/568286/229553db-ce38-4420-976f-41ec73d96a0b)

**Comment by carolyncole** [comment]
The folders are back.  Now we need to figure out why they are being created...  10-34770 is a dspace folder, so maybe something with the migration is creating the folder....

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1409?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii

**Comment by carolyncole** [comment]
From what I can tell it shows up when we migrate a work that has directories: https://pdc-describe-staging.princeton.edu/describe/works/390
