### ISSUE TITLE
Bug: Files are deleted after approval

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1416]
The record in question is: https://pdc-describe-prod.princeton.edu/describe/works/64

After I approved it, it showed:
```
August 10, 2023 13:51 by Chun
marked as Approved

 August 10, 2023 13:51 by Unknown user outside the system
Files Deleted: 25
```

There are now only 4 files.

Completion criteria:

- [ ] Add a flash message that indicates the files are being moved in the background
 "Your files are being moved to the post-curation bucket in the background. Depending on the file sizes this may take some time."

**Comment by astrochun** [comment]
The files later appear, but unsure why it deletes and then readds.

**Comment by carolyncole** [comment]
related to #1417 This is when the files are move from the pre-curation to post-curation automatically after the approval.

We need some better messaging to the user about what is going to happen in the background.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1416?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii
