### ISSUE TITLE
Describe Form: "Funder" property requests for the PPPL Group pipeline

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1421]
# Description

PPPL users would benefit from being able to more easily fill out the funder information under the "additional metadata" tab. All PPPL submissions will have the US Department of Energy as a funder. It would therefore be ideal to have this ROR information auto-populate to the Funder set for all PPPL submissions. 

If we cannot auto-populate this field (for the PPPL group only) in the short-term, we should alternatively add to the help text (for the PPPL group only) in the Funder set, the ROR information for US Dept of Energy. This could be added in the same way it was done for the "Creator" set, which has the ROR link that can be copy/pasted into the ROR field.

## ROR Info

United States Department of Energy
https://ror.org/01bj3aw27

## Acceptance Criteria
- [ ] If possible, the funder field will be auto-populated (for PPPL group only) with the ROR for the US Dept of Energy, which has been provided in this ticket. This should happen for every record in the PPPL Group pipeline.
- [ ] If possible, the funding number for the Lab's contract should be included. It is "DE-AC02-09CH11466" (see #331)
- [ ] If we cannot auto-populate in the short-term, then add the ROR information (as written in the ROR info for this ticket) to the help text for the Funder set for the PPPL group only.

**Comment by carolyncole** [comment]
For both the migrated and new PPPL data sets
