### ISSUE TITLE
Describe Form: Change PPPL's Default Publisher

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1424]
# Description

In DataSpace, PPPL's publisher was: Princeton Plasma Physics Laboratory, Princeton University. (See: [sample record](https://dataspace.princeton.edu/handle/88435/dsp01ft848t262)) The default in PDC Describe is: Princeton University. We would like to change the default for the PPPL Group pipeline only. All submissions to the PPPL Group pipline should have this new default. All records from the PRDS Group pipeline should remain with the default: Princeton University.

## PPPL Default Publisher
Princeton Plasma Physics Laboratory, Princeton University

## Acceptance Criteria
- [x] The default publisher will change for the PPPL Group only (Please see above for the new default publisher.)
- [x] The default publisher for PRDS Group will remain unchanged.

**Comment by hectorcorrea** [comment]
With PR #1453 the publisher defaults correctly:
* for records migrated via the "Migrate PPPL Dataset" button and 
* for new submissions created by users with only access to the PPPL group

New submissions for users with access to *more than one group* will still have "Princeton University" as the default publisher.
