### ISSUE TITLE
Strip spaces in names

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1431]
We should strip spaces from given and family names in creators, otherwise we carry those values to Discovery and then the data displays funny

![Screenshot 2023-08-14 at 2 03 55 PM](https://github.com/pulibrary/pdc_describe/assets/568286/da393c7c-8b26-492a-a050-7d6f71278207)

![Screenshot 2023-08-14 at 2 04 01 PM](https://github.com/pulibrary/pdc_describe/assets/568286/580c8b87-0536-4cc4-9b1c-0f2501170f25)

Completion Criteria:

- [ ] Clean up the names to remove spaces that a user adds on input before saving the data to the record

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1431?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii
