### ISSUE TITLE
Improve workflow for PPPL subcommunities

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1439]
As a staff member with permission to deposit in both Research Data and PPPL Groups, I should be able to select the PPPL group early in the workflow so that I have access to the PPPL subcommunities the first time I'm describing a record. Instead, the current workflow requires me to migrate or save the record first, then go back to select the PPPL subcommunities. 

## Acceptance criteria
- [ ] Add a menu item for "Migrate PPPL Dataset" that sets the Group to PPPL from the start
- [ ] There is also a menu item for "Migrate PRDS Dataset"

**Comment by hectorcorrea** [comment]
See also this ticket: https://github.com/pulibrary/pdc_describe/issues/1424 -- we can probably default the Publisher at the same time.
