### ISSUE TITLE
ARK not updated for 88435/dsp01rb68xg060

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1479]
The ARK for this work: https://pdc-describe-prod.princeton.edu/describe/works/71
Was not updated when the work was approved.

## Acceptance criteria
- [x] Figure out why
- [x] Fix the problem and document it if possible

## Backtrace

[pdc_describe/production] Notice: Unable to update EZID 88435/dsp01rb68xg060: Net::HTTPServerException: 400 "Bad Request"

    line 38 of [PROJECT_ROOT]/app/models/ark.rb: rescue in update
    line 28 of [PROJECT_ROOT]/app/models/ark.rb: update
    line 579 of [PROJECT_ROOT]/app/models/work.rb: update_ark_information

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/99588858)

**Comment by bess** [comment]
Individual arks update just fine when I try them again. Maybe this is some kind of intermittent network issue? I added a retry so it will back off and try again when it encounters an issue.
