### ISSUE TITLE
[pdc_describe/production] Notice: Unable to update EZID ark:/88435/dsp01dz010t189: Net::HTTPServerException: 403 "Forbidden"

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1480]
## Backtrace

    line 38 of [PROJECT_ROOT]/app/models/ark.rb: rescue in update
    line 28 of [PROJECT_ROOT]/app/models/ark.rb: update

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/99333930)

**Comment by bess** [comment]
This ark resolved with no intervention.
