### ISSUE TITLE
Embargoes for files

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1491]
Enable objects in PDC Describe to have their descriptive metadata indexed into PDC Discovery when approved, but not their files if those files are embargoed.  File embargoes at the file level are handled and enforced by curators, with embargoed files stored somewhere separate from PDC Describe infrastructure/storage while they are embargoed.  

Objects in PDC Describe would still need to have a README associated with it in order to be approved, but all files to be embargoed are stored outside of PDC Describe, and then after the embargo period is done, they are attached to the object via PDC Describe/Globus manually by the curator. 

## Potential method: 
- [ ] Add a date field to "embargo files" on an object in PDC Describe during curation (in "Curator Controlled" metadata)
- [ ] Update PDC Discovery to skip indexing on all files attached to an object when the object's metadata has an embargo date set with a value that is a date in the future.  PDC Discovery should index files on objects that have either no embargo date set, or an embargo date set to the past or the current day.
- [ ] Display a message in PDC Discovery to indicate that files are embargoed, including the embargo date, eg "File(s) associated with this object are embargoed until 2024/01/01."
- [ ] Write an end-to-end system spec in PDC Describe demonstrating what it looks like to create an item with an embargo, so we can ensure all parts of the system continue to work together

**Comment by jrgriffiniii** [comment]
I am nearly complete with extending the `Work` model to support embargo dates, however, my only delay has been some ongoing troubleshooting with Sass preprocessing for improving the styling for the form:

![image](https://github.com/pulibrary/pdc_describe/assets/1443986/ef0dfea6-90a6-4b58-a203-9fdb67581517)

**Comment by jrgriffiniii** [comment]
After the undertaking of testing within the `staging` environments for PDC Describe and PDC Discovery, the following two pull requests are all which remain from fully-resolving this issue:

- https://github.com/pulibrary/pdc_discovery/pull/512
- https://github.com/pulibrary/pdc_describe/pull/1544
