### ISSUE TITLE
Change Plasma Science and Technology sub-community to "Discovery Plasma Science"

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1496]
Because of some reorganization, PS&T is now DPS. To avoid confusion to researchers, this sub-community should be renamed. We should also make sure this is reflected in the metadata for existing records.

- [x] Changed PS&T to "Discovery Plasma Science"
- [x] Check that meta data for DPS is correct for existing records

## Moved to a separate ticket:
Also, we need to create a new sub-community called "Applied Materials and Sustainability Sciences"
- [ ] ~[Create "Applied Materials and Sustainability Sciences"](https://github.com/pulibrary/pdc_describe/issues/1498)~

**Comment by bess** [comment]
Output of job in production:

> Updating work 85
> Updating work 48
> Updating work 45
> Updating work 66
> Updating work 40
> Updating work 77
> Updating work 64
> Updating work 84
> Updating work 103
> Updated subcommunities metadata, recorded user bs3097 in WorkActivity

![Screenshot 2023-09-13 at 8 30 57 AM](https://github.com/pulibrary/pdc_describe/assets/65608/49c8c1be-43f2-43d0-ab97-f54b8de99ebe)
