### ISSUE TITLE
Illegal characters in legacy data

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1512]
AWS S3 and its associated libraries have certain characters that cannot be in filenames. See [this reference](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) for a complete list. When we have legacy data where the file names contain characters that S3 deems illegal, commands to move that data into S3 fail.

Records known to be affected:
1. Examination of OH and H2O2 production by uniform and non-uniform modes of dielectric barrier discharge in He/air mixture: [In dataspace](https://dataspace.princeton.edu/handle/88435/dsp01j3860b20c) and [In PDC Describe](https://datacommons.princeton.edu/describe/works/103)

![Screenshot 2023-09-13 at 9 54 24 AM](https://github.com/pulibrary/pdc_describe/assets/65608/de703861-6862-4639-8c2d-2cc22b7a1cb5)

## Acceptance criteria
- [x] Rename the files to something that is AWS legal. Replace all illegal characters with a `_` (underscore) ([source](https://stackoverflow.com/questions/21184720/how-to-rename-files-and-folder-in-amazon-s3))
- [x] Ensure there are no duplicate file names after the renaming by appending a (1), (2) at the end of the filename if the file has been renamed
- [x] Keep a record of all of the file names as they originally existed and what they were renamed to
- [x] The record goes into a file called `files_renamed.txt`, which contains a list of all files that have been renamed and what they were renamed to, along with a timestamp
- [x] This `files_renamed.txt` file gets added to the dataset as a payload file, akin to a README.txt or license.txt

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1512?planning-poker) with Zenhub @bess @jrgriffiniii @kelynch
