### ISSUE TITLE
Illegal characters in newly submitted data

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1513]
AWS S3 and its associated libraries have certain characters that cannot be in filenames. See [this reference](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) for a complete list. When we have legacy data where the file names contain characters that S3 deems illegal, commands to move that data into S3 fail.

## Acceptance criteria
- [ ] Check filenames as they're being uploaded and show the user an error if they have illegal characters in the filename
- [ ] Show the user what was illegal and ask them to re-name files and resubmit
- [ ] This will be accomplished as a rails validation
- [ ] mark https://app.honeybadger.io/projects/99214/faults/100266108#notice-params as resolved when this ticket is completed

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1513?planning-poker) with Zenhub @bess @jrgriffiniii @kelynch
