### ISSUE TITLE
Fix typo: Date format is missing a Y

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1555]
<img width="807" alt="Screenshot 2023-10-04 at 8 08 52 AM" src="https://github.com/pulibrary/pdc_describe/assets/65608/7fdcd251-9b77-4f16-8314-068b0026d0d5">

**Comment by avyuktsoni0731** [comment]
Hi @bess . Can i please get this issue assigned to me?
 
Thanks :)
