### ISSUE TITLE
"Add me as a Creator" button does not fetch family name

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#156]
As a researcher in a hurry, I want to quickly be able to add myself as a creator on a dataset I'm submitting. Having my ORCiD already on file makes this easy, except that in version v0.6.0 it isn't populating the family name from ORCiD, but instead puts in the string "family-name". 

Unclear whether this is a more widespread problem. My name in ORCiD is "Elizabeth (Bess) Sadler" so I wonder if there is an issue with unexpected name formatting? 

![Screen Shot 2022-06-03 at 12.20.28 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/05cf301d-7173-40c6-ab00-724c7b06d38a)

**Comment by hectorcorrea** [comment]
@bess this issue will fix it: https://github.com/pulibrary/pdc_describe/issues/154

**Comment by hectorcorrea** [comment]
Closed by https://github.com/pulibrary/pdc_describe/pull/158
