### ISSUE TITLE
Update this error message to include enough information to identify the User

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1578]
## Backtrace

    line 11 of [PROJECT_ROOT]/app/controllers/work_downloader_controller.rb: download

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/98018105)

**Comment by kelynch** [comment]
Reported by a user trying to edit an object and they cannot.  Would be helpful to include the user's UID (net ID) instead as part of the error.
