### ISSUE TITLE
PDC Globus Postcuration outage response

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1585]
Update at standup 10/26:
Francis suggests that the outage might have been on the Globus end. We should open a support ticket with them and let them know about the issue. They might ask us for logs, which we can best provide now, not two weeks from now.
- [x] Open a support ticket with Globus asking them whether anything happened on their end
- [ ] Provide them with any logs they request
- [x] Ensure any undocumented parts of this process are in the RDSS handbook

Update 26 Oct: It came back up without intervention, but we need to know why it went down.

- [x] Inform stakeholders about the outage
- [x] Schedule a post-incident meeting: Scheduled for 7 November

Honeybadger reported that "PDC Globus Postcuration is down", see https://app.honeybadger.io/projects/103564/sites

Globus monitoring instructions: https://github.com/pulibrary/rdss-handbook/blob/main/globus.md#monitoring

Connecting via SSH to the `pdc-globus-prod-postcuration` box and running the command recommended in the Monitoring page hangs:

```
globus-connect-server endpoint show
```

The same command gives the expected information in the `pdc-globus-prod-precuration` box.

**Comment by carolyncole** [comment]
It came back up at 3am.  Not sure what is up with that or how to find out.

**Comment by bess** [comment]
<img width="586" alt="Screenshot 2023-10-26 at 7 54 31 AM" src="https://github.com/pulibrary/pdc_describe/assets/65608/1b34f3ab-0fd8-4a0d-bb47-568cd56f0e71">

**Comment by bess** [comment]
I'd like to schedule a post-incident for this and see if we can figure out what happened.

**Comment by hectorcorrea** [comment]
The call to `globus-connect-server endpoint show` on `pdc-globus-prod-postcuration` also returns the expected information (as opposed to hanging):

```
$ globus-connect-server endpoint show
Display Name:    Production PDC Postcuration
ID:              blah-blah-blah
Subscription ID: blah-blah-blah
Public:          True
GCS Manager URL: https://blah.blah.data.globus.org
Network Use:     normal
Organization:    Princeton University Library
Contact E-mail:  lsupport@princeton.edu
```

**Comment by hectorcorrea** [comment]
Globus reported that they did not have a outages on their end.

```
We don't track historical health data for given endpoints, 
so we're unable to answer questions in that vein.
 
With regards to questions regarding a potential Globus outage between 12PM EST 10/25/2023 and 
3:17AM EST 10/26/2023, we have no such records or reports.
 
This doesn't mean that there wasn't some larger issue at your site that could have interfered with 
connectivity for your endpoint, but we are unable to speak to such possibilities.
```
