### ISSUE TITLE
An ARK is minted for each newly created object

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#16]
- [ ] When a new object is created via one of our input forms, it receives an ARK from ezid. That ARK is recorded with the object.
- [ ] In testing and staging, use ezid test service
- [ ] When this is done, there is an object input form that submits to a collection, associates the submitted object with the userid that created it, and it has an ark. There is not yet any meaningful metadata.

**Comment by hectorcorrea** [comment]
Closed by https://github.com/pulibrary/pdc_describe/pull/54
