### ISSUE TITLE
ApprovedFileMoveJob Can not find the ApprovedUploadSnapshot

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1607]
We are continuously getting errors where the ApprovedFileMoveJob can not find the ApprovedUploadSnapshot.  It was not getting retried because of an [error in sidekiq](https://github.com/pulibrary/pdc_describe/pull/1606), but why is this happening???

**Comment by jrgriffiniii** [comment]
This does not seem to have occurred again since 11/09/23 (https://app.honeybadger.io/projects/99214/faults/102051630). I am going to proceed with marking this as resolved, and reopen this should it reoccur.
