### ISSUE TITLE
Give higher privileges for Erik Gilson, one of the data reviewers

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1609]
I got Erik Gilson to sign into PDC Describe. Unfortunately the menu for email notifications did not include the list of collections.

I'm not sure what level is needed here, but desire is to have him be able to select which collections he should review and to receive email notifications.

**Comment by kelynch** [comment]
This should be addressed, I made Erik a group admin for PPPL collections on production.  Let me know if he cannot see the email configs.

**Comment by astrochun** [comment]
> This should be addressed, I made Erik a group admin for PPPL collections on production. Let me know if he cannot see the email configs.

Thanks. What is the order of access because I know we have Moderator access, correct?
