### ISSUE TITLE
The DOI is Finalized When the object is approved (Step 3 of 0-3)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#161]
### *This describes Step 3 in a process of DOI Creation that has 0-3 Steps. This step performs in the background, the end-user has completed steps 0-2. Step 3 is a final process for the completion of a Datacite DOI.*

Previous Steps:
- **step 0** the end-user has viewed the submission choice screen (see ticket: https://github.com/pulibrary/pdc_describe/issues/135)
-  **step 1** the end-user has agreed to create a new submission which reserves the draft DOI and displays the handle (see ticket: https://github.com/pulibrary/pdc_describe/issues/136)
- **step 2** the middle process has occurred in the background after the curators have approved the submission for publication

The remaining step is triggered after the completion of Step 2. The curator has selected the "approve" button for a submission, which triggers Step 2 and the DOI is registered with DOI resolver. Step 3 is automatically triggered after the completion of Step 2. In Step 3 the DOI becomes findable, which completes the process of DOI creation.

### Image shows the "approve" button the curator must select to initiate Steps 2-3 of DOI creation.

![Screen Shot 2022-06-21 at 9 32 30 AM](https://user-images.githubusercontent.com/50670293/174813708-606012fe-98bb-4cfd-b801-b9a8203b5f4c.jpeg)

## Acceptance Criteria

- [x] Step 2 will be triggered by the curator's selection of the "approve" button and Step 3 will be triggered by the completion of Step 2.
- [x] Step 3 will make the DOI findable

**Comment by carolyncole** [comment]
ref #236 A list of items that should be done for this ticket to be completed.  We will create separate issues and add them as part of this Epic.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/161?planning-poker) with ZenHub @bess @jrgriffiniii
