### ISSUE TITLE
Document DOI pre-minting/minting process

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#162]
This will be helpful in communicating with other departments and organizations at Princeton such as PPPL about our plans and workflows for DOIs.

Relevant tickets:
* https://github.com/pulibrary/pdc_describe/issues/160 
* https://github.com/pulibrary/pdc_describe/issues/161

**Comment by bess** [comment]
@hhkitsune will take a first pass at this and give it to @kelynch for feedback.
