### ISSUE TITLE
Additional Metadata doesn't look clickable 

### ISSUE THREAD

**Issue by leefaisonr** [pulibrary/pdc_describe#1635]
### User Story
As a PDC submitter, I need clear guidance toward the additional metadata that the curators recommend, so that I can enter it up front and get my submission approved as quickly as possible.

### Context
PDC testers unanimously found it difficult to locate the "Additional Metadata" section of the Describe step in the submission wizard. Currently, there is no underline or button box that would indicate to a user that the section tab is clickable:

![PDC-Describe_NewSubmission-Describe_AddlMetadataButton_2024-03-06](https://github.com/pulibrary/pdc_describe/assets/66128387/775871e0-b536-4992-9ddb-a76b59a00483)

### Acceptance Criteria 
- [ ] Add a [btn-light](https://getbootstrap.com/docs/4.0/components/buttons/) for "Additional Metadata" and "Required Metadata" to make them look more clickable
- [ ] Add an indicator to clarify which section of the form the user is on (i.e a different color button)
- [ ] The check for incomplete required fields can still happen when the user attempts to advance from the "Additional Metadata" section to the "Readme" step

**Comment by JaymeeH** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1635?planning-poker) with Zenhub @jrgriffiniii @bess @kelynch
