### ISSUE TITLE
[pdc_describe/staging] Errno::EIO: Input/output error is raised when attempting to deserialize UploadSnapshot models

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pdc_describe#1637]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/102905883)

**Comment by hectorcorrea** [comment]
@jrgriffiniii Given that the error happened in staging and it mentions `reline` I suspect that this is somebody exiting IRB. Not 100% sure about this, but I've seen `reline` before in those instances.

**Comment by jrgriffiniii** [comment]
Ah, thank you very much @hectorcorrea! I was still struggling to find where this might be occurring. I will close this issue then.
