### ISSUE TITLE
Globus production issues

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1638]
Globus production issues on 1/3/2024 (we also had short hiccup on 12/25/2023)
Manually rebooted the box. Self-diagnostic reported 700+ tasks and 1.3 GB. 
Same as issue https://github.com/pulibrary/pdc_describe/issues/1633

**Comment by hectorcorrea** [comment]
Rebooted the machine to get it going. But this is an issue that we look more closely since it is now happen some what often.

**Comment by hectorcorrea** [comment]
We are not actively working on this issue (Globus has been up with no issues). Kate will schedule a meeting with other folks at Princeton that also use Globus for us to share ideas and issues.

**Comment by hectorcorrea** [comment]
This issue happened again on 2/22/2024. @carolyncole rebooted the server and that took care of it.

**Comment by hectorcorrea** [comment]
Issue happened again on 3/3/2024. @carolyncole rebooted the server and that took care of it.
