### ISSUE TITLE
SPIKE: How do we escalate globus issues? 

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1639]
Ideas:
- [ ] Make sure everybody in the team receives the Honeybadger alerts when it goes down
  - [x] Bess
  - [x] Jaymee
  - [x] Robert
  - [ ] James
  - [x] Carolyn
  - [x] Kate
  - [x] Hector 
- [ ] Contact globus support? 
- [ ] Isn't there a setting for number of processes in globus?
- [ ] Should we set aside some time for an ensemble?
- [ ] Can we compare with the PRDS globus and make sure the settings are the same? 
- [x] Add monitoring to PRDS globus (it might be failing too and we wouldn't notice)
- [ ] Look at AWS network monitoring
- [ ] Ensure cloudwatch is enabled on all globus boxes

**Comment by bess** [comment]
@hectorcorrea is going to contact globus and ask what their level of support is. We might just need to set expectations with stakeholders that this is not a 24x7 service.

**Comment by hectorcorrea** [comment]
Globus responded. Our contract indicates:

"Provider will respond during Business Hours to all Support Requests submitted by a Named Support Contact in respect of Services within one (1) business day of receipt of such Support Request, and will use its commercially reasonable efforts to promptly resolve such Support Requests"

**Comment by carolyncole** [comment]
Added the uptime check for PRDS Globus: https://app.honeybadger.io/projects/103564/sites/a309c7c4-b995-4458-afcf-789b6418f5d7

**Comment by leefaisonr** [comment]
We have activated slack notifications for HoneyBadger Globus uptime checks.

**Comment by kelynch** [comment]
Draft Globus user policy (WIP) here - https://docs.google.com/document/d/1ylKXRmJrZX7P41FdPX6_r4G696-S7Baip98WyhKP7JY/edit
