### ISSUE TITLE
Bug: incorrect count on items in Describe

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1651]
When working on Sam Cohen's dataset, I noticed that the top says 478 files or directories but only 477 is seen. The latter is correct. I think we might be counting the <item_no> folder here.

![Screen Shot 2024-01-17 at 7 07 30 AM](https://github.com/pulibrary/pdc_describe/assets/20305734/28774c4f-04cb-4035-b878-2cd080054751)

**Comment by hectorcorrea** [comment]
That's strange...in also says "Showing 1 to 10 fo 477 entries" at the bottom ¯\_(ツ)_/¯

**Comment by carolyncole** [comment]
@astrochun the bottom table only shows files.  The top count is both Files and directories. That said, since this work only has files the top calculation seems to be including the top level directory along with the files in the directory.
