### ISSUE TITLE
Add the following PPPL data reviewers for the PPPL portal

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1656]
We need to have the following included as moderator. Princeton NetID included

- [x] Stan Kaye (skaye)
- [x] Kenneth Hammond (kch2 / kenneth.hammond)
- [x] Erik Gilson (already added; egilson)
- [x] Rajesh Maingi (maingi)
- [x] Ammar Hakim (ammar)
- [x] Nate Ferraro (nferraro)
- [x] Peter Dugan (pdugan)
- [x] Marc Cohen (macohen)
- [x] Rob Sheneman (rshenema)

**Comment by bess** [comment]
I added these users by hand per the instructions in the README. 

```
user.add_role(:group_admin, Group.plasma_laboratory)
```
