### ISSUE TITLE
clean up S3 Access logs

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1658]
https://s3.console.aws.amazon.com/s3/buckets/pdc-describe-logs?bucketType=general&region=us-east-1&tab=objects#
Logs need to be purged regularly.

**Comment by hectorcorrea** [comment]
As an experiment, I ran the following command to get a list of all the files that we have in the `pdc-describe-logs` bucket:

```
aws s3 ls --summarize --human-readable --recursive s3://pdc-describe-logs/ > pdc_describe_logs.txt
```

Lo and behold we have 9 million files (9,273,338 to be exact). 

The command took about 75 minutes to run and it gave me a list of all the files and their dates. The list is available here: https://drive.google.com/file/d/1fhyNJLWYCEfHVPCcq5bS8DmBxZ4FcQGP/view?usp=drive_link

We could go throught that list and start deleting files older than X.

**Comment by carolyncole** [comment]
I set up a lifecycle rule to delete all objects in the log bucket that are older than 60 days.  In theory at midnight Amazon should expire all the old objects. https://us-east-1.console.aws.amazon.com/s3/buckets/pdc-describe-logs?region=us-east-1&bucketType=general&tab=metrics

**Comment by carolyncole** [comment]
I took the weekend, but the bucket size is finally down and there are no logs from 2023!
![Screenshot 2024-10-21 at 8 47 30 AM](https://github.com/user-attachments/assets/7681f527-734c-4c3b-ba9e-08cf97fdd538)

**Comment by hectorcorrea** [comment]
@carolyncole this is fantastic! I am glad you found a way to deal with this within the AWS toolkit!
