### ISSUE TITLE
Describe Form: Admin/Curator "Approve" Button

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#166]
## Description

The Admin/Curator side of the describe form will include an "approve" button. This will allow the curator to approve submissions for publication and completes the DOI creation process (see tickets #160 and #161)

## User Story

Our curator Neggin has carefully reviewed the depositor's submission. After negotiating changes to make a submission more FAIR (findable, accessible, interoperable, and reusable) she has made any changes and is ready to approve the submission for publication. She will easily do this by selecting the "approve" button, which will be found around the top of the editing page and may be co-located with other helpful buttons. Selecting the "approve" button will also trigger Steps 2-3 of the DOI creation process, which completes the minting of the DOI. This makes the process much faster and smoother for curators like Neggin who have other dities to attend to.

### Image shows the "approve" button the curator must select to initiate Steps 2-3 of DOI creation.

![Screen Shot 2022-06-21 at 9 32 30 AM](https://user-images.githubusercontent.com/50670293/174813708-606012fe-98bb-4cfd-b801-b9a8203b5f4c.jpeg)

## Acceptance Criteria
- [ ] An "approve" button will be at the top of the editing page for curators or other administrative users.
- [ ] Selecting the "approve" button will complete Steps 2-3 of the DOI creation process.

**Comment by hectorcorrea** [comment]
Only curators can approve datasets

The approval process includes:
* Mark the DOI as final
* Publish to DataCite the metadata for the dataset 

The dataset becomes read-only once it has been approved.
* You cannot delete a dataset once it has been approved.

We should also remove the "withdraw" button until we figure out the process to deal with changes to datasets once approved.

**Comment by hectorcorrea** [comment]
Closed with PR #481
