### ISSUE TITLE
Add additional PPPL sub-communities

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1662]
Per @kelynch, I'm creating this issue ticket. In preparation for the completion of DataSpace migration (and forthcoming support), there are three sub-communities that should be created in PDC Describe (selectable under Additional Metadata - Subcommunity field):

1. "Computational Science" (no dataset existed in DataSpace but plans are being made to regroup certain datasets after a reorganization at PPPL)
2. "Applied Materials and Sustainability Sciences" (this is a new department established a year ago)
3. "DIII-D" (New support for DIII-D datasets from PPPL researchers)
4. "Tokamak Experimental Sciences" (this is after some recent reorganization)

Acceptance Criteria:

- [ ] Add above sub-communities to https://github.com/pulibrary/pdc_describe/blob/main/app/models/group.rb#L171
- [ ] Have an automated test for at least one of the new ones

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1662?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by astrochun** [comment]
Please note that I closed out #1663 as I decided it should not be a rename but a new sub-community. I've updated the original request accordingly. Sorry for the confusion.

**Comment by kelynch** [comment]
DIII-D group is the highest priority; there is a PPPL-led demo for this group in a meeting on Feb 23.

**Comment by astrochun** [comment]
Has this change been implemented on production or just staging?

**Comment by hectorcorrea** [comment]
@astrochun Production
