### ISSUE TITLE
Bug: Unable to download files under Edit mode due to incorrect URL

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1665]
One of the PPPL researchers point out that if you're in "Edit" mode on a record and you click on blue link for a data/file that was uploaded, it returns an error:

View from Edit mode:
![Screen Shot 2024-01-31 at 2 18 07 PM](https://github.com/pulibrary/pdc_describe/assets/20305734/fbc6363c-15b8-4196-bb71-0f77a5ef083d)

The error page:
![Screen Shot 2024-01-31 at 2 19 10 PM](https://github.com/pulibrary/pdc_describe/assets/20305734/6213742b-b80b-465b-a04b-d031eab2a320)

The issue, I think stems from the URI, with duplicate "246" for the record ID:
https://datacommons.princeton.edu/describe/works/246/246/download?filename=10.34770/dq61-gf89/246/Figure10

Note that this issue doesn't happen in the View mode for the record, which does permit downloading the file.

**Comment by astrochun** [comment]
Unfortunately, I don't think this is fixed and in fact it directs to PDC Discovery. Here's the link for one file:

```
https://datacommons.princeton.edu/works/288/download?filename=10.34770/hr5y-c816/288/Bodner_PPCF_2024_PublicDataset.zip
```

Notice that there is no "describe". We had to give a reviewer the direct link since clicking the file did not download the file.

**Comment by astrochun** [comment]
@hectorcorrea and @jrgriffiniii, I should clarify that this is breaking both on the dataset view and the Edit status

**Comment by hectorcorrea** [comment]
This might be related to this other issue that we fixed yesterday: https://github.com/pulibrary/pdc_describe/issues/1704 -- the culprit was also the lack of `/describe` at the front of the URL
