### ISSUE TITLE
Update Review page with new Distribution Agreement

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/pdc_describe#1667]
### Context

We initially inherited the distribution license from DataSpace, as implemented previously via #764. In the submission workflow, it shows like this on the Review page:

![PDC-Describe_Submission_Review-License_2024-02-05](https://github.com/pulibrary/pdc_describe/assets/66128387/fb6b4755-c84a-44d5-9408-5c4eae437c94)

We have a new Distribution Agreement for PDC, reviewed and approved by OGC in conjunction with the new Acceptance and Retention Policy (both publicly available at https://researchdata.princeton.edu/introducing-princeton-data-commons). Now we need to update the Review page.

While we're at it, we can correct the turn-around time indicated on this page to match the latest: 5-10 business days.

![PDC-Describe_Submission_Review-LicenseUpdate_2024-02-05](https://github.com/pulibrary/pdc_describe/assets/66128387/01fe39b8-0b4b-4579-b74f-580163b1aa2c)

### Completion Criteria
- [ ] Delete the text currently above the box containing the Distribution Agreement (it is redundant to the new Distribution Agreement text)
- [ ] Replace the entirety of the Distribution Agreement with the following text (including hyperlinks):
<blockquote>

In furtherance of its non-profit educational mission, Princeton University makes certain research data available to the public through its Princeton Data Commons (PDC). In order for PDC to reproduce, translate, and/or distribute your submission for public access, your agreement to the following terms is necessary. Please take a moment to read the terms of this agreement.

By clicking through this agreement, you (the author(s) or creator(s) or copyright owner(s)) hereby grant to Princeton University the non-exclusive, worldwide, perpetual, irrevocable, royalty free right to reproduce, translate (as defined below), and/or distribute your submission (including the abstract) worldwide in electronic format.  This license is in addition to any rights in the submission that Princeton University may hold based on other contracts, licenses, University policies, or applicable law.

You represent that the submission is your original work, and/or that you have the right to grant the rights contained in this license. You represent that your submission does not, to the best of your knowledge, infringe upon anyone's copyright and does not violate any laws or breach any contracts (for example, research agreements that supported the project) or other licenses.  If the submission contains material for which you do not hold copyright, you represent that you have obtained the unrestricted permission of the copyright owner to grant Princeton University the rights required by this license, and that such third-party owned material is clearly identified and acknowledged within the text or content of the submission.

Because Princeton University owns the copyright in any work that any member of the University staff creates in the course of his or her assigned duties at the University ("University Work Product"), University Work Products may not be deposited in Princeton Data Commons without first securing the written consent of the University supervisor who is responsible for the creation and dissemination the University Work Product. Such consent must include acknowledgement by the supervisor that the University Work Product can, and will, be made available to the general public.  Regarding copyright ownership of faculty work products, including software, please see the University’s [Copyright Policy](https://copyright.princeton.edu/policy).

You also represent, to the best of your knowledge, that public distribution of your submission will not violate the personal privacy rights or other proprietary rights of any group or individual. You agree that Princeton University may translate the submission to any medium or format as deemed reasonably necessary by the University, e.g., for the purpose of preservation.

You also agree that Princeton University may keep more than one copy of this submission for purposes of security, back-up, and preservation.

If the submission is based upon work that has been sponsored or supported by an agency, company, or other organization other than Princeton University, you represent that you have fulfilled any right of review or other obligations required by such contract or agreement.

You acknowledge that you have read the “[Data Acceptance and Retention Policies and Guidance for the Princeton Data Commons Data Repository Service](https://drive.google.com/file/d/1GECvKoOjwqvKTKYvyNThCyzTWjD6cPxs/view?usp=sharing),” which is incorporated by reference into this agreement, and that you agree to the policy’s terms and conditions.  The policy addresses topics including data acceptance, embargo, retention, cost, retraction/takedown, and migration.  In addition, Princeton University reserves the right to make unavailable and/or remove from PDC any submission or content which it deems to be in violation of this agreement.

</blockquote>

- [ ] Below the box containing the Distribution Agreement, change the text "2-5 business days" to "5-10 business days"

**Comment by jrgriffiniii** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1667?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
