### ISSUE TITLE
Redirect PPPL DataSpace collections to PDC

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1677]
Redirect collections with the "Ready!" status in the "ARK Migrated?" column [in this spreadsheet](https://docs.google.com/spreadsheets/d/1D0z4xQsLqAZQPJtSjOdn81u25siaCU3u3Fn93r-0vyA/edit#gid=1032867214) to the PDC Discovery URLs in the "PDC Discovery URL" column on the same row.

## Collections to be migrated:

* Princeton Plasma Physics Laboratory
* ITER and Tokamaks
* ITER and Tokamaks - PPPL Collaborations
* Spherical Torus
* Spherical Torus - MAST-U
* Spherical Torus - NSTX
* Spherical Torus - NSTX-U
* Theory
* Theory - Theory
* Theory and Computation

## Completion Criteria

* Each of the above-listed collections' arks are redirected to PDC Discovery correctly
* The above-linked spreadsheet is updated to reflect this

**Comment by bess** [comment]
done!
