### ISSUE TITLE
Revise the New Submission splash page to reflect new policies

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/pdc_describe#1683]
### User Story
As a PDC submitter, I need to know in advance what the policies are for acceptance and retention, especially the potential costs involved, before I begin my submission, so that I do not proceed with minting a DOI and submitting without realizing that PDC might not actually work for me.

### Context
The PDC policies changed in February 2024, but the New Submission splash page does not currently signal potential deal-breakers like costs associated with large submissions. We need to do our best to inform submitters before they submit, which we can do, in part, by updating the information provided on the New Submission splash page:

![PDC-Describe_NewSubmission_Splash_2024-03-06](https://github.com/pulibrary/pdc_describe/assets/66128387/3187aa53-480a-49d7-8d33-274b0b70c413)

### Completion Criteria
- [x] Insert a new line that reads "Before you proceed, please review the PDC policies for [Acceptance and Retention](https://drive.google.com/file/d/1GECvKoOjwqvKTKYvyNThCyzTWjD6cPxs/view?usp=sharing) and [Distribution](https://drive.google.com/file/d/1E8EgfyL2yB2rH0xCIIqYrTFE0QfY8Sk_/view?usp=sharing) to be sure your intended submission is eligible for PDC, that you are authorized to grant permission for redistribution, and that you are prepared to pay any applicable costs. If you are unsure about any of these points, please [reach out to our team](mailto:prds@princeton.edu) before submitting."
- [x] Include the embedded links as above
- [x] Make the words "review the PDC policies" bold
- [x] Insert the new line as its own paragraph between the existing first and second paragraphs
- [x] In the current second paragraph, update the link for "PRDS Data Repository Help Page" to https://researchdata.princeton.edu/research-lifecycle-guide/princeton-research-data-repository

**Comment by carolyncole** [comment]
@matthewjchandler  Would it be better to make the first step of the wizard a review of the policies?  With the ability to say pleas do not show this to me again?  If you really want them read that is a better way.

**Comment by matthewjchandler** [comment]
Good idea @carolyncole! I was trying not to introduce to much new to the software, because we need to move quickly. But if a new first step is an option, I'd like to pursue that.

**Comment by hectorcorrea** [comment]
Agreed, I think adding a new first step won't be too much work
