### ISSUE TITLE
Refine the navigation buttons for the submission wizard

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/pdc_describe#1684]
### User Story
As a PDC submitter, I need to have clear and consistent navigation buttons throughout the submission wizard, so that I can be assured that I'm not missing anything and save myself from surprises and hassles through the curation process after I submit.

### Context
PRDS engaged several beta testers after PDC - Describe version 1.0 was released. The testers expressed deep misgivings with the current layout of the submission workflow, with particular confusion over navigating through the wizard. We can address the concerns by refining the action buttons at the bottom of each page/section of the submission wizard.

In particular, I propose a standard four-button layout: "Cancel" at the lower-left; and at the lower-right, "Previous", "Save", and "Next" (in that order). We would naturally deviate from the standard on the first and last steps.

So then the "Required Metadata" portion of the Describe step would keep the existing "Cancel" button in the lower-left, but revise the lower-right with "Save" and "Next" buttons:

![PDC-Describe_NewSubmission-Describe_ActionButtons_2024-03-06](https://github.com/pulibrary/pdc_describe/assets/66128387/1600c19e-5c56-4eba-9801-9e6824ce30d1)

Another repeated complaint is that submitters don't realize there's any opportunity to enter required metadata (addressed in part by #1635), which is a problem for curators. We can address those issues on the first page of the Describe step by making the (new) "Next" button take the submitter to the "Additional Metadata" portion of the Describe step.

The additional metadata page can keep the same body contents, but revise the action buttons at the bottom to match the new consistent layout:

![PDC-Describe_NewSubmission-Describe-Addl_ActionButtons_2024-03-06](https://github.com/pulibrary/pdc_describe/assets/66128387/37d342bb-1d82-4a54-9e25-a16ec7eef59a)

At the Readme and Upload steps, we not only need to revise the lower-right buttons, but also the existing "Go Back" buttons to become "Cancel". The Cancel button should have the same action on every page: exiting the wizard without saving whatever has changed since the last save.

![PDC-Describe_NewSubmission-Readme_ActionButtons_2024-03-06](https://github.com/pulibrary/pdc_describe/assets/66128387/0a40db31-2db6-477a-9807-d481b45e068b)

![PDC-Describe_NewSubmission-Upload_ActionButtons_2024-03-06](https://github.com/pulibrary/pdc_describe/assets/66128387/026e3043-a8f6-489e-ae9d-fd4dbec5c155)

The Review page should be a bit different, given the need for clarity in granting the license and completing the submission, but still in line with the navigation scheme:

![PDC-Describe_NewSubmission-Review_ActionButtons_2024-03-06](https://github.com/pulibrary/pdc_describe/assets/66128387/0bdc3db1-12e8-4fd2-9c8b-097d84aa91ce)

### Completion Criteria
- [x] The Required Metadata page from Describe step has 2 buttons in the lower-right instead of the current "Save Work" button:
  - [x] The "Save" button saves the entered values without advancing
  - [x] The "Next" button saves the entered values and advances the user to the "Additional Metadata" page of the Describe step
- [ ] The Additional Metadata page from the Describe step has 3 buttons in the lower-right instead of the current "Save Work":
  - [ ] The "Previous" button returns the user to the "Required Metadata" page without saving anything
  - [ ] The "Save" button saves the entered values without advancing
  - [ ] The "Next" button saves the entered values and advances the user to the Readme step
- [x] The "Go Back" button on the Readme, Upload, and Review steps is replaced with a "Cancel" button, which exits the wizard without saving any changes made since the last save
- [x] The Readme and Upload steps get 3 buttons in the lower-right instead of the current "Continue" button:
  - [x] The "Previous" button returns the user to the previous page without saving anything
  - [x] The "Save" button saves the entered values and/or uploaded files without advancing
  - [x] The "Next" button saves the entered values and/or uploaded files and advances the user to the next step
- [x] The Review step keeps the existing "Grant License and Complete" button, but adds 2 navigation buttons to the lower-right:
  - [x] The "Previous" button returns the user to the Upload step without saving anything
  - [x] The "Save" button saves any entered value for the message to curators box, without advancing

**Comment by carolyncole** [comment]
@matthewjchandler Does a cancel mean cancel the process?  We are going to get a bunch of DOIs created and then cancelled if we allow the user to cancel the entire process. Does the cancel just return the user to. their dashbord, but leave the DOI and work created?

**Comment by matthewjchandler** [comment]
@carolyncole  As noted above, the Cancel button should have the same action on every page: exiting the wizard without saving whatever has changed since the last save. This applies to the Describe step and beyond; it happens after the submitter has already affirmed that they understand that they are creating a new DOI. I would indeed expect that exiting the wizard means returning to the dashboard, where one can see that the submission is started but not completed yet, and then return to it when they are ready.

**Comment by matthewjchandler** [comment]
As of Version: 1684-buttons, last updated: 03 April 2024, I'm seeing a "Previous" button on the "Required Metadata" portion of the "Describe" step:

![PDC-Describe_Submission_Describe-1-ActionButtons_2024-04-03](https://github.com/pulibrary/pdc_describe/assets/66128387/39f5fa6d-c3ff-43d9-9df6-a8afc7197a66)

The "Previous" button should not appear here. When clicked, it takes me back to the "New Submission" page, which asks for confirmation about creating a DOI, after the point is moot.
