### ISSUE TITLE
SPIKE: Redesign the New Submission Upload page

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/pdc_describe#1685]
### User Story
As a PDC submitter, I need clear instructions for submitting my data files, with assurances that I am proceeding as I am supposed to, so that I can avoid a confusing and/or time-consuming conversation with the curators.

### Context

Multiple PDC testers criticized the file upload workflow: it gives no options for uploading files from multiple local sources; it does not spell out which files have been selected when there are multiple; when one tries to make a second selection, it just overwrites the first selection; and it does give a confirmation of successful upload.

![PDC-Describe_NewSubmission-Upload_SelectedFiles_2024-03-06](https://github.com/pulibrary/pdc_describe/assets/66128387/6338ace3-2ae9-4a1d-bfc2-f0bb9db90801)

Moreover, in PDC, after one advances to the Review step and then returns to the Upload, it appears that the uploaded files are removed. This really threw our testers through a loop.

They expected something more like what DataSpace provides: options of multiple uploads on one page, with immediate information on progress and success, and then a way to make revisions to the files after upload (including anything uploaded by mistake).

![DataSpace_Upload_2024-03-07](https://github.com/pulibrary/pdc_describe/assets/66128387/1c78c72a-140c-491e-9b22-4f4c4483a172)
![DataSpace_Upload-Progress_2024-03-07](https://github.com/pulibrary/pdc_describe/assets/66128387/2a084042-1b7e-4697-b895-38b153163d30)
![DataSpace_Upload-Success-Multi_2024-03-07](https://github.com/pulibrary/pdc_describe/assets/66128387/996b7c7c-2628-4c1e-b6e9-22c3b731b852)
![DataSpace_Upload-Revise_2024-03-07](https://github.com/pulibrary/pdc_describe/assets/66128387/28d85b2c-74e2-48e9-8a63-92f558516af5)

Back to PDC. I'd recommend we build on the file viewer that exists in the curator/moderator view:

![PDC-Describe_ModeratorReview-Files_2024-03-07](https://github.com/pulibrary/pdc_describe/assets/66128387/92ca6b11-2827-4556-aae8-1877a9ce17e9)

After selecting and uploading, submitters need to see what they have there and decide whether they are missing something or included something by mistake. This is a strong point made by multiple testers.

### Criteria for the solution
- [ ] On the "file-upload" page, add the following functionality:
  - [ ] The ability to select multiple files from multiple local sources and in multiple selection operations
  - [ ] Immediate confirmation with a list of all files successfully uploaded
  - [ ] The ability to remove some files after upload

## Criteria for this ticket
- [x] Hector is going to investigate what UI options are available to us and report back. 
- [x] Schedule a meeting with RDSS + Matt Chandler
- [x] Spend 1 hour discussing options and make tickets

**Comment by carolyncole** [comment]
@matthewjchandler I think there is some confusion on when the upload actually occurs.  The upload doe snot occur until  after the user click continue.  When you say multiple sources, I am unsure what you mean?  Do you mean you want to allow them to select a location on the web?

**Comment by matthewjchandler** [comment]
@carolyncole The testers have indeed been very confused about what is happening at the Upload step of the wizard. As explained above, the issues with this step are: it gives no options for uploading files from multiple local sources; it does not spell out which files have been selected when there are multiple; when one tries to make a second selection, it just overwrites the first selection; and it does give a confirmation of successful upload.

Multiples sources means multiple drives/folders to which the user has direct access on their local machine. Currently, if I try to select files from one local source, and then add files from another local source, then my first selection gets overwritten by my second selection. I need to be able to select any number of files from any number of local drives/folders in any number of selection operations. Whenever I have completed a selection operation, I need to see everything I have selected so far, so I can decide whether I need to select more, or whether I need to de-select anything.

**Comment by carolyncole** [comment]
@matthewjchandler so are you asking for the upload to occur while the user is on the screen, or just a list of files selected for upload and the ability to add/ remove items from that list.  I'm just trying to be clear, because the dpsace example is files being uploaded as the user chooses them.

**Comment by matthewjchandler** [comment]
@carolyncole I could conceive of the user experience being resolved in multiple ways, and I would advocate for whichever is the simplest/fastest method. The criteria, again, as above, are:
- The ability to select multiple files from multiple local sources and in multiple selection operations
- Immediate confirmation with a list of all files successfully uploaded
- The ability to remove some files after upload

The DSpace example shows multiple points of confirmation for the user, along with the ability to remove files after successful upload. We don't have to do things exactly the same as DSpace, but we do need to accomplish criteria for which DSpace provides useful reference points.
