### ISSUE TITLE
Update language on submission form

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1689]
## Context

The PDC policies changed in February 2024, such that there are firm limits on free submission sizes, but the Upload page does not currently give users any indication that they can't just submit whatever they want. We need to do our best to inform submitters before they start sending us data, which we can do, in part, by updating the language included on the Upload page.

In addition, the mechanisms for transfer that PRDS uses have changed since PDC - Describe v1.0 was released. Now, it doesn't matter whether data is stored on a Princeton research cluster or somewhere else, so we can clean up the options given (and omit the "file-cluster" page).

![new_submission_language](https://github.com/pulibrary/pdc_describe/assets/65608/a4c8d4db-522e-4929-ab44-abee794aacce)

## Acceptance criteria
- [x] At the top of the first page for the Upload step, insert a new paragraph that reads, "PDC can accommodate submissions of all sizes, but please be aware that [large data submissions](https://researchdata.princeton.edu/research-lifecycle-guide/publishing-large-datasets) usually take more time and may require assistance from PRDS staff, and [very large submissions may have costs associated](https://drive.google.com/file/d/1GECvKoOjwqvKTKYvyNThCyzTWjD6cPxs/view?usp=sharing). If you have any questions, please contact [prds@princeton.edu](mailto:prds@princeton.edu) before proceeding."
- [x] Include the embedded links in the above language
- [x] Delete the option "located on a Princeton research Cluster."
- [x] Deactivate the "file-cluster" page that was opened by selecting the above option
- [x] Change the language of the now-second option to read "more than 100MB or I am unable to upload."
- [x] Update the language on this form as indicated by the screenshot

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1689?planning-poker) with Zenhub @carolyncole @JaymeeH @jrgriffiniii @kelynch

**Comment by leefaisonr** [comment]
<img width="1512" alt="image" src="https://github.com/pulibrary/pdc_describe/assets/108823963/6e28b712-c692-4f09-a93f-35f2aca59e49">
