### ISSUE TITLE
Draft ADR on shutting down research data collections

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/pdc_describe#1693]
### Transitioning Research Data Submissions from DataSpace to PDC - Describe
Date: 2024-03-15

### Status
Decided

### Context
As of February 2024, PRDS began encouraging new submitters to the institutional data repository to use PDC - Describe instead of DataSpace. Repeat submitters to DataSpace, however, have been permitted to continue initiating new submissions to DataSpace without intervention. PRDS intends to send messages by the end of March 2024 to all those enabled to submit to research data collections in DataSpace informing them of the upcoming deprecation of DataSpace. These messages to DataSpace users will give April 15 as the date for transition to PDC, but PRDS and RDSS will need some time to phase out DataSpace for research data. Those users who have unfinished submissions in the DataSpace workflow as of April 15 will need to receive extra prompting, but for those collections that do not have any submissions in the workflow, we do not need to wait.

### Decision
The process of shutting down research data collections curated by PRDS will begin on April 16, 2024 and end no later than April 30, 2024. If there are any unfinished submissions in the research data collections as of April 16, 2024, PRDS we will provide a list of all email addresses for the initiators of these unfinished submissions, so that PRDS can warn them to complete their submissions or risk losing all saved data and metadata. If there are any research data collections that do not have unfinished submissions in the workflow as of April 16, 2024, we will begin by selecting one or two to shut down promptly and monitor the consequences. If all research data collections still have unfinished submissions in the workflow as of April 16, 2024, we will wait to begin shutting any down until PRDS has given fair warning to all affected users. If, after receiving the warning message from PRDS, a given collection is cleared of all unfinished submissions before April 30, 2024, then we may shut it down without delay. All DataSpace research data collections curated by PRDS must be prevented from receiving any new submissions whatsoever no later than April 30, 2024.

### Consequences
- PDC - Describe will become the only institutional research data repository available to the Princeton Community as of May 1, 2024
- Some potential DataSpace submitters will be forced to transition to PDC - Describe before May 1, 2024, if the specific collection to which they are enabled to submit has already been shut down
- If any unfinished research data submissions remain in DataSpace as of May 1, 2024, we can decide on a case-by-case basis what to do with them

**Comment by kelynch** [comment]
Moved from discussion to decision in RDOS/RDSS meeting
