### ISSUE TITLE
DataCite - Using an existing ARK updates the ezid metadata

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#17]
When we're migrating an object, it will already have an ARK. When that's the case, do not register a new ARK. Instead, update the metadata at ezid to point to the new location.

ACCEPTANCE CRITIERIA
- [x] The DataCite input form has a place for an existing ARK
- [x] When that field is filled out, the form validates that the ARK is legit before allowing submission
- [x] When the existing ARK field is filled out with a legit ARK, no new ARK is registered
- [x] When the existing ARK field is filled out with a legit ARK, the metadata at ezid is updated to point to the new location of the object

**Comment by carolyncole** [comment]
@bess It was not clear, but there was already ARK validation in the system: https://github.com/pulibrary/pdc_describe/pull/281/files#diff-ebe838f9d71d26b6227d6d37c96a7e2d93fb68a80d55075c7f2374bfcb4688abR339-R343

**Comment by carolyncole** [comment]
No new ark is registered after this commit: aa9c96ee97e2c3d8e205e1bd556a9d86c35fcef2
Should we really test a negative?

**Comment by bess** [comment]
@carolyncole Not totally sure what to do here, since we're not totally clear on whether we're registering new arks on the regular. As long as we're pretty sure we're not proliferating new arks I'm fine with whatever you deem appropriate testing.

**Comment by carolyncole** [comment]
The final item can be checked off by this existing test: https://github.com/pulibrary/pdc_describe/blob/main/spec/system/migrate_submission_spec.rb#L103-L145
