### ISSUE TITLE
Replace a file in post curation

### ISSUE THREAD

**Issue by sec122** [pulibrary/pdc_describe#1709]
Task: Replace a file in post curation

DOI of published dataset in question: https://doi.org/10.34770/6gc9-5787
Title: The 3D3A Lab Binaural Room Impulse Response (BRIR) Dataset

Replace a single file in post curation with another file. 

- File to delete: paper.pdf

- File to add: methods.txt

<img width="764" alt="image" src="https://github.com/pulibrary/pdc_describe/assets/60932884/a99b963a-629f-4577-9b86-cc77f8559f72">

Replace the deleted file “paper.pdf” with “methods.txt” - file emailed to @hectorcorrea 

Acceptance Criteria: 
- [ ] Paper.pdf file replaced with methods.txt file for https://doi.org/10.34770/6gc9-5787 in post curation bucket

**Comment by hectorcorrea** [comment]
Replaced the file directly in AWS and the new file now shows in PDC Describe and PDC Discovery. 

![Screenshot 2024-03-21 at 3 33 15 PM](https://github.com/pulibrary/pdc_describe/assets/568286/3136c760-1568-4958-a59b-a81bae6bf8e5)
