### ISSUE TITLE
Document how to load PPPL ORCID IDs

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#171]
Document how to use the ORCID rake task and where to find the spreadsheet, in the `docs/` directory.

[Spreadsheet here](https://docs.google.com/spreadsheets/d/1U6AuWCLogVGBcNXmH4p6o8ZQc2nleyt0s0TedOpNkC0/edit#gid=0)

### Acceptance Criteria

* Create a `docs/` directory
* Document how to load PPPL user data (and generate net IDs) and include a reference to the spreadsheet
* Test the documentation with someone else on the RDSS team

**Comment by astrochun** [comment]
@bess @Twade968 

An additional list is available in this attachment. This includes past staff/researchers and has overlap with the above list.

[member_portal_public_2023-01-12_extra.csv](https://github.com/pulibrary/pdc_describe/files/10864651/member_portal_public_2023-01-12_extra.csv)
