### ISSUE TITLE
Error on Create Dataset

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1717]
As an admisitrator or curator, select "Create Dataset" from the dropdown menu

You should not see the error:

<img width="459" alt="Screenshot 2024-03-26 at 2 01 00 PM" src="https://github.com/pulibrary/pdc_describe/assets/1599081/07fcb573-bb89-4c0d-8e77-b9928428b3ed">

**Comment by bess** [comment]
We believe this has been fixed.
