### ISSUE TITLE
Direct link login bumps you to discovery instead of describe root

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1748]
When I have a direct link and get redirected to login on the production (~~and staging servers~~ the error happens in Production but works fine in Staging)

Steps to reproduce:
* Open a browser in incognito mode
* Go to a direct link for a dataset in PDC Describe in production (e.g. https://datacommons.princeton.edu/describe/works/282)
* Notice how the browser redirects you to PDC Discovery's home page: https://datacommons.princeton.edu/discovery/

The system should have instead asked the user to login and then take them to the correct dataset.

I believe the issue is because we have configured Nginx to automatically send people to Discovery when the URL does not have the `/describe` prefix. The same issue happens if you go to https://datacommons.princeton.edu/batman)

I suspect our page not found or authentication redirect is not including the `/describe` in the URL when it tries to handle the incognito user visiting the URL.

**Comment by hectorcorrea** [comment]
Notice how curl against a Describe URL in **production** redirects to the sign in page for Discovery (i.e. it does not have `/describe` on the URL

```
curl https://datacommons.princeton.edu/describe/works/285
<html><body>You are being <a href="https://datacommons.princeton.edu/sign_in">redirected</a>.</body></html>~/src/pdc_describe
```

Whereas a curl to a similar URL in the **staging** environment returns the proper URL:

```
curl https://pdc-describe-staging.princeton.edu/describe/works/583
<html><body>You are being <a href="https://pdc-describe-staging.princeton.edu/describe/sign_in">redirected</a>.</body></html>~/src/pdc_describe
```

**Comment by hectorcorrea** [comment]
Not sure this discrepancy between Staging and Production matters, but I noticed that group_vars for Staging is defined as (https://github.com/pulibrary/princeton_ansible/blob/main/group_vars/pdc_describe/staging.yml):

```
passenger_server_name: "{{ inventory_hostname }}"
```

but in Production is defined as (https://github.com/pulibrary/princeton_ansible/blob/main/group_vars/pdc_describe/production.yml):

```
passenger_server_name: "pdc-describe-prod1.princeton.edu"
```

**Comment by hectorcorrea** [comment]
I suspect the call to `sign_in_and_redirect @user, event: :authentication` in https://github.com/pulibrary/pdc_describe/blob/main/app/controllers/users/omniauth_callbacks_controller.rb#L10 is getting the wrong redirect URL.

Looking at the code for `sign_in_and_redirect` in Devise provides instructions on how to overwrite this method, https://github.com/heartcombo/devise/blob/main/lib/devise/controllers/helpers.rb#L190-L243, not for the faint of heart, but we might have hit that point with our weird URL root at datacommons.princeton.edu

Another strange thing that I noticed while debugging locally is that the call to `after_sign_in_path_for(resource)` **inside Devise `sign_in_and_redirect`** returns `/` but the same call within the `OmniauthCallbacksController` controller returns the expected path (e.g. /works/38)

**Comment by hectorcorrea** [comment]
I am having second thoughts. I don't think the problem is in the code in https://github.com/pulibrary/pdc_describe/blob/main/app/controllers/users/omniauth_callbacks_controller.rb#L10 because that code does not get called until a User has authenticated. 

From the look of I think the problem is happening _before_ this code is even executed. Notice that the `curl` command below is calling the `sign_in` page already without the `/describe`. The code in the `omniauth_callbacks_controller` is to process _after_ the user has signed in.

```
curl https://datacommons.princeton.edu/describe/works/285
<html><body>You are being <a href="https://datacommons.princeton.edu/sign_in">redirected</a>.</body></html>~/src/pdc_describe
```

Running this is my localhost I get the impression that this redirect URL is the issue. Yet, I cannot explain why it works in staging but not in production.

**Comment by hectorcorrea** [comment]
It looks like this PR https://github.com/pulibrary/pdc_describe/pull/1733 might have fixed the issue (even though it seems to have now broken other URLs, see https://github.com/pulibrary/pdc_describe/issues/1783)
