### ISSUE TITLE
Curator dashboard

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#176]
## Resource

See [wireframes](https://docs.google.com/presentation/d/1m5sagNRekwQJ62PzGt_rbZq2iWiUv-h9Np2HpFwWR4I/edit#slide=id.g1365656f5db_0_502) 

## Description

These slides were created from discussions between Hector and Hannah. Per Hannah: "These wireframes could be further refined (please see the questions on slide 10), but we discussed some details that may be actionable now."

#### Some features of interest now:

List of "Unfinished Submissions" has the following categories:
- Title: the title of the submission
- Name: the surname (family or last name) of the depositor
- Curator: curator's initials; may also use DCN for Data Curation Network; more than one may be applied
- Status: In review; New; Published (We may consider other categories)
- Last Edited (or similar category): shows the date of the last user (depositor or curator) that made changes to the record.

The following have sorting features:
- Curator: Only shows on the admin/curator dash. Admin users (e.g. curators) can sort by the curator, similar to how we can sort by assignees on Github.
- Status: sort by a specified status type
- Date: sort by date (suggested: ascending, descending)

Search bar feature
- Admin users can use the search bar to quickly find any records using PID, Title, Name, ARK (possibly others?)

#### Hannah will write a separate ticket:

Color change button for messages
- A "message" button will change from blue to orange when a  user has new messages.

#### To further discuss:
- The wireframe (as-is) looks button-heavy. What can we do to simplify this design? 
- Could we have the three-lined hover menu described in the original wireframes?

## This image shows the wireframe ideas mentioned on this ticket

![Screen Shot 2022-06-24 at 4 51 10 PM](https://user-images.githubusercontent.com/50670293/175683039-a758c1bd-0050-4047-807a-7fc127779da8.jpeg)

**Comment by kelynch** [comment]
Hector will review and create or reference new tickets as needed.

**Comment by hectorcorrea** [comment]
Added related tickets to implement the rest of the functionality.
