### ISSUE TITLE
Handle AWS errors when uploading files

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1767]
Handle how to report to the user when a file is uploaded to us but the transfer to AWS fails. This gets tricky because the user can upload many files at once and we should report the file(s) that actually failed.

See TODO in https://github.com/pulibrary/pdc_describe/pull/1762 

https://github.com/pulibrary/pdc_describe/pull/1762/files#diff-951c82a67003ff7679fa28cb396d9319bfe99be9a935f6d45481f2386158fa06R209-R217

**Comment by kelynch** [comment]
The TODO is gone from the code in the linked PR.  Has this work been completed elsewhere maybe?

**Comment by hectorcorrea** [comment]
I added the link to the TODO in the code since it was easy to miss, I missed it too and I added it :)

**Comment by hectorcorrea** [comment]
For what is worth, I opened this issue in April/2024 and so far we have not gotten any instance of this. I vote for closing it.
