### ISSUE TITLE
Refactor JavaScript validation for agreement in Wizard

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1770]
As suggested by Carolyn on https://github.com/pulibrary/pdc_describe/pull/1761

We should also add a System spec for this functionality.

Completion criteria:

- [ ] write a system spec to make sure the confirmation button gets disabled and enabled correctly as the user checks and unchecks the agree to terms of service in the pre step for the wizard
- [ ] Move the javascript into the app/javascript instead of having it inline in the page.  This allows for linting and better visibility

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1770?planning-poker) with Zenhub @JaymeeH @jrgriffiniii @kelynch @leefaisonr
