### ISSUE TITLE
Validation for Awaiting Approval (end of wizard) Need to check for Readme and Other files explicitly

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1772]
The user should not be able to mark a submission as complete unless a README file exists AND some other file.

Completion Criteria:
- [x] When a user Click Grant License and Complete the controller should validate the uploaded files
  - [x] There Must be one and only one README.
  - [x] There Must be one or more other files if they are uploading locally
- [x] If the right files do not exists the user will see an error on the page and the work will not update state
  - [x] Readme error: "You Must include a README. [Please upload  one][link to readme step]"
  - [x] File error "You Must include at least one file. [Please upload  one][link to upload step]"

**Comment by hectorcorrea** [comment]
@jrgriffiniii some of this was taken care of by https://github.com/pulibrary/pdc_describe/pull/1777 but maybe not all of it (?)
