### ISSUE TITLE
Strange provenance for files added/deleted/replaced

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1785]
Neggin noticed a strange provenance display issue for the files on this record: https://datacommons.princeton.edu/describe/works/295

PDC Describe indicates that an "Unknown user" deleted two files at `17:33`, Neggin said the curators were not updating the data on AWS directly which normally would explain the "unknown user" message. It is curious that we logged that the user `Yuanyu` was making changes at that exact same time: 

![Screenshot 2024-04-24 at 2 23 06 PM](https://github.com/pulibrary/pdc_describe/assets/568286/1212b3c4-1979-468f-bc7a-76791519a438)

This looks like a bug in out logic to determine changes in AWS, but I am not 100% sure where or how.

The log in AWS shows in fact several changes to the README, it looks like the file was replaced (deleted and readded or overwritten?) 

![Screenshot 2024-04-24 at 2 27 36 PM](https://github.com/pulibrary/pdc_describe/assets/568286/6ebda60c-252f-4b31-a8e0-d27a9948497b)

The fact that this happened on the README (which is a specific step on with Wizard with its own set of rules) might be something to keep an eye on if this happens again. We might need to revisit the logic to update this file when users select a new file via Uppy.

**Comment by hectorcorrea** [comment]
Related: There is an entry in Honeybadger for April 24th at 12:47 PM that logged that we blocked the user from making any changes to the dataset. 

```
Can not update work: 295 is not editable in current state by yuanyux
[PROJECT_ROOT]/app/controllers/application_controller.rb:48:in `validate_modification_permissions' 
```

This makes sense. The version deployed on April 24th prevents users from editing a work once it has been submitted and it is waiting for approval (https://github.com/pulibrary/pdc_describe/releases/tag/v1.25.0)

**Comment by hectorcorrea** [comment]
Looking at the AWS S3 log files in the `pdc-describe-logs` bucket I saw the three requests that made the changes. We can clearly see the add (HTTP PUT) and delete (HTTP DELETE) on the 23rd and then added (HTTP PUT) again on the 24th (be aware that the times are in UTC, i.e. 4 hours ahead)

```
[23/Apr/2024:21:33:25 +0000] 
xxx.xxx.xxx.80 REST.PUT.OBJECT 10.34770/xtje-mj26/295/Readme.txt "PUT /10.34770/xtje-mj26/295/Readme.txt HTTP/1.1" 200 - - 2407 119 77 "-" "aws-sdk-ruby3/3.130.2 ruby/3.1.0 x86_64-linux aws-sdk-s3/1.113.2"

[23/Apr/2024:21:33:32 +0000] 
xxx.xxx.xxx.79 REST.DELETE.OBJECT 10.34770/xtje-mj26/295/Readme.txt "DELETE /10.34770/xtje-mj26/295/Readme.txt HTTP/1.1" 204 - - - 23 - "-" "aws-sdk-ruby3/3.130.2 ruby/3.1.0 x86_64-linux aws-sdk-s3/1.113.2" 

[24/Apr/2024:17:16:44 +0000] 
xxx.xxx.xxx.79 REST.PUT.OBJECT 10.34770/xtje-mj26/295/Readme.txt "PUT /10.34770/xtje-mj26/295/Readme.txt HTTP/1.1" 200 - - 2407 63 10 "-" "aws-sdk-ruby3/3.130.2 ruby/3.1.0 x86_64-linux aws-sdk-s3/1.113.2" 
```

Given the user agent and other information logged on the `pdc-describe-logs` I am certain these changes happened through the app (i.e. not via Globus or any other outside process.) 

This looks more and more like a bug in our process.

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1785?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii

**Comment by hectorcorrea** [comment]
I have found a way to replicate this issue. 

The issue happens if the user uploads files via the Wizard and instead of clicking "Next" on the Wizard they go back to their dashboard. 

When they do this, because they did not click "Next" the system does not make the call to update the snapshots using the `current_user_id`, in other words the following code from the [WizardController](https://github.com/pulibrary/pdc_describe/blob/main/app/controllers/works_wizard_controller.rb#L71-L88) will not be executed:

```
# POST /works/1/file_upload
def file_uploaded
    upload_service = WorkUploadsEditService.new(@work, current_user)
    # By the time we hit this endpoint files have been uploaded by Uppy submmitting POST requests
    # to /works/1/upload-files-wizard therefore we only need to delete files here and update the upload snapshot.
    @work = upload_service.snapshot_uppy_and_delete_files(deleted_files_param)

    prepare_decorators_for_work_form(@work)
    if params[:save_only] == "true"
      render :file_upload
    else
      redirect_to(work_review_path)
    end
    [...]
    redirect_to work_file_upload_path(@work)
end
```

but then when the user goes to the [Show page](https://github.com/pulibrary/pdc_describe/blob/main/app/controllers/works_controller.rb#L68-L84) for this record that code will execute a call to update the snapshot but this call will be (by design) without a user id: 

```
def show
    @work = Work.find(params[:id])
    UpdateSnapshotJob.perform_later(work_id: @work.id, last_snapshot_id: work.upload_snapshots.first&.id)
end
```

This call to `UpdateSnapshotJob.perform_later` will pickup the files the user added but will mark them as "unknown user" because this call is meant to pick up files added outside the system...but now it is picking up files added through the system.

**Comment by hectorcorrea** [comment]
One way to prevent this issue will be to issue the call to `UploadSnapshots` as the user _adds each file_ the files via Uppy. But that causes other problems because the process to produce the snapshot takes a while and doing a snapshot for each file has already shown to be problematic (particularly for datasets with a large number of files.)
