### ISSUE TITLE
Confirm with the user that they really want to grant the license

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1790]
### User story
On the Review page as a submitter I want to understand that I will not be able to modify the submission after I submit.

On the “Review” page, when one clicks “Grant License and Complete,” we’d like a dialog box to ask for confirmation, including a note that proceeding will send the submission to the curators, during which time edits are disabled

### Acceptance criteria

- [ ] A Dialog pops up to warn the user they will not be able to edit if they continue

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1790?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii

**Comment by hectorcorrea** [comment]
Closed with PR #1808
