### ISSUE TITLE
A Confirmation Page occurs after the user Grants the License in the wizard

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1791]
### User story

As a submitter I need to know that my submission has been completed

After one confirms on the “Review” page, we’d like them to be taken to a page matching the “Completed” step in the progress bar at the top of the wizard, where there is a message noting the 5-10 business day turnaround for curation
After confirmation, it should also be impossible to go back in the browser and make any changes to the submission

### Acceptance criteria
- [ ] Test this page with axe dev tools
- [ ] Update the progress bar to show that we're at the last step
- [ ] The Review screen in the wizard forward to the new confirmation page
- [ ] The new Confirmation page has a button Return to dashboard
- [ ] The new Confirmation page includes text tell in user the turn around time

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1791?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii
