### ISSUE TITLE
Regenerate migration spreadsheet for PRDS

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1817]
Migration plans for the rest of the content are linked here: https://docs.google.com/document/d/1aYmfwi9CV2ERop0yY0oTdvqJVLZyrbk9Brg86_TiKBU/edit?usp=sharing

The [documentation lives here](https://github.com/pulibrary/pdc_discovery/blob/main/docs/migration_spreadsheet.md)

## Acceptance Criteria
- [x] Re-generate the PRDS migration spreadsheet

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1817?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
