### ISSUE TITLE
ResourceType and resourceTypeGeneral

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#182]
Add support for `ResourceType` and `resourceTypeGeneral` properties (see https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties#10-resourcetype) in the data entry and show pages.  This is part of the Curator Controlled metadata (see wireframe https://docs.google.com/presentation/d/1iddiW0nhZahKxdDRzWAthiF_Y1di2_88b5XUr9AtBDQ/edit#slide=id.gfebb5c6012_0_341)

resourceTypeGeneral should be a dropdown list with the values defined in the [DataCite documentation](see https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties#101-resourcetypegeneral). We should default the value to "Dataset". 

ResourceType is a Text box and ResourceTypeGeneral is a drop down

This is complete when:

- [ ] A curator has the ability to edit the ResourceType and the ResourceTypeGeneral from the dataset Edit page
- [ ] A submitter can see the values assigned to the ResourceType and the ResourceTypeGeneral on the edit page
- [ ] There is a automated test to make sure only the collection admins can edit the ResourceType and ResourceTypeGeneral
- [ ] The show screen displays the ResourceType and ResourcesTypeGeneral

**Comment by hhkitsune** [comment]
@hectorcorrea --- For (10) ResourceType, we may need to discuss with the group on 7/8. We might not want the depositor to guess on what to enter for this field. For (10.1) resourceTypeGeneral, yes it should be a dropdown list. However, we might want to hide some of the choices that aren't deposit options for the research data repository. For example: Book, Book Chapter, Conference Proceeding, Dissertation, Journal, Journal Article, Peer Review, Preprint... possibly others, but let's ask the larger group.

**Comment by hhkitsune** [comment]
Here are some examples of the [XML code from the Datacite 4.4 help](https://support.datacite.org/docs/datacite-metadata-schema-v44-xml-metadata-examples) (note: I put weird spaces between characters, so Github wouldn't render to regular text.):

Example software:
< resourceType resourceTypeGeneral ="Software" >Software < /resourceType >

Example a simple dataset:
< resourceType resourceTypeGeneral = "Dataset" >Dataset < /resourceType >

Example for video as ResourceType:
< resourceType resourceTypeGeneral = "Audiovisual" > narrated video </resourceType> 

Example for a workflow ResourceType:
< resourceType resourceTypeGeneral = "Workflow" > Software < /resourceType >

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/182?planning-poker) with Zenhub @jrgriffiniii @hectorcorrea

**Comment by hectorcorrea** [comment]
This is a duplicate of #448
