### ISSUE TITLE
Support for Princeton guest users

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1823]
### Expected behavior
Previously, DataSpace permitted guest account users to login to DataSpace and submit data. It was my understanding that this would be permitted as well on PDC. However, we had some issues a few month back with Grant Bodner who had an account as bodnerg@fusion.gat.com.

### Actual behavior
However, upon logging in, Grant was met with this error message:
![Screenshot 2024-02-29 at 12 58 14 PM](https://github.com/pulibrary/pdc_describe/assets/20305734/29fd4e4e-79c1-4135-93a7-b4deca0197aa)

Please note the URI in the browser window.

### Steps to replicate
Would require a Princeton guest account and login with credentials.

### Impact of this bug
We imagine that many collaborators who come to the Lab will need to publish their data through PDC. Thus, having an account would be beneficial.

**Comment by carolyncole** [comment]
Looks like we created a user, but didn't deal with the fact that he does not have @princeton.edu in his email.

![Screenshot 2024-05-28 at 3 49 06 PM](https://github.com/pulibrary/pdc_describe/assets/1599081/8ec36778-3bdc-474f-9800-7494a87420e6)

**Comment by carolyncole** [comment]
We currently have the ability to support [guests with a single dots in their emails ](https://github.com/pulibrary/pdc_describe/commit/fdaa5afd4b5e87d93e81f433d878c06c69034f84).   This user has multiple dots.  I suggest that we need to update their uid in our system to be safe (no dots).
