### ISSUE TITLE
Inconsistency in file count

### ISSUE THREAD

**Issue by sec122** [pulibrary/pdc_describe#1826]
### Expected behavior
The number should match in the title of the list as well as in the actual list. For example, It should say "3 files or directories in pre-curation storage" when the count is three and the bottom reads "Showing 1 to 3 of 3 entries" below. 

### Actual behavior
![image](https://github.com/pulibrary/pdc_describe/assets/60932884/b3d56940-c0b1-4535-994f-895f34cce71f)

### Steps to replicate
Noticed when publishing https://pdc-describe-prod.princeton.edu/describe/works/308 Derrida's Margins Web Archive 

### Impact of this bug
Confusion for submitter as to how many files there are. 

### Honeybadger link and code snippet, if applicable

```
```

**Comment by kelynch** [comment]
List directories and files explicitly and separately, example:

### 3 files and 1 directory
* file_a
* file_b
* file_c

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1826?planning-poker) with Zenhub @carolyncole @JaymeeH @jrgriffiniii @leefaisonr

**Comment by kelynch** [comment]
Described in detail in https://github.com/pulibrary/pdc_describe/issues/1784
