### ISSUE TITLE
File name display when delete is clicked more than once

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1833]
When I click on the "Delete File" link the file name is strike through but the system also displays a "#" symbol before the name and it should not:

![Screenshot 2024-06-04 at 11 54 50 AM](https://github.com/pulibrary/pdc_describe/assets/568286/f2072d0c-15ed-4ebb-9bf3-e36e51ab5016)

If I then click "Undo delete" the file will keep the "#" before the name (it should not)

![Screenshot 2024-06-04 at 11 54 57 AM](https://github.com/pulibrary/pdc_describe/assets/568286/dcacf97d-2563-4d12-b461-ecfa4c51830b)

If I then click "Delete file" again, a new "#" symbol will be prefixed to the name:

![Screenshot 2024-06-04 at 11 55 05 AM](https://github.com/pulibrary/pdc_describe/assets/568286/8827c85e-ae58-40c6-96c0-9ac57b686da5)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1833?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
