### ISSUE TITLE
File provenance when deleting files

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1834]
When I delete a file the provenance register two records for the delete. One correctly assigned to the user that delete the file and one indicating "unknown user. The system should not log the "unknown user" provenance in this case since we know the user that deleted the file:

![Screenshot 2024-06-04 at 11 59 23 AM](https://github.com/pulibrary/pdc_describe/assets/568286/f2b356e7-e94b-46ac-9f12-2e37306176b3)

This is related to issue #1833 but not the same.

Look at the snapshots and figure out why the snapshot after the delete (if it is created) is not the same as the snapshot when you come back.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1834?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
