### ISSUE TITLE
Phantom file in AWS bucket

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1836]
We have seen instances where there is a phantom file that shows in PDC Describe:

![Screenshot 2024-06-04 at 8 19 06 AM](https://github.com/pulibrary/pdc_describe/assets/568286/862c1df1-f29a-479e-b025-73026e30fea4)

when this happens it looks like there is indeed a file with zero bytes and no name (or a "/" as the name?) but this file only shows in the AWS S3 webpage if you *search by prefix* but NOT if you navigate to the folder for the work:

![Screenshot 2024-06-04 at 11 07 00 AM](https://github.com/pulibrary/pdc_describe/assets/568286/ed7f0975-49e3-4d0f-a0b8-ad4adc3ab3ce)

![Screenshot 2024-06-04 at 11 06 50 AM](https://github.com/pulibrary/pdc_describe/assets/568286/5649b9d7-8e56-45f6-837d-62efde97ab8a)

The call to AWS that PDC Describe does to fetch files is more similar to the search by prefix and that's why this file shows in PDC Describe:

![Screenshot 2024-06-04 at 12 19 48 PM](https://github.com/pulibrary/pdc_describe/assets/568286/667aa88f-5b33-44a7-b3da-1dfb522c99ac)

Notice how AWS returns the "phantom file" and it shows an `etag` for it and zero bytes. Notice also how the last modified value for the "phantom file" is later than that of the README...which indicates that this file is not the "folder" since it was created after the file.

We think this "phantom file" is something that PDC Describe creates sometimes...or maybe it created it in a previous version. If this issue happens again we should track the problem and fix it. We don't know if this is related to files added via Globus or through the application, but it will be good to check next time the issue happens.

For now we have manually deleted this "phantom file" from the records in staging that had the problem and we'll wait to see if it happens again.

To make things even more puzzling it looks like the AWS S3 webpage also gets confused with these "phantom files". We have seen instances in which the file is displayed as a *folder* instead of a file but notice how it names the "folder" `586/` instead of `/`

![Screenshot 2024-06-04 at 11 43 37 AM](https://github.com/pulibrary/pdc_describe/assets/568286/2225ddd2-57f0-4ada-b639-c1c1041a2b0c)

we think this is a bug in the AWS S3 display since the API fetches that record a zero bytes file with name `/`. Good luck!

Acceptance criteria:

- [ ]  Identify if these are being created by the system. We should be able to look at the Provenance and see if a file was added by an external user, if not it is definitely us.  If it does show as external it could still be us...
- [ ]  Look for patterns in the places that have these files created
- [ ]  If we are sure, or think it is us try to identify which step in the process is creating the directory.  The readme might be the spot based on time stamps
- [ ]  Stop the code from making the files

**Comment by hectorcorrea** [comment]
This record (in production) also shows the problem: https://datacommons.princeton.edu/describe/works/315. In looking at the AWS history it seems that the phantom `/` file was created almost at the same time as the README. I wonder if the culprit is there.

![Screenshot 2024-06-05 at 2 48 48 PM](https://github.com/pulibrary/pdc_describe/assets/568286/9ad2b5c7-7354-4ced-9882-c8044f8bec52)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1836?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @leefaisonr

**Comment by carolyncole** [comment]
During the migration party we noticed that all of the items migrated from dataspace had that phantom file

**Comment by carolyncole** [comment]
The files seem to be created when you upload a folder in globus.  We are just reflecting the data that exists.  They exists in the dpsace data sometimes and also in data created in globus, but are not created by the PDCDescribe

**Comment by matthewjchandler** [comment]
If I were curating hands-on, I would manually delete any phantom file that arises due to my transfer actions. By analogy, I would suggest that phantom files we know arise due to the infrastructure we have currently should be deleted. I would ask that we attempt to set up an automated process for catching and removing any phantom files that show up, rather than asking the curators to do it manually for every migrated dataset. It also seems like a good idea report the bug to Globus, in the hopes that they can help us limit how many more we have to deal with.

**Comment by carolyncole** [comment]
@matthewjchandler We are a bit hesitant to automatically delete files.  We have a couple of options on how to solve this:
1. Add a button for Curators to remove all the empty files from the record
2. Leave the empty files, but do not migrate them to post-curation
3. Hide the empty files and do not migrate them to post-curation

Option one would actually remove the files with curator intervention.  Option 2 & 3 would leave the files behind in pre-curation.

**Comment by carolyncole** [comment]
Looks like they do get published.
<img width="1759" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUJTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abc692e50988abebb01c08f20bba68d2ab89216a/Screenshot%202024-08-13%20at%208.37.10%E2%80%AFAM.png" alt="Screenshot 2024-08-13 at 8.37.10 AM.png" />

**Comment by hectorcorrea** [comment]
During the Feature Refinement meeting on 8/14/2024 we decided not to do anything on PDC Describe at this moment. See [meeting notes](https://docs.google.com/document/d/14SjoKlTI7AWNVNjgBOa28jDnhClTnaMnEgN5EBocR9o/edit) for details.
