### ISSUE TITLE
Review how the system works with GAP accounts

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1851]
Guest Access Accounts (GAP) are used for non-princeton users and they are associated with a non-princeton.edu email address. PPPL uses these kind of accounts.

We should review how the system handles GAP accounts and make sure we don't make assumption about each user having a princeton.edu email address.

**Comment by kelynch** [comment]
Chun is going to test this and report back.

**Comment by hectorcorrea** [comment]
See also https://github.com/pulibrary/pdc_describe/issues/1901

**Comment by hectorcorrea** [comment]
Closing this since we are now tracking the details on #1901
