### ISSUE TITLE
As a PDC user, I like to be able to switch from awaiting_approval to draft

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1852]
### User story

Users would go through the deposit process and may upload a README as a temporary solution and skip the dataset upload. Unfortunately when they get to the end, it puts it in a "awaiting_approval" state and they are not able to edit the submission further. This means they can't upload the data files or change the metadata. While those with Moderator status can, this imposes delays and third-party human intervention.

There are two needs:
- The ability for a Moderator to switch it back to "draft" state. This is analogous in DataSpace of not approving the submission and sending it back with instructions
- The ability for a data submitter to revert back to "draft" state so they can finish their submission

### Concrete example

An example of something being stuck is this one where it is awaiting approval but the depositor failed to upload files:
https://datacommons.princeton.edu/describe/works/304

**Comment by matthewjchandler** [comment]
I think it makes sense for a submitter to be able to withdraw a submission while it is in the "awaiting_approval" status, but I would recommend that the judgement of whether a submission is complete be left to the curator/moderator.

We had a related issue not too long ago with a submitter making revisions after the curators already had a submission in their queue, and #1773 prevented that from happening anymore, which effectively left the decision of whether something needed to be added or edited post-submission to the curator. With this present issue, it sounds like there is agreement between PRDS and PPPL that when a submission still needs more, it should be sent back to a "draft" state. My point is just that I think it would be best for due process if the assigned curator/moderator makes that determination.

That said, if it keeps happening that submitters click submit without including any data files, then we'll need to enhance the submission form to do a better job of preventing that.

**Comment by astrochun** [comment]
Agreed with @matthewjchandler's evaluation. Happy with the option that we can send it back and for the submitter to request it so we understand the unique circumstances. To be clear, this is different from DOI versioning with datasets that are already published.
