### ISSUE TITLE
List of files overlaps with chat message side

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1868]
### Steps to recreate

When working with a PDC reviewer, we noticed how bad this is when we were looking at up to 100 files.

![Screen Shot 2024-07-29 at 12 22 51 PM](https://github.com/user-attachments/assets/8931ec5a-6dc0-4cf5-8029-fa18706c691a)

### URL
https://datacommons.princeton.edu/describe/works/301

### Issues

Unable to easily see the chat messages due to overlap. We believe the user was on a Chrome browser.

### Acceptance criteria
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

**Comment by hectorcorrea** [comment]
We are able to replicate this issue in Chrome and Firefox if we resize the browser window too narrow. It looks like the file list width is fixed and once we hit certain size the file display collides with the messages.
