### ISSUE TITLE
Some objects are not migrating cleanly

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1874]
We have quite a few migration failures with the error "the specified key does not exist."

I wonder if this is a case of AWS illegal characters in the filename, and we need to tweak [this class](https://github.com/pulibrary/pdc_describe/blob/977ce3e52d23b0b9d47fe3d41d6b5941d58849b5/app/services/file_rename_service.rb)? 
![retries](https://github.com/user-attachments/assets/b22fee56-20cc-4bfb-9c40-30ad1c836080)

## Backtrace

    line 239 of [PROJECT_ROOT]/app/services/s3_query_service.rb: copy_file
    line 11 of [PROJECT_ROOT]/app/jobs/dspace_file_copy_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/109875023)

**Comment by kelynch** [comment]
Here's the object that appears to be creating errors - https://datacommons.princeton.edu/describe/works/348
