### ISSUE TITLE
Improve handling for bitstream files which are downloaded from DSpace for checksum validation

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pdc_describe#1878]
## Backtrace

    line 112 of [PROJECT_ROOT]/app/services/pul_dspace_connector.rb: checksum_file
    line 64 of [PROJECT_ROOT]/app/services/pul_dspace_connector.rb: block in download_bitstreams
    line 62 of [PROJECT_ROOT]/app/services/pul_dspace_connector.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/109877600)

**Comment by kelynch** [comment]
Closing in favor of https://github.com/pulibrary/pdc_describe/issues/1888
