### ISSUE TITLE
Messaging sidebar shows recent message at the top but you have to respond below

### ISSUE THREAD

**Issue by astrochun** [pulibrary/pdc_describe#1881]
### Issues

For very extensive comments history, it became clear that the area to provide additional comments is way at the bottom while the most recent message is near the stop. Some discussions is needed as to what order the messages should appear (ascending vs descening). However, I think it would make sense for the comments box to appear next to the recent messages.

![Screen Shot 2024-08-02 at 7 54 09 AM](https://github.com/user-attachments/assets/bbaf538c-e56a-4883-8d09-4ea8e76413cd)
...
...
![Screen Shot 2024-08-02 at 7 54 16 AM](https://github.com/user-attachments/assets/7354b6ef-1c2a-4020-afd7-7efb378e9ddc)

### URL

https://datacommons.princeton.edu/describe/works/301

### Acceptance criteria
- [ ] Move the box to enter messages to the top of the message section 
- [ ] Keep the messages in the current sort order
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools

### Notes

We may do additional user testing in the future on this item, but that is not part of this ticket.

**Comment by hectorcorrea** [comment]
As a first pass we are going to move the box to enter messages to the top (and keep the messages in the current sort order)

**Comment by astrochun** [comment]
I'm not opposed to that if the intent it ensure that recent messages are more easily seen.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1881?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @kelynch @leefaisonr
