### ISSUE TITLE
Background jobs architecture

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1906]
Investigate how to manage our background jobs so that they are better distributed across our machines. During the migration we noticed that one machine got most of the work and the other was almost idle. Adding a new machine after the fact did not help since the jobs are already queued on one of the two pre-existing machines.

(This was the [action item from the retrospective](https://docs.google.com/document/d/1vxJc86aIJ1WStfOZBc8yNXeFHFzDzD4AdBK7O49Xbmw/edit) on 8/20/2024)

We updated nginx to look at the health page: https://github.com/pulibrary/princeton_ansible/issues/5281. This way when the queues get too high no user will get routed to that host...

We still need to think about rearchitecting the system for longer term stability.  Other systems use a centralized Redis, which puts us back at a single point of failure for Redis.

## Acceptance criteria

- [x] Organize and hold a meeting including Operations to discuss different approaches to come up with options for what we can do.
- [x] Make a spike ticket if applicable based on the outcomes of the discussion.

**Comment by bess** [comment]
Meeting scheduled for September 9. Notes document here: https://docs.google.com/document/d/145G79ZX6Ln500e7Fb61m5i1wxIs-00V2-UHqod-M6gA/edit?usp=sharing
