### ISSUE TITLE
Dataset owner

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#191]
We currently consider the person that added a dataset to PDC Describe as the "owner" of the dataset, i.e. it will show under their "my unfinished datasets" list in the dashboard. 

But this process does not work when a person other than the real owner creates the dataset record in PDC Describe, for example if a student or a curator adds a dataset on behalf of a researcher. 

We need to give curators the ability to assign an owner to a dataset. This will require
* An option to assign an owner to a dataset (available only to curators)
* Store this value separate from the person that created the record
* Use this new value to drive the "my xxx dataset" lists in the dashboard.

**Comment by carolyncole** [comment]
@bess Do you believe this will be required for migration?
