### ISSUE TITLE
Write Code to pull down 6 tar files explode the tar files, checksum each file in the tar and produce a report for the curators

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1920]
There are 6 works describe in https://github.com/pulibrary/pdc_describe/issues/1918 that have tar files with different checksums.

The curators would like a report of the checksums of each file in the tar to prove that they are the same.

Acceptance Criteria:
 - [ ] ~~write code that can take an id, pull down the files locally, unzip and then checksum the files and~~ use pkgdiff to write a report
    - [x] https://datacommons.princeton.edu/describe/works/38
    - [x] https://pdc-describe-prod.princeton.edu/describe/works/425
    - [x] https://pdc-describe-prod.princeton.edu/describe/works/429
    - [x] https://pdc-describe-prod.princeton.edu/describe/works/431
 - [ ] Run [the rake task](https://github.com/pulibrary/pdc_describe/blob/main/lib/tasks/works.rake#L113) to delete the dspace files and move the globus file to the original name after the curators have reviewed the report
 - [ ] This code is throw away and will be utilized 6 times

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1920?planning-poker) with Zenhub @hectorcorrea @JaymeeH @leefaisonr @bess

**Comment by carolyncole** [comment]
I pulled the files and then ran pkgdif on each data_space globus pair.  I noted no changes while running the pkgdiff, but to be certain I also searched the reports, which had 99 verdicts and 99 Unchanged reports:
<img width="1086" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--790c4b888012989ae96a7092e1241c048d8dbd2d/Screenshot%202024-09-16%20at%209.21.43%E2%80%AFAM.png" alt="Screenshot 2024-09-16 at 9.21.43 AM.png" />

**Comment by matthewjchandler** [comment]
@carolyncole following Slack side conversations, I understand that the report confirms that duplicated tar files have matching contents.

I know there was a pointed discussion about 38, which has files with very similar names but dashes in some cases and underscores in others, and I saw that the decision was to just keep the files that were originally in DataSpace.

As for 425, 429, and 431, I understand that they have a lingering issue of README files that do not match, and so @sec122 and @neggink are working on manual review.

If there's anything else anyone needs to complete this ticket, let me know.
