### ISSUE TITLE
Rails 6 Upgrade

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1927]
### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### EOL upgrade
- [ ] EOL Date 10/01/2024

### Why is this maintenance needed?
- Security will no longer be patched

### Acceptance criteria
 - [ ] Upgrade to Rails 7.2
 - [ ] Make sure all tests still pass

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1927?planning-poker) with Zenhub @bess @hectorcorrea @carolyncole @jrgriffiniii @leefaisonr

**Comment by carolyncole** [comment]
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html
