### ISSUE TITLE
Duplicate email error

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pdc_describe#1932]
[pdc_describe/production] ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"DETAIL:  Key (email)=() already exists.

Please find the full backtrace here:
```
[PROJECT_ROOT]/app/models/group.rb:212 :in `default_user` 
    user = User.new(uid:, default_group_id: id)
    user.save!
    user
  end

[PROJECT_ROOT]/app/controllers/groups_controller.rb:51 :in `add_submitter`
def add_submitter
    @group = Group.find(params[:id])
    user = @group.default_user(params[:uid])
    @group.add_submitter(current_user, user)
    check_and_render
```

## Backtrace

    line 212 of [PROJECT_ROOT]/app/models/group.rb: default_user
    line 51 of [PROJECT_ROOT]/app/controllers/groups_controller.rb: add_submitter

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/111407300)

**Comment by kelynch** [comment]
This could have been introduced with GAP account support including making the email field editable.

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1932?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @jrgriffiniii @leefaisonr
