### ISSUE TITLE
Resource Type and Resource Type General fields are behaving strangely

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/pdc_describe#1934]
### Expected behavior
As a curator or moderator completing a new submission, I expect to be able to enter appropriate free-text values for Resource Type and select any option from the Resource Type General drop-down. For example, when I select "Software" from the dropdown for "Resource Type General" and enter a short descriptive term, such as "Source Code," in the "Resource Type" field, like so:

![PDC-Describe_NewSubmission-Describe-CC_ResourceType_2024-09-19](https://github.com/user-attachments/assets/c02d6e76-09d4-44f2-9336-5419b6c89c71)

...I expect to be able to complete the submission without issue.

### Actual behavior
Instead, I get an error message telling me that "Resource Type: General resource type cannot be nil," when I can plainly see that what I entered is still there (not nil):

![PDC-Describe_NewSubmission-Describe_ResourceTypeMessage_2024-09-19](https://github.com/user-attachments/assets/f3473725-429f-4942-ac41-851f62a92fc1)

The message is especially confusing because it seems to conflate two fields: Resource Type and Resource Type General. According to [DataCite v4.4 documentation](https://schema.datacite.org/meta/kernel-4.4/doc/[DataCite-MetadataKernel_v4.4.pdf](https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf)), Resource Type is meant to be a free-format text field (with guidance to choose "a single term of some detail"), while Resource Type General has a controlled vocabulary (which the current drop-down selector reflects).

### Steps to replicate
1. Start a new submission
2. After entering required metadata, go to the "Curator Controlled" tab
3. Enter something other than "Dataset" for Resource Type and select something other than "Dataset" for Resource Type General
4. Complete the submission process
5. Find yourself returned to the Describe step, Curator Controlled tab, with an error message at the top

### Impact of this bug
PRDS cannot complete migration without being able to accurately assign Resource Type and Resource Type General to existing records.

### Acceptance criteria
- [ ] The Resource Type field allows free text (no controlled vocabulary) that gets saved to the model on next or save
- [ ] All options from the drop-down selector for the Resource Type General field are available for submission
- [ ] In the XML version of the record for DataCite, the text entered in the PDC Resource Type field becomes the value for the element resourceType, and the selected value for the PDC field Resource Type General becomes the value for the attribute resourceTypeGeneral
- [ ] An error is thrown if Resource Type and/or Resource Type General do truly end up with nil values
- [ ] The error message is corrected as follows:
  - [ ] If the Resource Type field ends up empty, then the error is "Resource Type cannot be nil."
  - [ ] If the Resource Type General field ends up empty, then the error is "Resource Type General cannot be nil."
- [ ] Data sent to DataCite is still valid XML

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1934?planning-poker) with Zenhub @hectorcorrea @JaymeeH @leefaisonr @jrgriffiniii
