### ISSUE TITLE
Extra DOIs for some migrated items

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/pdc_describe#1939]
### Expected behavior
When migrating records from DataSpace to PDC, if a given record in DataSpace already has a DOI, then one is expected to copy it over to PDC and double-check its accuracy before moving on. That way, PDC Describe should only ever record one accurate DOI, and PDC Discover should only ever display the one DOI that resolves to the record page.

### Actual behavior
A few cases slipped through the cracks, receiving a second (undesired) DOI and causing problems:

- https://datacommons.princeton.edu/describe/works/161
  - WRONG DOI: https://doi.org/10.34770/qcby-s338
  - CORRECT DOI: https://doi.org/10.34770/yw3z-w471
- https://datacommons.princeton.edu/describe/works/359
  - WRONG DOI: https://doi.org/10.34770/9ksn-2e46
  - CORRECT DOI: https://doi.org/10.34770/chag-5f03
- https://pdc-describe-prod.princeton.edu/describe/works/440
  - WRONG DOI: https://doi.org/10.34770/wk18-4h90
  - CORRECT DOI: https://doi.org/10.34770/ghkd-4558

### Impact of this bug
In all of the above cases, the incorrect DOIs are currently recorded in PDC Describe, and they do not resolve when fetched. Each of the correct DOIs, however, does resolve--either to the original DataSpace record, or (in the case of work 161) to PDC Discovery. PRDS cannot complete the migration process without correcting these errors (see the rows marked as "Multiple DOIs" under the "Issue Type" column on the "Needs Attention" sheet of [COPY of RDOS Records in Dataspace](https://docs.google.com/spreadsheets/d/130B7RMhnqSeTIKPFBdDsrSVbC1C_PCdZp0qwTucR0QA/edit?gid=1621544543#gid=1621544543)).

### Acceptance criteria
- [x] Replace the wrong DOI with the correct DOI for each of the following works in PDC Describe:
  - [x] https://datacommons.princeton.edu/describe/works/161
  - [x] https://datacommons.princeton.edu/describe/works/359
  - [x] https://pdc-describe-prod.princeton.edu/describe/works/440
- [x] Manually move the data in the AWS Web Console or aws client
  - [x] https://datacommons.princeton.edu/describe/works/161
  - [x] https://datacommons.princeton.edu/describe/works/359
  - [x] https://pdc-describe-prod.princeton.edu/describe/works/440
- [x] Delete all of the wrong DOIs from DataCite: [use curl](https://support.datacite.org/reference/delete_dois-id) 
  - [x] https://doi.org/10.34770/qcby-s338
  - [x] https://doi.org/10.34770/9ksn-2e46
  - [x] https://doi.org/10.34770/wk18-4h90

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1939?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by hectorcorrea** [comment]
A possible list of steps to take care of this: https://docs.google.com/document/d/1WZ5JDx7VZ04-HaByDi4B_ycpDm3zWoMqhcZFsG3iZ-U/edit?tab=t.0

**Comment by hectorcorrea** [comment]
@matthewjchandler @leefaisonr and I have completed the steps for these 3 datasets. When you are ready please close this ticket or let us know if other steps are needed.

**Comment by matthewjchandler** [comment]
I checked in with @neggink and it looks good, thank you! If you have nothing else @leefaisonr , I'd say we can close this.
