### ISSUE TITLE
Decision Document: One S3 Bucket or Two? 

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#194]
In order to finalize this document (https://docs.google.com/presentation/d/1RxhzZa9qa1IT2phT-nvgAXAAqGipVK0OYn5SWRI9bOo/edit#slide=id.g13a9de7c0de_1_0) we need to decide whether want one S3 bucket or two. 

Produce a decision document with the risks and benefits of each approach. 

Some benefits of one bucket:
* Faster transfer between CURATION and FINAL
* No S3 transfer costs
* Fewer buckets to track

Drawbacks of a single bucket:
* Higher risk that the content of CURATION bucket will be made public

We need to better understand the risk profile of the permissions on pre-curated data.

**ACCEPTANCE CRITERIA**
- [x] Produce a draft of a decision document
- [x] Go through it with Hannah, Francis, and RDSS team
- [ ] Present it to PRDS for final decision
- [x] Make an ADR for pdc_describe with the decision documented

**Comment by hhkitsune** [comment]
@bess I was planning to have this as a topic of discussion (and decision making) for the RDOS Repositories meeting on August 12. Does this work for the expected timeframe to present to PRDS for the final decision? I can adjust the meeting date if needed.
