### ISSUE TITLE
Redirect PRDS DataSpace collections

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#1943]
Redirect collections with the "Ready!" status in the "ARK Migrated?" column [in this spreadsheet](https://docs.google.com/spreadsheets/d/130B7RMhnqSeTIKPFBdDsrSVbC1C_PCdZp0qwTucR0QA/edit?gid=154020724#gid=154020724) to the PDC Discovery URLs in the "PDC Discovery URL" column on the same row.

Arks to be redirected:
* Music and Arts - bitKlavier
* Princeton Neuroscience Institute - Research Data Sets
* Computational Social Science - Research Data Sets
* Chemistry - Research Data Sets
* Molecular Biology - Research DataSets
* Department of Geosciences - Research Data Sets
* Sociology - Research Data Sets
* Astrophysical Sciences - Research Data Sets
* Civil and Environmental Engineering - CEE Research Data Sets
* Chemical and Biological Engineering - Research Data Sets
* Princeton School of Public and International Affairs - C-PREE Research Data Sets
* Mechanical and Aerospace Engineering - MAE Research Data Sets
* Psychology - Research Data Sets
* Princeton University Library - Research Data
* Physics - Physics Research Data Sets
* Digital Humanities - Research Data Sets
* Electrical Engineering - EE Research Data Sets
* Geophysical Fluid Dynamics Laboratory - Research Data Sets
* Lewis-Sigler Institute for Integrative Genomics - Research Data Sets

## Acceptance criteria
- [ ] Each of the above-listed collections' arks are redirected to PDC Discovery correctly; use [this rake task](https://github.com/pulibrary/pdc_describe/blob/main/lib/tasks/dspace.rake#L16) to create the redirects
- [ ] The above-linked spreadsheet is updated to reflect this

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/1943?planning-poker) with Zenhub @bess @carolyncole @jrgriffiniii @leefaisonr @JaymeeH

**Comment by matthewjchandler** [comment]
Please add the following:
- Music and Arts - Research Data Sets
- Economics - Research Data Sets

And please revise confirm the following (naming discrepancy):
- "Electrical Engineering" from the listing in this ticket is the same as "Electrical and Computer Engineering" (current display in DataSpace)

**Comment by kelynch** [comment]
Sorry about that, here's the actual spreadsheet (I've updated the original ticket to reflect this too) - https://docs.google.com/spreadsheets/d/130B7RMhnqSeTIKPFBdDsrSVbC1C_PCdZp0qwTucR0QA/edit?gid=154020724#gid=154020724

**Comment by bess** [comment]
Our ARK redirection script isn't working as expected. I don't know what changed since we did PPPL. I am investigating this.

![Screenshot 2024-10-09 at 8 36 52 AM](https://github.com/user-attachments/assets/6590b355-d677-4f5f-a408-ce7865e17967)

**Comment by bess** [comment]
Question:
The spreadsheet we’re working from doesn’t list a specific ARK that should be redirected (I’m looking them up and adding them as I go), it instead says “Princeton Neuroscience Institute - Research Data Sets”
I would think we’d want to redirect both:
ark:/88435/dsp0147429c369 (the ark for the Princeton Neuroscience Institute collection) AND
ark:/88435/dsp010g354h44r (the ark for the Princeton Neuroscience Institute research data sets subcollection)
Is that right? I asked on slack and here, I'll update this comment with the answer when I get one.

**Comment by bess** [comment]
Done!
