### ISSUE TITLE
When a dataset is approved the DOI is marked as final/discoverable in Datacite

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#196]
We currently have the process to generate a draft DOI. We should also figure out how to mark the draft DOI as final DOI and submit the proper metadata for it to DataCite.

This will be needed once we implement the Approve button for a dataset. Right now the button just flags the dataset as APPROVED but eventually it should update DataCite as well.

If an error occurs during the DataCite publishing we will add a notification tagging the curator telling them that there was an issue publishing to DataCite (perhaps with the details) (as @hectorcorrea suggested in slack)

**Comment by carolyncole** [comment]
Here is the relevant spike test for implementing this ticket: https://github.com/pulibrary/pdc_describe/blob/main/spec/models/doi_spec.rb#L63-L83
