### ISSUE TITLE
Dropbox File Counts for Two Migrating Datasets 

### ISSUE THREAD

**Issue by sec122** [pulibrary/pdc_describe#1971]
### Expected behavior
A count for the files and folders for two of the migrating datasets that were in Dropbox. 

### Actual behavior
Unable to get a count from Dropbox to verify that all of the necessary files and folders have been moved to PDC buckets.

### Impact of this bug
Unable to finish migrating two datasets from DataSpace to PDC. 

### Acceptance criteria
A total file and folder count from Dropbox for 
- [x] PDC 362 (doi ending s59n-wm23)
- [x] PDC 350 (doi ending 45m3-am91)

Here's the file and folder counts in PDC (so if these match what you see in Dropbox, that's what we want  to verify before we approve the dataset) 
- https://datacommons.princeton.edu/describe/works/362 - PDC shows 46852 files and folders
- https://datacommons.princeton.edu/describe/works/350 - PDC shows 23335 files and folders

**Comment by jrgriffiniii** [comment]
The files seem to have transferred, but there are missing Folders:

<img width="788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1R0Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b57e36f321abb6a73ac98ceb8ca825cdf20717de/image.png" alt="image.png" />

I can look to ensure that the structure of the Folders is properly in place.

**Comment by jrgriffiniii** [comment]
This has been completed for https://datacommons.princeton.edu/describe/works/362

**Comment by jrgriffiniii** [comment]
After using https://thelig.ht/code/dbxfs/ to generate a file count, both data sets appear to have been properly migrated.
