### ISSUE TITLE
System provenance messages for large works

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#1978]
We are trying to display all system provenance messages on the page by default and this seems to be causing the page to grow too big and times out. 

For example, work https://datacommons.princeton.edu/describe/works/383 has 10,539 "system" notifications that we are rendering on the page which causes the "Looks like something went wrong" message to be rendered instead of the page. 

I suspect this is because either the page is too large or we take too long generating the page.

```
w = Work.find(383)
w.activities.count {|wa| wa.activity_type == "SYSTEM" }
=> 10539

w.activities.count
=> 10547
```

From that I can tell most of these "system" notifications are about empty files: "Warning: Attempted to publish empty S3 file"

This is very likely related to https://github.com/pulibrary/pdc_describe/issues/1977

We should implement a way to toggle these notifications, for example, perhaps we don't display SYSTEM notifications by default and allow the user to turn them on if they want to. Or some variation of this.

**Comment by jrgriffiniii** [comment]
Perhaps a hard limit on the number of provenance messages (100) will ensure that the page can load, and this can then ensure that we can proceed with troubleshooting the actual underlying cause.

**Comment by hectorcorrea** [comment]
@jrgriffiniii FYI - I have a draft PR on this (see #1982). The issue was more complicated than I had thought.
