### ISSUE TITLE
How can I utilize capistrano to take a machine off the loadbalancer

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#1984]
When we want to be certain a machine does not get served to the public, even when the rails environment is working, can we utilize capistrano machine off line

- [x] Create a custom health endpoint that looks at a database value (possibly flipflop)
- [ ] Create a rake task to change the value on/off (does flipflop already have these?)
- [ ] Create a capistrano task to change the value
- [ ] Verify that the loadbalancer believes the site is down and then up based on the cap task

**Comment by carolyncole** [comment]
https://github.com/voormedia/flipflop/blob/master/lib/tasks/flipflop.rake Flip flop has rake tasks!

**Comment by tpendragon** [comment]
@carolyncole did it! We've distributed it everywhere, closing this.
