### ISSUE TITLE
A user can log in via Princeton SSO

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#20]
ACCEPTANCE CRITERIA

- [ ] Any user with a Princeton NetID can authenticate via CAS
- [ ] The system will create a User account populated with their Princeton Shibboleth attributes

Background reading:
* https://github.com/pulibrary/pul-the-hard-way/blob/main/services/shibboleth.md
* https://curationexperts.github.io/recipes/authentication/shibboleth_and_hyrax.html

We believe that CAS will only provide us with netid and email, and that if we want to know about a user's affiliation (e.g., are they a member of PPPL?) we'll need shibboleth, which we can configure to send us additional attributes. 

UPDATE: Looks like maybe CAS *can* provide us with the fields we need? 
* Go to https://fed.princeton.edu/cas/login
* See the field departmentnumber -- that's the attribute we need to know someone's affiliation
* If the department number is 31025 then the person is affiliated with PPPL

**Comment by hectorcorrea** [comment]
We are going to use Shibboleth instead of CAS for PDC Describe, but for future reference here are a few notes about CAS: https://docs.google.com/document/d/1-anC1V5zOHe4Px7DrV4jTykP5aMnrwlPBmG_2zT1tdU/edit?usp=sharing.

**Comment by kelynch** [comment]
Here is PeopleSoft department affiliation codes from October 2021 -- this can be refreshed periodically by asking PeopleSoft contact for a refreshed report - 

https://docs.google.com/spreadsheets/d/1_Elxs3Ex-2wCbbKUzD4ii3k16zx36sYf/edit#gid=1484576831
