### ISSUE TITLE
Describe Form: Augment Page (DOI Step 0 page)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#204]
## Description

Per feedback from Carolyn and Hector, we may run into a problem with the new submissions process if we don't gather (at least) the title of the work prior to allowing the depositor to have the draft DOI. At the same time, we don't want the warning page to become lengthy, tedious to read, which could also result in the depositor choosing the wrong action for their needs. The following screen shot is an attempt to augment step zero with the developer's recommendation, but keeping things simple and easily understandable to avoid mistakes.

Leave the title field on the subsequent page with the ability to edit the value entered here.

### Screenshot shows the warning page with a placement of the "enter title" feature that may avoid confusion. We may additionally need to add either a hover feature to explain what makes a good title, or link out to this information.

![Screen Shot 2022-07-06 at 9 48 16 AM](https://user-images.githubusercontent.com/50670293/177567718-6b08f6cb-b7f6-4f5f-8ef1-665fa8139e7c.jpeg)

**Comment by carolyncole** [comment]
I believe this is still open in error.  It has been added to the system
