### ISSUE TITLE
Curator dashboard - search feature

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#205]
Curators can use the search bar to quickly find any records using DOI, Title, Depositor/submitter, ARK.  Allow partial terms in the title and the depositor.

![](https://user-images.githubusercontent.com/50670293/175953050-e4903f16-ef8a-4c36-8231-d7fa1c778fe1.jpeg)

(see https://github.com/pulibrary/pdc_describe/issues/176 for background and screenshot)

This is complete when:

- [ ]  Indexes in the database on our search terms
- [ ] There is a search bar in the UI that has a a text field to enter any of doi title depositor and ark
- [ ] A search will show the dashboard filtered to just the works that match the search
- [ ] There is a way to clear the search and go back to all results
- [ ] There are system tests that prove this works from the user's perspective

See https://www.scimedsolutions.com/blog/arel-part-i-case-insensitive-searches-with-partial-matching for example

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/205?planning-poker) with Zenhub @bess @jrgriffiniii @kelynch

**Comment by kelynch** [comment]
@carolyncole Is this the previously-implemented pattern you referred to in the meeting? https://github.com/pulibrary/lockers_and_study_spaces/commit/c2fde1cc052c3794e666ed4b76a84df38d9f30c7

**Comment by carolyncole** [comment]
@kelynch Here is the pattern: https://github.com/pulibrary/lockers_and_study_spaces/blob/6515df8a2410e370c66ba38af4a1bd49a2452930/app/models/application_record.rb#L9

**Comment by carolyncole** [comment]
See Closed #205 for wireframe
