### ISSUE TITLE
Back the system with a state machine

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#207]
I believe that adding a state machine gem like [AASM](https://github.com/aasm/aasm) will give us greater flexibility as the system gets more complex.

We utilized this gem in Approvals  to allow for complex state transitions with notifications (https://github.com/pulibrary/approvals/blob/16fec05410196bc3be689784c4a9e919a110102a/app/models/concerns/aasm_config.rb)

Of note to one of the current tickets is the logging at every state change: https://github.com/pulibrary/approvals/blob/16fec05410196bc3be689784c4a9e919a110102a/app/models/concerns/aasm_config.rb#L12

[Here](https://github.com/pulibrary/pdc_describe/blob/main/docs/work_states.md) is a document that describes all the desired work states.

**Comment by hectorcorrea** [comment]
As you work on this ticket, keep this other ticket in mind: https://github.com/pulibrary/pdc_describe/issues/237

**Comment by carolyncole** [comment]
Need to handle state transition errors:
![Screen Shot 2022-08-16 at 7 39 51 AM](https://user-images.githubusercontent.com/1599081/184870932-0eeb9b3e-aea5-4845-99a3-a64501b59308.png)
