### ISSUE TITLE
Describe Form: Bug in Orcid Feature (Staging)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#209]
## Description

**Bug in the Orcid ID feature of the Describe Form**

**Part of the form:** New Submission, required metadata

Entering an Orcid ID to the "Creator(s)" field of the form should auto-populate the fields with the given name and surname. In the image below, two Orcid IDs did not auto-populate at all and one incorrectly rendered the given name field with both given and surname.

## Image shows incorrect return of data after entering three correct Orcid IDs

![image1](https://user-images.githubusercontent.com/50670293/177643149-f80cb9ed-def0-45d8-8de7-88fc3ef28ebe.png)

 ## Acceptance Criteria
- [ ] Entering an Orcid ID to the "Creator(s)" field of the form should pull the name and given name to auto-populate the correct fields

**Comment by jrgriffiniii** [comment]
I am progressing with this, however, I am now finding the following error:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/c9415048-5873-4af7-94e8-c33ec2c969a9)
