### ISSUE TITLE
SPIKE: How do we validate the DataCite record we produce? 

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#210]
At least one goal of our workflow is to produce a valid DataCite record. Do we have a clear definition of what that means? 

Trying to reach an understanding of that I find this (old) thread from the Research Data Alliance - Research Data Repository Interoperability WG where the topic is debated: https://www.rd-alliance.org/group/research-data-repository-interoperability-wg/post/validation-datacite

I *think* our goal should be to produce a datacite XML serialization that can validate against the datacite schema document as published by datacite. 

Suggested goals:
* An automated system for validating our document
* We set that up earlier rather than later so that as we add more fields we know if we diverge from valid practice. This will make it much easier to fix the problem right away, instead of waiting until all of the datacite fields are implemented and THEN finding out that the output doesn't validate and having to go back and fix it in lots of places.
* We should record which version of the datacite schema we're matching because it will doubtless change over time.

## July 12 Update:
After further investigation by @hhkitsune and conversations between @hhkitsune and @bess , we recommend: 
* For the time being we validate using the 4.3 schema already in use by Stanford. This lets us align with them on code maintenance, and would allow us to move quickly because we can validate using existing code they've already written. 
* We cannot find any places where the 4.4 schema offers fields that we need right now that aren't also present in 4.3
* @hhkitsune continue to monitor the situation and when we need something that requires 4.4 we can re-assess
* When datacite releases the 4.4 schema in JSON format, it should be relatively easy to swap it into the `datacite-ruby` gem.
* @hhkitsune checked with @windcowles on this and we have approval to proceed on 7/12.

**Comment by carolyncole** [comment]
https://github.com/pulibrary/lib_jobs/blob/8951eb350389c8cbbf17ff67dc749cdf62d4279b/spec/models/alma_people/alma_person_feed_spec.rb#L92-L99

**Comment by hhkitsune** [comment]
I found a "data validator" for Datacite, which we can't directly use because it doesn't support Datacite 4.4. However, it's made from code that Kate confirmed could potentially be used to create our own validator for Datacite 4.4. 

**Please see these resources:**

- [Datacite validator](https://format.gbv.de/validate/datacite/xml) for earlier schema; 4.0, 4.1, 4.2
- [GBV/Validation Server](https://github.com/gbv/validation-server#get-validate) possible to make a custom validator

My Questions:
- Can it be done?
- Would it be too difficult or time-intensive to make a custom validator?

Thanks, hope this helps!

**Comment by carolyncole** [comment]
Should we write an upgrade to the gem we are utilizing to include 4.4 schema? https://github.com/sul-dlss/datacite-ruby#validation

**Comment by hectorcorrea** [comment]
More information on a threat that @hhkitsune found: https://github.com/datacite/schema/issues/99

**Comment by hhkitsune** [comment]
Kristian provided this except in a helpful reply from the thread Hector had mentioned:

Datacite also provides tools that can help you to convert valid Datacite XML to JSON serialization and vice-versa (and other formats). Take a look at our [libraries](https://github.com/datacite/bolognese).

**Comment by hectorcorrea** [comment]
See also https://github.com/pulibrary/pdc_describe/issues/218
