### ISSUE TITLE
Change Curator to Moderator

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#214]
Change the display of Curator to Moderator in the Dashboard and the Collection edit screens

## Dashboard
![Screen Shot 2022-07-08 at 3 11 52 PM](https://user-images.githubusercontent.com/568286/178056253-2397a138-5f17-4371-9013-3acce9a3f1bf.png)

## Collection Edit
![Screen Shot 2022-07-08 at 3 12 41 PM](https://user-images.githubusercontent.com/568286/178056080-7d15ea4b-aca1-4a11-b218-af84614f6383.png)

**Comment by hectorcorrea** [comment]
@hhkitsune do we want to rename the column curator (to moderator) in the dashboard (the text with #2) as well or only the role at the top? I am thinking just the role at the top since we do want to designate a curator for the dataset, right?

**Comment by carolyncole** [comment]
@hhkitsune To clarify a Collection has a moderator and a DataSet has a Curator.  The dataset curator is the person who is curating that particular dataset currently.  The collection moderator(s) is a person who can add users to submit and add additional moderators in addition to assigning themselves as the curator for a data set.

**Comment by hhkitsune** [comment]
@carolyncole I looked at your comment closer after the meeting and what you are saying is correct.

Moderator:
- may be assigned to one or more collections (For example: Hannah is assigned to all collections, but Neggin might only be assigned to the main Research Data collection, and Chun might only be assigned to all PPPL collections.)
- may add users (depositors) to submit data
- may add users (additional moderators) to a collection they are assigned to, but not to other collections
- may assign themselves and other moderators from the same collection as a "curator" of a deposit
- signage next to name (number 1 in screenshot above) indicates "Moderator"

Curator:
- the moderator when assigned to a submission
- ID or name shows in "Curator" column (number 2 in screenshot above)

Please let me know if we need further clarification on these details.

**Comment by hhkitsune** [comment]
@carolyncole @hectorcorrea Please see the above ticket that I had closed. We do want to change the term for the blue label from "Curator" to something more inclusive. This is because PPPL's workflow uses reviewers instead of curators, the latter term would be confusing for them. I don't think we are wanting to change the behaviors and permissions both Carolyn and I have described above, but we do want to revisit the naming of these labels.
