### ISSUE TITLE
Dataset approval

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#236]
When a dataset has been curated a curator can approve a dataset. This could be done with a button on the Show page of the dataset. This button should only be available to curators for the collection that the dataset belongs to.

When a dataset is marked as approved the following activities must be performed on the dataset:
-[] the dataset becomes readonly, neither the files nor the metadata can be changed.
-[] the files are moved from the AWS pre-curation bucket to the post-curation bucket (so that they can become public via Globus and/or other mechanism).
-[] the DOI is marked as final/discoverable and updated in DataCite with the current metadata in PDC Describe (see https://github.com/pulibrary/pdc_describe/issues/196).
-[] the dataset becomes available in PDC Discovery (or at least it marked in a way that PDC Discovery can harvest it)

Questions:
-[] Will curators be able to make changes to the metadata in an approved dataset? 
-[] Should it be possible to add comments to an approved dataset? (comments are for internal use and not published to DataCite)

**Comment by carolyncole** [comment]
Curators will be able to change metadata after approval

**Comment by carolyncole** [comment]
We are closing this ticket in favor of the epic #161.  We have created tickets for each step in the check list and attached them to the epic.
