### ISSUE TITLE
File management in a dataset

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#238]
A user should be able to add and remove files from a dataset while it is being curated. This should be implemented on the Show/Edit page of the dataset.

Once approved, files in a dataset cannot be changed (dataset must be withdrawn first). Notice that we are not implementing versioning of datasets yet, once we do, this workflow might change.

**Comment by hectorcorrea** [comment]
TODO: Address ordering

**Comment by jrgriffiniii** [comment]
Apologies, https://github.com/pulibrary/pdc_describe/compare/issues-238-jrgriffiniii-reordering-persist?expand=1 required an unexpected amount of time in order to determine how to implement the proper `system` test suite for dragging and dropping the `<table>` row elements.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pdc_describe/pull/375 advances the JavaScript user interface updates required to support reordering within the browser. Still required is the `WorksController` functionality to persist the ordering of the uploads.
