### ISSUE TITLE
Upload to AWS in staging/production

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#239]
Configure PDC Describe to upload files to AWS S3 on staging and production.

We currently have a `pdc-globus-staging-precuration` bucket in S3 that we could probably use for staging. 

There is also a `pdc-describe-test` bucket that already has a `10-34770` folder on it. Perhaps we can use this one for "production" before we go to production for real (?)

**Comment by hectorcorrea** [comment]
Is this related to #221 ?

**Comment by kelynch** [comment]
This has been addressed in other tickets.
