### ISSUE TITLE
datacite xml format does not utilize the same fields as datacite json format

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#245]
https://api.datacite.org/dois/10.5438/0014 vs http://schema.datacite.org/meta/kernel-4.4/example/datacite-example-full-v4.xml 

Since we are targeting version 4.4 and that is only available in XML and we are utilizing the xml for validation, we need to utilize the XML format directly.  This will mean: 
 
- [ ]  removing the ruby gem that utilizes the json format
- [ ]  replacing the gem with our own capabilities that utilize XML instead or utilize another gem 
        * https://github.com/CDLUC3/datacite-mapping (only version 4.3) might be helpful (or might not)
- [ ] Send xml to datacite via ruby (should just be a http get or post/put once we have the xml)

**Comment by hectorcorrea** [comment]
As we work on the XML serialization we might consider pulling the [PULDatacite::Resource.to_xml](https://github.com/pulibrary/pdc_describe/blob/main/app/models/pul_datacite.rb#L31-L89) method to its own class.

**Comment by carolyncole** [comment]
Looks like we may still be able to utilize the original ruby gem.  The api requires json with xml metadata as base 64 encoded data in the json: https://support.datacite.org/docs/api-create-dois#provide-metadata-in-formats-other-than-json

**Comment by carolyncole** [comment]
The ruby gem has been updated to accept xml.  The gem will no longer do validation for us with XML as it does for JSON.  They might be open to pushing our validation up into the gem.
