### ISSUE TITLE
Utilize PDC describe to import a record

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#254]
[Sowing the Seeds for More Usable Web Archives: A Usability Study of Archive-It](https://dataspace.princeton.edu/handle/88435/dsp01d791sj97j)

The following should work:
Ark identifier: ark:/88435/dsp01d791sj97j
Multiple authors, order must be preserved
Multiple files
Publicly accessible

## Acceptance Criteria

- [x] Any missing fields are ticketed and added to the epic #229 
- [x] Verify that Author order is preserved, ticket if not working
- [x] Verify that Multiple files work, ticket if not working
- [x] Verify that the Datacite record has the information we desire.  If not ticket the missing items
- [x] Add Documentation for the process

**Comment by carolyncole** [comment]
Need to familiarize with the importer and the schema.  Involves back and forth and learning with Tyler

**Comment by Twade968** [comment]
We did this in an Rspec test. We will make a separate ticket to migrate in production after the form is complete.
