### ISSUE TITLE
Preserve author order in datacite mapping

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#259]
There is no explicit ordering in the DataCite Schema, but we believe there is implicit ordering. 

**ACCEPTANCE CRITERIA**
- [x] Datacite records we create should preserver author order
- [x] Write a test to make sure that when we have multiple authors the XML is produced in the correct order

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/259?planning-poker) with ZenHub @bess @hectorcorrea @jrgriffiniii
