### ISSUE TITLE
Withdrawing an object from publication

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#27]
- [x] As an admin for a collection, if I go to the page of a published object I see a button that allows me to withdraw it from publication
- [x] I do not see that button if I am not an admin for the collection
- [x] if I am a superadmin I always see that withdraw button, for all collections

**Comment by hectorcorrea** [comment]
I am 99% sure this was taken care of with https://github.com/pulibrary/pdc_describe/pull/66, right?
