### ISSUE TITLE
s3_query_service.rb and work.deposit_uploads

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#288]
Currently the code in `s3_query_service.rb` fetches data from S3 for a given work (by its DOI), however, for works where the user uploaded the files from PDC Describe (instead of directly to S3) the metadata for theses files lives in Rails ActiveStorage tables (accessible via `work.deposit_uploads`) and the information could be duplicated.

This double source of data should be handled in the code "somehow" as it currently causes issues since sometimes we get data via `work.deposit_uploads` (with uses ActiveStorage tables) but other times we get the data via `service = S3QueryService.new(@work.doi)` (which goes straight to S3)

**Comment by jrgriffiniii** [comment]
Following the commits merged for this issue within #301 and #339, the following should still be addressed:

- [ ] Improving the design and layout of the `Curated Files` on the Work View

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pdc_describe/pull/402 should fully resolve this, and hence I am going to please proceed with closing this in favor of keeping https://app.zenhub.com/workspace/o/pulibrary/pdc_describe/issues/379 open.
