### ISSUE TITLE
remove ETDs, Library Resources from the codebase

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#309]
These items were defined as out of scope for PDC describe.
Library Resources will be in Figgy
ETDs will not be in PDC Describe (unsure where they will live)

- [x] Search for Library Resources and ETD to find the locations
- [x] Remove them from the staging and production servers
- [x] Remove any associated tests

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/309?planning-poker) with ZenHub @bess @hectorcorrea @jrgriffiniii

**Comment by carolyncole** [comment]
Some of this was completed by #352

**Comment by carolyncole** [comment]
Staging & Production already only had the two expected collections

**Comment by bess** [comment]
Closing!
