### ISSUE TITLE
Email Notifications can be configured in addition to in Application Notifications

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#360]
This Gem is a possible solution: [mailboxer](https://rubygems.org/gems/mailboxer/versions/0.15.1 ) allows configuration for both in app notifications and also email notifications.
This is utilized in [hyrax](https://github.com/samvera/hyrax/blob/main/hyrax.gemspec#L65)
Possible alternatives to mailboxer: https://www.ruby-toolbox.com/categories/e_mail.html

The system user should be able to decide if they want email or just in app notifications.

This is complete when

- [x] The moderator has the ability to configure notifications
- [x] The current set of notifications also trigger emails if desired ( This includes when a person is tagged )
- [x] There is a record of each notification that has been sent
- [x] There are automated test that show a user can configure emails and does receive them if configure

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/360?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii

**Comment by jrgriffiniii** [comment]
> The moderator has the ability to configure notifications

I apologize, should this ensure that notifications can be disabled at the level of each Collection, or just globally for all Works?

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pdc_describe/compare/i360-jrgriffiniii-coll-moderate advances the updates to the `Collection` and `User` models. I am now only addressing updates to the UI.
