### ISSUE TITLE
When a work is edited, its metadata is not immediately updated

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#365]
* When a work is updated via the edit form, its metadata appears to be updated in the web interface, but the changes are not available in-memory in the object. 
* If a NEW object is loaded into memory (e.g., `work = Work.last` instead of `work.reload`) then the changes are present)
* This is not a show-stopper bug but it could lead to unexpected behavior down the road

```ruby
      it "a collection manager editing a work" do
        login_as princeton_curator
        visit edit_work_path(work)
        fill_in "title_main", with: "New Title"
        click_on "Save Work"
        expect(page).to have_content("New Title")
        # This should work but it does not:
        # expect(work.reload.title).to eq "New Title"
      end
```

**Comment by hectorcorrea** [comment]
Here is another example where this bug showed up (and the workaround) 

https://github.com/pulibrary/pdc_describe/blob/main/spec/system/work_spec.rb#L57
