### ISSUE TITLE
Required field validation in Works is broken

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#368]
The validation for required fields in Works is not being processed at the right moment. If I create a new submission and do not enter a description, the validation does not happen and then we display a rather cryptic error message to the user as shown in the screenshot below.

Notice that the error indicates that it couldn't transition to a new state, but from now on the user can edit the record and not enter the missing required fields and never see the error again.

![Screen Shot 2022-09-01 at 2 21 55 PM](https://user-images.githubusercontent.com/568286/187985754-7d517d70-12b6-4da8-abfb-bbf62f116e28.png)

**Comment by carolyncole** [comment]
I would work on this but I can not.  Can someone be more specific about this?  If we want to user to be able to save before they add the description in the first screen of the wizard, then we can not just make the description a required field at all times for a work to be saved.  Please clarify the requirements.

**Comment by hectorcorrea** [comment]
I will be out next week on PO training so here are my thoughts on this:

In general I think we should let Work records be saved without the required fields **while the Work is on the draft state**. We will enforce required-fields validation as soon as the user completes the Wizard (i.e. we don't let the work move from draft to waiting for approval until all required fields have been entered). From that point forward we always enforce the required field validation.

This will allow a user to come and go from the Wizard at their leisure (e.g. they might not know what kind of license they want to use, but they will still be able to upload files). They might leave the Wizard with some incomplete fields and come back later once they know what license or description they want to use.

Currently we do not allow the user to move from the very first step of the Wizard until they have provided a title and a creator. But the user is free to move through the rest of the Wizard even if the other fields have not been provided. I think this is OK. 

One thing that we should change is that we could send the user to the Wizard anytime they edit a work that is still on draft state. Right now, we only send them to the Wizard the first time, but never again. I think it will be more intuitive to the user to always see the same interface (the Wizard in step 1, not step 0) while they are in draft. Once the Work is in any another state (i.e. waiting for approval) then we could use the normal edit form since I don't think curators probably won't care about or need the Wizard.

**Comment by hectorcorrea** [comment]
Closed with PR https://github.com/pulibrary/pdc_describe/pull/413
