### ISSUE TITLE
Our footer is no longer in the footer

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#370]
In v0.19.0, our footer has been moved into a sub-element of the page (see attached screenshot).

![Screen Shot 2022-09-01 at 3.30.32 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/cfd6ef7c-3981-4d1c-8d10-121ba659bd1b)

**Comment by carolyncole** [comment]
I can not replicate this bug with version 20.  Please reopen if we see this again.
