### ISSUE TITLE
When I add files in S3 they never show up

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#386]
I believe the query to S3 was moved to the after save hook.  This means if we do not edit and change the work the new files will never show.

Although if I delete all the files and then add more that hook does not seem to file when I change the title either.
I'm not sure if this is related to delete or when the hook to S3 is firing.  It looks to me like the hook will only fire when the work changes state: https://github.com/pulibrary/pdc_describe/blob/main/app/models/work.rb#L119-L122 

Rehydrating the test here might be enough for the automated test of adding files before the show page is loaded: https://github.com/pulibrary/pdc_describe/commit/714311048579738f95358c5e3595fd32c6ced15a#diff-7a4e13232c344a69ce8a18cfc9db4629c0c792e3e2f82513184b0695a1e437ceR423-R442

This is complete when

- [x] When I show a work I should see all the files in S3 and only the files that are in S3 (aka if one is removed we should also remove it)
- [x] When I edit a work the above conditions should also be true (Synchronized here too).
- [x] There is an automated test that creates a work with s3 files, add files to s3 and the files should show on the show work screen
- [x] There is an automated test that creates a work with s3 files, removes files from s3 and the files should not show on the show work screen
- [x] There is an automated test that creates a work with s3 files, add files to s3 and the files should show on the edit work screen
- [x] There is an automated test that creates a work with s3 files, removes files from s3 and the files should not show on the edit work screen

**Comment by jrgriffiniii** [comment]
I apologize, https://github.com/pulibrary/pdc_describe/blob/main/app/models/work.rb#L118 is likely where this bug originates. If there are no changes to the `state` of the `Work`, S3 resources are *not* synchronized to the ActiveStorage attachments on the `Work`. However, if the `Work` has not yet been persisted, then the S3 resources are also not synchronized.

This behavior is undesirable, and I suspect that this was related to a bug found when attempting to synchronize S3 resources for the `Work` before it had been persisted.

**Comment by carolyncole** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/386?planning-poker) with Zenhub @bess

**Comment by jrgriffiniii** [comment]
> When I show a work I should see all the files in S3 and only the files that are in S3 (aka if one is removed we should also remove it)

If this is the case for files in S3 for Works which are in the `post-curation` state, and we are not using ActiveStorage with S3 for `post-curation` Work files, then these will be deleted by the `S3` Ruby client, yes?
