### ISSUE TITLE
When a work has an existing DOI, redirect it

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#388]
The works we're migrating from PPPL will have existing DOIs that are not currently part of the DataSpace record. When a work with an existing DOI is approved, we need to redirect that DOI to the PDC Discovery URL for the work. 

ACCEPTANCE CRITERIA
- [x] I can input a DOI on the initial screen instead of having the system register one for me
- [x] Validate the DOI when it has been entered
- [ ] That DOI will, at the "Publish" step in the workflow, be re-directed to the PDC Discovery URL for this work
- [ ] Do something with DOIs we did not create ?? Still figuring out the something ??
- [x] There is an automated test for allowing the user to enter a DOI on the first step of the wizard for an existing DOI, which proves that no DOI is minted in this case.
- [ ] There is an automated test for allowing a already published DOI to be updated with a new URL

**Comment by astrochun** [comment]
@bess and @kelynch , I have the following JSON between DOE DOIs and the ARKs. This was outputted by `dspace-osti`. Hopefully this helps.
 
[redirects.txt](https://github.com/pulibrary/pdc_describe/files/9506342/redirects.txt)

**Comment by carolyncole** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/388?planning-poker) with Zenhub @bess

**Comment by carolyncole** [comment]
I did some testing of updating with items in our DOI prefix and items not in our DOI prefix (most if not all of the PPPL DOIs).  We do not have permission to update the DOIs with a new URL in a prefix that we do not own.

I saw responses like 
```
You are not authorized to access this resource
```

**Comment by astrochun** [comment]
> I did some testing of updating with items in our DOI prefix and items not in our DOI prefix (most if not all of the PPPL DOIs). We do not have permission to update the DOIs with a new URL in a prefix that we do not own.
> 
> I saw responses like
> 
> ```
> You are not authorized to access this resource
> ```

I'm not surprised. It may be best to use the DOI prefix (`10.?????/`) in your logical statement before doing so.

**Comment by carolyncole** [comment]
I noticed that OSTI is also utilizing DataCite.  I went ahead and contacted DataCite to see if they had recommendations for how to request a URL changed on another prefix.

**Comment by kelynch** [comment]
We may be able to just use the EZID API to update the ark URL redirects, which are what powers the OSTI DOI redirects. 
 I thought of this and discussed the possibility with @carolyncole, @bess, and @Twade968 and documented in this PR - https://github.com/pulibrary/pdc_describe/pull/412

**Comment by astrochun** [comment]
Correct, updating the EZID may be the best approach. Keep in mind that the metadata stored on OSTI.gov is to the ARK and not final landing page (I think).

**Comment by carolyncole** [comment]
I just tested that sending the publish event on an already published DOI will change the url if an updated url is sent.  I believe that updating the URL for the DOI will just work, once we are sending the appropriate URL. See https://github.com/pulibrary/pdc_discovery/issues/328

**Comment by astrochun** [comment]
Following up: there are 29 new records with DOIs from DOE. I'm including just these below

```json
{
    "https://doi.org/10.11578/1814960": "88435/dsp01dz010t189",
    "https://doi.org/10.11578/1888268": "88435/dsp01rf55zb85t",
    "https://doi.org/10.11578/1888269": "88435/dsp01sx61dq46q",
    "https://doi.org/10.11578/1888270": "88435/dsp01qb98mj62b",
    "https://doi.org/10.11578/1888271": "88435/dsp01q811kn76d",
    "https://doi.org/10.11578/1888272": "88435/dsp019w032619d",
    "https://doi.org/10.11578/1888273": "88435/dsp01zp38wg800",
    "https://doi.org/10.11578/1888274": "88435/dsp01kk91fp703",
    "https://doi.org/10.11578/1888275": "88435/dsp011n79h751f",
    "https://doi.org/10.11578/1888276": "88435/dsp011g05ff77b",
    "https://doi.org/10.11578/1888278": "88435/dsp018623j1954",
    "https://doi.org/10.11578/1888279": "88435/dsp011g05ff76p",
    "https://doi.org/10.11578/1888280": "88435/dsp01pz50h025c",
    "https://doi.org/10.11578/1888281": "88435/dsp01xp68kk38z",
    "https://doi.org/10.11578/1888253": "88435/dsp01hh63t006w",
    "https://doi.org/10.11578/1888254": "88435/dsp01ng451m72r",
    "https://doi.org/10.11578/1888255": "88435/dsp013197xq19q",
    "https://doi.org/10.11578/1888256": "88435/dsp013r074z09k",
    "https://doi.org/10.11578/1888257": "88435/dsp01cr56n4150",
    "https://doi.org/10.11578/1888258": "88435/dsp01x059cb547",
    "https://doi.org/10.11578/1888259": "88435/dsp015d86p342b",
    "https://doi.org/10.11578/1888260": "88435/dsp01qz20sw65g",
    "https://doi.org/10.11578/1888261": "88435/dsp01rb68xg060",
    "https://doi.org/10.11578/1888262": "88435/dsp013j3335393",
    "https://doi.org/10.11578/1888263": "88435/dsp01pk02cd897",
    "https://doi.org/10.11578/1888264": "88435/dsp0170795b825",
    "https://doi.org/10.11578/1888265": "88435/dsp01xk81jp54s",
    "https://doi.org/10.11578/1888266": "88435/dsp015q47rr88m",
    "https://doi.org/10.11578/1888267": "88435/dsp019c67wq96p",
    "https://doi.org/10.11578/1888277": "88435/dsp013n2042309"
}
```
