### ISSUE TITLE
Ensure non-Princeton users have access

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#395]
There are a number of non-Princeton collaborator users in DataSpace who will need access to PDC Describe as submitters.  Most, if not all, of these are PPPL research affiliates.  If they do not have them, [Princeton University sponsored guest accounts](https://guestaccount.princeton.edu/) will need to be created for them, and their non-Princeton accounts will then need to be reconciled.

This will need to be done as part of the PDC Describe launch.

We'll need to get a list of all non-Princeton users from DataSpace as part of the migration so we can do follow up with the right sponsors to get them accounts.  This ticket encompasses the work of listing the users and asking for sponsorship.\\

## Acceptance criteria

- [ ] Create PPPL-specific documentation for setting up guest accounts using GAP from OIT ([example for Figgy](https://docs.google.com/document/d/1MdoTZmTnNQNFfwy6sqP75byYFG-PPmkIHM6N080iSKQ/edit))
- [ ] Train sponsors at PPPL to create guest accounts.
- [ ] Generate a list of users in DataSpace whose email addresses do not end in `@princeton.edu`
- [ ] Work with Kate to follow up with potential sponsors so they can determine who needs to have guest accounts created

**Comment by carolyncole** [comment]
@kelynch are we expecting documentation to be written, or should the accounts be created when this ticket is closed?
