### ISSUE TITLE
Install the new Globus trust root by December 12

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#406]
We received this email on September 12: 

Subject: Action Required - Install the new Globus trust root by December 12, 2022

Globus is updating the Certificate Authority (CA) used for its transfer service, and moving to a different system for managing the CA. All Globus Connect installations (Globus Connect Server and Globus Connect Personal) must be updated to install the new trust root by December 12, 2022. After this date, the Globus service will cease to function with Globus Connect installations that have not updated the trust root.

Once the update is complete, you must perform a directory listing or submit a transfer request in order for the new trust root to be recognized. In-flight transfers will not resume until the new trust root is recognized.

More information and instructions for updating your deployment are provided at: [Globus Transfer Service Certificate Authority Update.](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fglobus.us7.list-manage.com%2Ftrack%2Fclick%3Fu%3Dfc5710a2f5a23cca23d928994%26id%3Db44b51402f%26e%3D13e5e5d315&data=05%7C01%7Cbess.sadler%40princeton.edu%7C8ae463fedc6b4e40e3a208da94f5928a%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C637986080457369001%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IRznSPICR04LlxnXyJVvWcG9h6qipq4n5QOVwrJM9EY%3D&reserved=0)

Please contact [support@globus.org](mailto:support@globus.org) with any questions, or if you need assistance with the upgrade.

- [ ] Please add to the globus page in the RDSS handbook

**Comment by carolyncole** [comment]
Francis created a ticket for this in princeton-ansible https://github.com/pulibrary/princeton_ansible/issues/3326
