### ISSUE TITLE
Describe Form: metadata entry tabs

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#421]
## Description

Users will have three named tabs to help navigate the metadata entry page. 

*This feature ticket focuses on the tabs themselves. Other tickets will focus on the content within each tab.*

### The tabs will organize metadata properties into three areas:
**1. Required Metadata**
- The depositor and curator can input to all fields except the Datacite DOI
- These are properties that are required by Datacite to mint the DOI and those which we require locally  

**2. Additional Metadata** 
- The depositor and curator can input to all fields

**3. Curator Controlled** 
- These include automated and manual fields 
- Only the curator can change these fields
- The depositor may only see what is inputted and may request the curator to make any changes

## Image shows the three tabs (at left)

![Screen Shot 2022-09-20 at 4 34 51 PM](https://user-images.githubusercontent.com/50670293/191359308-f6f580dd-f6cf-42ec-ab89-b2e1ff6ec907.jpeg)

## Acceptance Criteria

- [ ] There are Three tabs (Required Metadata, Additional Metadata, Curator Controlled)described above are created
- [ ] The Curator Controlled is only editable by Collection Admins and Super Admins
- [ ] There are system test(s) to prove that a submitter can **not** edit the fields on the Curator Controlled tab
- [ ] There are system test(s) to prove that a collection Admin can edit the fields on the Curator Controlled tab
- [ ] Tabs will highlight to show users which tab is currently active (already does)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/421?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii
