### ISSUE TITLE
Invalid ark leads to hidden error message

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#426]
In pdc_describe v0.23.0, the user will experience unexpected behavior if they enter an invalid ark:

![Screen Shot 2022-09-22 at 11 35 31 AM](https://user-images.githubusercontent.com/65608/191795371-5b133994-565c-4193-b7d5-7979a958d78b.png)

![Screen Shot 2022-09-22 at 11 36 59 AM](https://user-images.githubusercontent.com/65608/191795301-9c41a606-ebbc-4239-a272-aeb3883595f4.png)

**Comment by hectorcorrea** [comment]
Good catch. We should move the display of errors to be outside the tabs so that users can see the regardless of which tab they are on.
