### ISSUE TITLE
Describe: bitKlavier (DataSpace to Describe)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#435]
## Description

Our first sample of legacy data that will be translated from the record in DataSpace to the Describe form. This is one record from the bitKlavier collection.

## Sample

The record in DataSpace:
- [bitKlavier Grand Sample Library—Piano Bar Mic Image](https://dataspace.princeton.edu/handle/88435/dsp015999n653h)

## Record Translated to the Wireframes

[Describe_bitKlavier.pdf](https://github.com/pulibrary/pdc_describe/files/9637140/Describe_bitKlavier.pdf)

## Record Translated Details

**DOI:** 10.34770/r75s-9j74

**Title:** bitKlavier Grand Sample Library—Piano Bar Mic Image

**Description:** The bitKlavier Grand consists of sample collections of a new Steinway D grand piano from nine different stereo mic images, with: 16 velocity layers, at every minor 3rd (starting at A0); Hammer release samples; Release resonance samples; Pedal samples. Release packages at 96k/24bit, 88.2k/24bit, 48k/24bit, 44.1k/16bit are available for various applications.

Piano Bar: Earthworks—omni-directionals. This microphone system suspends omnidirectional microphones within the piano. The bar is placed across the harp near the hammers and provides a low string / high string player’s perspective. It also produces a close sound without room or lid interactions. It can be panned across an artificial stereophonic perspective effectively in post-production. File Naming Convention: C4 = middle C . Main note names: [note name][octave]v[velocity].wav  -- e.g., “D#5v13.wav” . Release resonance notes: harm[note name][octave]v[velocity].wav  -- e.g., “harmC2v2.wav” . Hammer samples:  rel[1-88].wav (one per key)  -- e.g., “rel23.wav” . Pedal samples:  pedal[D/U][velocity].wav  -- e.g., “pedalU2.wav” => pedal release (U = up), velocity = 2 (quicker release than velocity = 1) .
This dataset is too large to download directly from this item page. You can access and download the data via Globus (See "https://www.youtube.com/watch?v=uf2c7Y1fiFs" for instructions on how to use Globus).

**Rights:** CC by 4.0

**Creator(s):** 

- **Given name:** Daniel
- **Family name** Trueman

- **Given name:** Matthew
- **Family name** Wang

- **Given name:** Andrés
- **Family name** Villalta

- **Given name:** Katie
- **Family name** Chou

- **Given name:** Christien
- **Family name** Ayres

**Keywords:** bitKlavier, sample library, piano

**Publisher:** Princeton University

**Publication Year:** 2021

**ResourceType:** Dataset

**resourceTypeGeneral:** Dataset

**AlternateIdentifier:** 88435/dsp015999n653h

**alternateIdentifierType:** ARK

**Version:** V1

**Collection Tags:** bitKlavier, Music and Arts

## Acceptance Criteria

- [x] The record will be translated to Describe using the form
- [x] The record will be examined for errors as this work is performed
- [x] Any issues observed or experienced during this process will be reported back to Hannah and RDSS
- [x] There is a repeatable system spec that runs in the browser, that we can re-play to help us improve the experience of entering a record in the form

**Comment by Twade968** [comment]
```
<?xml version="1.0"?>
<resource xsi:schemaLocation='http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://datacite.org/schema/kernel-4'>
  <identifier identifierType='DOI'>10.34770/r75s-9j74</identifier>
  <creators>
    <creator>
      <creatorName>Trueman, Daniel</creatorName>
      <givenName>Daniel</givenName>
      <familyName>Trueman</familyName>
    </creator>
    <creator>
      <creatorName>Wang, Matthew</creatorName>
      <givenName>Matthew</givenName>
      <familyName>Wang</familyName>
    </creator>
    <creator>
      <creatorName>Villalta, Andrés</creatorName>
      <givenName>Andrés</givenName>
      <familyName>Villalta</familyName>
    </creator>
    <creator>
      <creatorName>Chou, Katie</creatorName>
      <givenName>Katie</givenName>
      <familyName>Chou</familyName>
    </creator>
    <creator>
      <creatorName>Ayres, Christien</creatorName>
      <givenName>Christien</givenName>
      <familyName>Ayres</familyName>
    </creator>
  </creators>
  <titles>
    <title>bitKlavier Grand Sample Library—Binaural Mic Image</title>
  </titles>
  <publisher>Princeton University</publisher>
  <resourceType resourceTypeGeneral='Dataset'/>
  <publicationYear>2021</publicationYear>
  <relatedIdentifiers>
    <relatedIdentifier relationType='IsIdenticalTo' relatedIdentifierType='ARK'>88435/dsp015999n653h</relatedIdentifier>
  </relatedIdentifiers>
  <rightsList>
    <rights rightsURI='https://creativecommons.org/licenses/by/4.0/' rightsIdentifier='CC BY'>Creative Commons Attribution 4.0 International</rights>
  </rightsList>
</resource>
```

**Comment by hhkitsune** [comment]
Thanks @Twade968! I am in the process of making tickets for the missing properties/attributes.

**Comment by hhkitsune** [comment]
note: I am writing tickets that show these properties in the wireframes and describe user perspective and expectations.
