### ISSUE TITLE
Add version property to pdc_describe form

### ISSUE THREAD

**Issue by Twade968** [pulibrary/pdc_describe#442]
This will be on the curator only tab.  This can only be whole numbers

Acceptance criteria
- [x] it should not be user editable
- [x] it should be curator editable 
- [x] it should appear in the DataCite record 
- [x] it should be set by default to 1

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/442?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii
