### ISSUE TITLE
schema.org recommendations

### ISSUE THREAD

**Issue by Twade968** [pulibrary/pdc_describe#447]
Acceptance Criteria 
- [x] Bess & Tyler will research schema.org and recommend which fields we should expose in PDC Discovery
- [x] Turn the recommendation into an actionable ticket

UPDATE: Discussed with @hhkitsune on 24 October 2022 and she approves this plan. 
Ticket here: https://github.com/pulibrary/pdc_discovery/issues/353

**Comment by bess** [comment]
We watched a presentation from Mikala Narlock from DCN and participated in a conversation afterwards. The recommendation was to follow the practices that dataverse is using: 

https://dataverse.org/blog/latest-dataverse-update-adds-support-schemaorg
