### ISSUE TITLE
Describe Form: ResourceType property package

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#448]
## Datacite Properties for this ticket

Top property: [10 ResourceType](https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties#10-resourcetype)

Sub property: [10.a resourceTypeGeneral](https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties#10a-resourcetypegeneral)

**note: These are Mandatory properties**

## Description

This ticket provides the user perspective for Describe ticket [182](https://github.com/pulibrary/pdc_describe/issues/182). These properties should be added to the form in a grouping under the "Curator Controlled" section of the form. (See images below.) We have previously decided that default values "dataset" and "dataset" will be automatically recorded to these two fields. However, the curator or admin will be able to change the field's information if needed.

#### ResourceType
- The field is free text
- It will autopopulate with "dataset"
- The text may be changed by a curator or admin

#### resourceTypeGeneral
- The field has a dropdown menu (Please see the link above for details)
- We have limited the visibility of certain selections to inhibit deposits that should go to OAR
- The field autopopulated to "dataset"
- A curator or admin may change the field selection from "dataset" to another selection

## User stories

Datacite requires both the ResourceType and it's sub-property, resourceTypeGeneral, to mint a DOI and register the record with Datacite. Matt the curator expects these fields to be completed, but knows that the variability of the free text in the top property (ResourceType) would be problematic and intimidating for depositors. Fortunately, these fields are located in a "Curator Controlled" portion of the form.

Deposits are datasets most of the time, so Neggin the curator appreciates that the Describe form automatically fills in ResourceType and resourceTypeGeneral with the term "dataset" in each. Neggin will be able to change these automated fields if needed, such as for submissions of code -- but in the meantime, this really helps to scale the submission process. 

### These show the expected order and position for these properties

![Screen Shot 2022-09-20 at 5 20 41 PM](https://user-images.githubusercontent.com/50670293/192633608-a4fc7eb8-9afc-43e5-9dac-083e041c4ac2.jpeg)
![Screen Shot 2022-09-20 at 5 20 48 PM](https://user-images.githubusercontent.com/50670293/192633633-37dcae51-6ee8-4836-be71-772826a8fcb7.jpeg)

#### ResourceType
- [x] The field is free text
- [x] It will autopopulate with "dataset"
- [x] The text may be changed by a curator or admin

#### resourceTypeGeneral
- [x] The field has a dropdown menu (Please see the link above for details)
- [x] It will visibly include selections discussed in our meetings, which discussed what CDL is using
- [x] We have limited the visibility of certain selections to inhibit deposits that should go to OAR
- [x] The field autopopulated to "dataset"
- [x] A curator or admin may change the field selection from "dataset" to another selection

#### Overall
- [x] Both properties will live under the "Curator Controlled" section of the form.
- [x] ResourceType will come before, and will be packaged with, resourceTypeGeneral; as can be seen in the above wireframes.
- [x] Both properties may be changed by curators or administrators, but may not be changed by depositors.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pdc_describe/pull/456 resolved this.

**Comment by jrgriffiniii** [comment]
The updates for the Views seem to have been removed during a problematic rebase.
