### ISSUE TITLE
Describe: Related Identifier Property Set

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#494]
# Description

This ticket shows the [12 RelatedIdentifer](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#12-relatedidentifier) property set that we would like to start with for the MVP. Note: There are other properties in this set, but this is what we have decided to prioritize for the MVP.

## Datacite properties to include in this set:

- Related Identifier (Top, use different label; see slides)
- Related Identifier Type (subproperty; mandatory if RelatedIdentifier is used)
- Relation Type (subproperty; mandatory if RelatedIdentifier is used)

### Image shows wireframe for this property set

![Screen Shot 2022-10-11 at 11 49 24 AM](https://user-images.githubusercontent.com/50670293/195684368-0ce77542-e9aa-44a1-9866-cca8e3ccd844.jpeg)

# Acceptance Criteria

- [x] Set name text displays above the set: Related object (i.e., published dependencies)
- [x] Set follows the order described in [RDOS_publishing ticket 7](https://github.com/pulibrary/RDOS_Publishing/issues/7)
- [x] Set includes three properties: Related Identifier, Related Identifier Type, Relation Type that correspond to Datacite 4.4 (12) RelatedIdentifier, (12.a) relatedIdentifierType, and (12.b) relationType.
- [ ] (12.a) relatedIdentifierType and (12.b) relationType are mandatory when (12) RelatedIdentifier is used. However, it is not mandatory to use (12) RelatedIdentifier.
- [x] The DataCite controlled vocabulary is used to populate values for relatedIdentifierType and relationType
- [x] The DataCite record produced needs to include the human-friendly version of any controlled vocabularies. E.g., use "arXiv", not "ARXIV"

## Reference
- [(12) RelatedIdentifier](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#12-relatedidentifier)
- [(12.a) relatedIdentifierType](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#12a-relatedidentifiertype)
- [(12.b) relationType](https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#12b-relationtype)

**Comment by bess** [comment]
Added last acceptance criteria, plus one more, to a different ticket: https://github.com/pulibrary/pdc_describe/issues/591
