### ISSUE TITLE
Export object metadata for preservation

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#512]
Export Datacite XML and object metadata as JSON to a backup location within the DOI directory for the files in S3, as follows:

## Example: 

```bash 
s3:/bucket/10.80021/ge21-2181/92/
    file1.png 
    dataset.zip 
    princeton_data_commons/
        datacite.xml
        metadata.json 
```

- [x] Keep the location configurable so we can easily change the location in the future
- [x] Export the datacite.xml which is the `work.resource.to_xml` in AWS
- [x] Export the metadata.json which is the `work.resource.to_json` in AWS
- [ ] This will occur when the curator approves the work
- [ ] Automated tests for the files getting created when the approve button is pressed

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/512?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii @kelynch
