### ISSUE TITLE
Ensure that checksums are appropriately configured in S3 for preservation

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#513]
Ensure that file checksums are being recorded and available via inventory retrieval for all PDC Describe buckets.

## Resources: 

* https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/

**Comment by carolyncole** [comment]
@kelynch The link here is talking about additional checksums.  What kind of additional checksums are you expecting AWS to calculate?  We currently utilize MD5 checksums that are built in, but no additional checksum, nor do we ask AWS to calculate an additional checksum during any processing.

**Comment by kelynch** [comment]
Converting this to an ADR, per conversation at stand-up
