### ISSUE TITLE
Configure recurring database backups for preservation

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#514]
Set up daily database backups for the PDC Describe application.

The database should dump all data to a cloud storage location for secure backups.

https://docs.google.com/document/d/1PG2yQCdOAgKuEcXpX578ED6VCahmel1PRchOpi1hYwQ/edit#heading=h.y6jox8ikmkbe

- [x] Check with Operations about if this is done for every database in our shared postgres
- [ ] Document how to retrieve the backup and recover 
- [ ] Document how to restore from Google Cloud (RDSS should be able to do this working off documentation that Operations writes)

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/514?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii @kelynch

**Comment by kelynch** [comment]
Operations will check and report on this next week.

**Comment by kayiwa** [comment]
Backup for pdc-describe https://console.cloud.google.com/storage/browser/pul-postgres-backup/13/daily/pdc_describe_prod?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=pul-gcdc&prefix=&forceOnObjectsSortingFiltering=false

**Comment by acozine** [comment]
PR with documentation about backups: https://github.com/pulibrary/pul-it-handbook/pull/199. It still needs instructions for restoring, but this is a start!

**Comment by kelynch** [comment]
Closed by https://github.com/pulibrary/pdc_describe/pull/1475
