### ISSUE TITLE
Refactor: lint javascript

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#534]
It would make the project more maintainable to add linting. (eslint?) The amount of javascript we maintain will only grow, so let's set ourselves up to be able to use the js tooling ecosystem. 

Article on setting it up: https://medium.com/@Tunmise/set-up-eslint-with-airbnb-style-guide-in-5-minutes-d7b4cc5707f8
ESlint configuration: https://yarnpkg.com/package/eslint-config-airbnb

### Acceptance criteria
- [ ] More than one team member should do this together
- [ ] js linting is part of the CI

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/534?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii
