### ISSUE TITLE
ORCID completion on contributor

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#556]
The code to fetch the first and last name of a contributor based on the ORCID entered by the user is incorrectly populating the creator fields rather than the contributor fields.

This is likely a copy and paste error in the javascript.

Acceptance criteria:

- [ ] The code populates the contributor fields when an ORCID on the work Edit form additional metadata tab
- [ ] There is an automated test that show the creator is not updates and that the contributor is updated

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/556?planning-poker) with Zenhub @bess @hectorcorrea @mccalluc
