### ISSUE TITLE
Describe Form: Move specified properties to a different tab

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#561]
## Priority

Not on fire, but needed before user testing and launch.

## Description

The following properties must be moved from the "Additional Metadata" tab to the "Curator Controlled" tab.
- Publisher
- Publication Year
- Collection

These are properties that we do not want depositors to be able to change themselves. However, they may request a curator to change when appropriate.

## Acceptance Criteria 
- [x] The specified properties (Publisher, Publication Year, Collection) will move to the "Curator Controlled" tab. 
- [x] An automated test to be certain that only curators and super admins have access to the properties and that they reside on the curator controlled tab

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/561?planning-poker) with Zenhub @bess @hectorcorrea @mccalluc
