### ISSUE TITLE
Curator comments should sanitize html

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/pdc_describe#585]
Besides supporting markdown and expanding netIDs, the curator comments support HTML. This can be useful, but we need to sanitize the input. To demonstrate the problem, leave this as a comment:
```html
<script>alert('xss!')</script>
```
After you click "comment", an alert box will pop up.

**Comment by jrgriffiniii** [comment]
I believe that https://app.zenhub.com/workspace/o/pulibrary/pdc_describe/issues/570 fully resolved this.
