### ISSUE TITLE
Refactor `_curator_controlled_{display,form}.html.erb`

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/pdc_describe#594]
- Follow-up to #593

There's a lot of duplication between `_curator_controlled_display.html.erb` and `_curator_controlled_form.html.erb`... and where there are differences, I'm not sure that it's intentional, or accidental.

Suggest refactoring this into a single partial with a parameter to control the mode... But if this doesn't seem like the right course to other folks, feel free to close.

**Comment by jrgriffiniii** [comment]
I strongly agree, thank you very much again for identifying these improvements, and for creating this issue.
