### ISSUE TITLE
Ensure quotations in Datacite xml are encoded correctly

### ISSUE THREAD

**Issue by Twade968** [pulibrary/pdc_describe#601]
When we generate Datacite xml do not include ampersand encoded characters. See, for example the attached screenshot.
![Screen Shot 2022-11-14 at 11.36.27 AM.png](https://images.zenhubusercontent.com/62e44626d7978151c71e4583/21cd1f6a-4f72-4ad1-86bf-a899345e3aeb)

**Comment by bess** [comment]
@mccalluc Good point! This was based on feedback we got from folks reviewing the XML records for migration, and I encouraged Tyler to open this ticket. If it comes up again I'll remind everyone (including myself!) that these characters SHOULD be encoded like this in an XML record. 

I will close this issue.
