### ISSUE TITLE
Describe Form: Remove header options from the comment feature

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#622]
## Description

Headings are a useful means to organize textual content. However, there isn't sufficient space or need to support this in the Describe Form. For example, the screenshot below shows how distracting this feature can be when trying to read the provenance and messaging for this record. The bold and italics are sufficient to organize this information, although we may consider other markdown options for the future.

## Image shows the distracting size of the headers
![Screen Shot 2022-11-21 at 4 33 08 PM](https://user-images.githubusercontent.com/50670293/204357547-89bc2714-0cec-424b-8612-d89a524e1c3a.jpeg)

## Acceptance Criteria
- [ ] Remove heading options
- [ ] Leave the remaining markdown options, such as **bold** and *italic*

**Comment by mccalluc** [comment]
We decided that this is best handled with CSS, rather than trying to pre- or post-process the markdown. Still on my plate.
