### ISSUE TITLE
Describe Form: Error message for record selection

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#631]
## Description

**This happened to more than one person testing PDC Describe.**

An error screen appears when attempting to click on a record to open that record. This doesn't seem to happen for all records. The two separate instances occurred with different users for (test) records they recently created.  

## Image shows user tried to access "Purple Haze.." record.
![Screen Shot 2022-11-29 at 4 18 16 PM](https://user-images.githubusercontent.com/50670293/204656782-577cd736-b209-4419-8cbf-2aaafed03b47.jpeg)

## Image shows the error screen after selecting the record from the home screen list
![Screen Shot 2022-11-29 at 4 18 23 PM](https://user-images.githubusercontent.com/50670293/204656819-5184b1ff-98a0-43f8-90a9-3e2e2d48005b.jpeg)

## Acceptance Criteria
- [ ] The record will open when selected from the home screen list

**Comment by kelynch** [comment]
"Purple Haze" record is throwing an error on staging, investigate.

**Comment by bess** [comment]
I believe this is the error from honeybadger: https://app.honeybadger.io/projects/99214/faults/90933978

**Comment by kelynch** [comment]
Possibly related #633

**Comment by jrgriffiniii** [comment]
Until a meeting with Hannah can be scheduled, I am hesitant to consider this closed (should it be the case that #633 did not resolve this). Hence, I am going to return this to the Sprint Backlog.

**Comment by hhkitsune** [comment]
@jrgriffiniii I just checked staging and the error message is still showing. Please feel free to schedule a meeting with me. I am particularly available next Tuesday morning, but happy to find time to meet on any day next week.

**Comment by carolyncole** [comment]
There are six works with nil collections.  I am going to set those works to the ResearchData collection and then write some code to hopefully stop this from ever happening again.
