### ISSUE TITLE
`URI::InvalidURIError in Works#edit`

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/pdc_describe#662]
This same error message was part of 
- #519

That is marked as fixed, but it's possible this is a regression.

To reproduce:
- Create a new record: On the first page of the wizard, just a title, and "x", "y" as the creator, "asdf" description, and pick a license.
- Hit the "Save work" button.
- Select the default: "under 100GB and I want to upload the files directly."
- create a zero length file locally and upload.
- Hit "Complete"
- From the list of all submissions, click on the one you've just created.
- and then click "Edit"

I get the following error:
```
URI::InvalidURIError in Works#edit
Showing /Users/chuck/github/rdss/pdc_describe/app/views/works/_uploads_form.html.erb where line #31 raised:
bad URI(is not URI?): nil
```
The error occurs on this line:
```
<a href="<%=upload.url%>" class="documents-file-link" target="_blank" title="<%= upload.key %>"><%= upload.filename %></a>
```
 In the console we can narrow down the problem:
```
>> upload.url
URI::InvalidURIError: bad URI(is not URI?): nil
	from /Users/chuck/github/rdss/pdc_describe/app/views/works/_uploads_form.html.erb:31:in `block in _app_views_works__uploads_form_html_erb___1404918409379364812_148280'
```
The `url` method is [documented here](https://api.rubyonrails.org/classes/ActiveStorage/Blob.html#method-i-url).

- Can other devs reproduce this?
- Does it still happen with a non-zero-length file?

**Comment by kelynch** [comment]
Suggested approach: try writing a test to recreate this failure.

**Comment by mccalluc** [comment]
Bess writes:

> I think this system spec should get moved out of the “data migration” folder (because it’s more about testing the submission functionality than it is about ensuring we have all our use cases for the data migration covered): https://github.com/pulibrary/pdc_describe/blob/main/spec/system/data_migration/form_submission_spec.rb
I’d be very interested to know whether the bug you just reported can show up in this spec or a similar one.

**Comment by mccalluc** [comment]
Not able to reproduce this on Staging, so either it's a problem just with my configuration, or it's a problem for other developers as well. @carolyncole should be able to try it locally later in the afternoon.
