### ISSUE TITLE
Configure and test email notification sending

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#687]
Mailcatcher (SMTP server that runs locally) is installed (possibly not configured) on staging.

## Acceptance Criteria 
- [x] Ensure production server can send out email
- [x] Ensure the email setup is documented
- [x] Ensure [mailcatcher on staging setup](https://github.com/pulibrary/approvals#staging-mail-catcher) is documented so developer can use it for testing
- [ ] Emails should go out ONLY if user has email enabled in their account, in the following cases:
  - [x] In work state cases documented [here](https://github.com/pulibrary/pdc_describe/blob/main/docs/work_states.md) 
  - [ ] Comments in the system with "@" their username

**Comment by carolyncole** [comment]
Once #853 is closed I believe this can be closed.  The issue with collections and mail for non curators is documented here: https://github.com/pulibrary/pdc_describe/issues/762
