### ISSUE TITLE
Add funding fields to DataCite record

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#688]
Based on [base DataCite metadata fields](https://github.com/pulibrary/RDOS_Publishing/issues/3), add funding fields to DataCite records.

**Comment by mccalluc** [comment]
I may be confused, but I think this is already in place?
```ruby
    def self.new_from_work_resource(resource)
      mapping = ::Datacite::Mapping::Resource.new(
        ...
        funding_references: funding_reference_from_work_resource(resource)
      )
      Datacite.new(mapping)
    end
```
and the result of `PDCSerialization::Datacite.new_from_work(work).to_xml` has funder information:
```xml
  <fundingReferences>
    <fundingReference>
      <funderName>National Science Foundation</funderName>
      <awardNumber awardURI='http://asdfasf'>asdfasdf</awardNumber>
    </fundingReference>
  </fundingReferences>
```

**Comment by hectorcorrea** [comment]
Agreed, this was implemented in PR: https://github.com/pulibrary/pdc_describe/pull/654
