### ISSUE TITLE
Describe form: "complete metadata prompt" enhancement

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#698]
## Description

When selecting "Save Work" from the "required metadata page, the user currently goes to the upload section. We want the user to go through the next tab, "additional metadata," before the upload section. Therefore, we probably want the button on the "required metadata" tab to say next, then go to the "additional metadata" tab where the button can say "save work."

## Acceptance Criteria
- [ ] The end result should be that a user must (at least) visit the second tab (additional metadata) before going to the next section to deposit files
- [ ] This should not affect saving work already done. The work should be saved automatically.

**Comment by kelynch** [comment]
This has been done.
