### ISSUE TITLE
Sample data: Identify key records that we will use as fixtures for metadata 

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#7]

**Comment by kelynch** [comment]
I'll pull some from https://docs.google.com/document/d/18ZkBldqWxIIR1UA6qMY87RnGFTKU9HG3EJzodzzFf2A/edit#heading=h.iz99wt7c73wh and will be ready to update afterward as needed.

**Comment by jrgriffiniii** [comment]
This has been confirmed as closed.
