### ISSUE TITLE
Develop a statement for our provenance log which describes our migration process

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#718]
Given that it is one of the goals of PDC Describe to qualify for Core Trust Seal status, we are required to record in our provenance log any intentional changes to the data or metadata from what was originally put on deposit. I think that means we should have a simple statement we can paste as a comment on all our datasets that are being migrated from DataSpace which says:
1. That they were re-described
2. Who did the redescription
3. Why this was undertaken. 

<img width="927" alt="Screenshot 2022-12-13 at 9 16 51 AM" src="https://user-images.githubusercontent.com/65608/207357390-9b240ce9-786c-4dff-8c9d-90a2a9deec86.png">

Proposed language:

"This dataset was re-described in order to migrate its metadata from modified Dublin Core to modified DataCite, and to migrate its location from Princeton's legacy DataSpace repository to the DataCite compliant Princeton Data Commons suite of applications. 
This migration was undertaken by ________________ (name of cataloger here, likely Tyler Wade for most of these) and work was checked by ______________ (name of second pair of eyes here). "

Refinement to this statement welcome.

UPDATE:
Per request from @hhkitsune we'll instead have three short statements, like this: 
![Screen Shot 2022-12-13 at 10 16 58 AM](https://user-images.githubusercontent.com/50670293/207372227-38da62ee-3d9c-442f-9fc2-a0b1c1b3d899.jpeg)

**Comment by mccalluc** [comment]
Bess points out that this can't just be a comment on the record: We need to be sure it's in the provenance so it will be persisted... And there's no provision right now for free text in the provenance log. I'll file a new issue for that: This issue is just to come up with text and apply it to the records.

**Comment by hhkitsune** [comment]
@bess This longer statement belongs in the repository documentation, not the provenance log. A shorter statement to indicate the record was migrated and re-described can be placed in the provenance log. Tyler's (or whomever else) performs the change to the record should be recorded to the provenance log in the same way it will record changes made by other users. (note: I'm not totally happy with how the provenance log is capturing contributors to the record, so we can talk more about versions of names recorded.)

### Example of what I would like to see in the provenance log:
 
![Screen Shot 2022-12-13 at 10 16 58 AM](https://user-images.githubusercontent.com/50670293/207372227-38da62ee-3d9c-442f-9fc2-a0b1c1b3d899.jpeg)


### Example from the current provenance log in Describe:
![Screen Shot 2022-12-13 at 9 53 32 AM](https://user-images.githubusercontent.com/50670293/207366825-881cc794-2ece-4039-9545-a4699681ed51.jpeg)


### Example from ScholarSphere (see migration info):
![Screen Shot 2022-12-13 at 9 47 49 AM](https://user-images.githubusercontent.com/50670293/207365858-61206426-f6cc-4b55-ab3f-8eb84e332aa9.jpeg)

**Comment by hhkitsune** [comment]
@bess @mccalluc We need to talk about what goes in this log and what should be in separate documentation.

**Comment by bess** [comment]
I'm happy with the three shorter statements in the provenance log for the object. Seems to me that meets the CTS requirements, and if keeping the log short and easily scanned is a goal this seems like a good way to do that. 

@mccalluc Thanks for pointing out the need to record user-entered statements into the provenance log, and thank you for writing that ticket.

**Comment by hhkitsune** [comment]
@bess I like this statement though and want to see it in our documentation for the repository. It belongs with further detailed description of the migration.

**Comment by bess** [comment]
Sounds like we have agreement on what the migration messages should look like, and implementation will happen with ticket #720
