### ISSUE TITLE
Add text for "about" page

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/pdc_describe#739]
@hhkitsune will provide. (Close if this is duplicate, but I couldn't find an existing issue.)

- Follow up for #541

**Comment by kelynch** [comment]
Text here - https://docs.google.com/document/d/1miQatqxCBp5EpEAJI54aO8sdVFOdc3n7yIicVhHLDJo/edit#heading=h.aru0jotyefxn

Note "How to Submit" section should be a separate page.

**Comment by kelynch** [comment]
Moving this in-sprint, as it will be best to have this ready to show at OLC communications meeting next week.
