### ISSUE TITLE
Provenance Log: Streamlined Organization (to discuss)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#745]
## Description
This ticket provides an example for how the appearance of our provenance log could improve. An example is provided below to show how provenance information might be organized. This does not mean we have to do exactly the same thing in our log, but we should consider how to bring our log towards improved comprehension for users.

## Image shows screenshot of example
![Screen Shot 2022-12-14 at 1 54 31 PM](https://user-images.githubusercontent.com/50670293/207688156-5590787e-1754-4293-b457-fbc7e7d33d1c.jpeg)

### Link to the live record
- [Example record](https://scholarsphere.psu.edu/resources/19a9240c-ae55-44a2-b6d6-e174d618b059)

### Qualities to consider from the example
- Shortened entries with a standardized form
- The action, date and user who made the changes are immediately available without visual clutter that can obscure scanning for specific items
- Details are available by clicking on the expansion button
- Expanded details show changes, but these do not visually clutter the record when closed

## Expectations
- [x] To discuss at the feature meeting on 12/14: Discuss qualities from the example above that can be applied to the provenance log in Describe.
- [ ] Decide on tickets to apply to make agreed upon changes

**Comment by mccalluc** [comment]
With these PRs:
- #790
- #824

I think this can be closed. If anything else is needed, feel free to file a new issue.
