### ISSUE TITLE
Help Text: Sign in for new users (ORCID landing page)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#750]
## Description

Please add help text (w/links) from this ticket to the page that appears when new users sign-in. This is the page where new users may enter an ORCID ID before being directed to the regular landing page.

## Text and links to include:

You do not have an ORCID ID on file. Add one to your profile. 

ORCID, Open Research and Contributor ID, is a non-profit organization that promotes the use of a unique digital identifier in an effort to help link researchers to their scholarly works regardless of institutional affiliation, moves or names. You can learn more about ORCID in our [ORICD guide](https://researchdata.princeton.edu/research-lifecycle-guide/orcid) and register for one at https://orcid.org/register.

## Acceptance Criteria:
- [ ] Text from this ticket is applied to the specified page

**Comment by mccalluc** [comment]
Fixed with (accidental) push to main: https://github.com/pulibrary/pdc_describe/commit/cf8c8dc1b869d4aff9caa65e61d7856265bf666b

Added code to my .zshrc to prevent accidental pushes in the future.
