### ISSUE TITLE
Describe Form: additional contributor and hosting institutions

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#811]
## Description

The "Additional Contributor" property set (under additional metadata tab) is configured for most of the controlled vocabularies under the "role" sub-property. However, this configuration would not work for some selections. For example: I can't enter an corresponding institutional name if "Hosting Institution" is selected from the role list, because the entry fields are first and last names for persons.

## Image shows the Additional Contributor property set with the controlled list for roles
![Screen Shot 2023-01-03 at 5 09 46 PM](https://user-images.githubusercontent.com/50670293/210450189-33d3cfbf-2d57-42ed-99e3-944011775687.jpeg)

## Acceptance Criteria
- [x] Discuss options in meeting on 1/4/23
- [x] Tickets will be created to address this issue once we have decided on the solution

**Comment by mccalluc** [comment]
Tow follow-up tasks were identified in the meeting, and issues have been filed:
- #815 
- #816

Closing
