### ISSUE TITLE
Make fixtures for theses

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pdc_describe#82]
ON HOLD

Use samples identified here - https://docs.google.com/document/d/18ZkBldqWxIIR1UA6qMY87RnGFTKU9HG3EJzodzzFf2A/edit#bookmark=id.kxd230q0k7lz

**Comment by jrgriffiniii** [comment]
This is to be considered on hold, as during a meeting concerning pdc_describe held on 04/29/22, it was determined that pdc_describe shall not manage theses from DataSpace.
