### ISSUE TITLE
Fix collection in bitklavierimage_form_submission_spec

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#820]
Spec [bitklavierimage_form_submission_spec.rb](https://github.com/pulibrary/pdc_describe/blob/main/spec/system/data_migration/bitklavierimage_form_submission_spec.rb#L17) uses "bitklavier" as the Collection 

```
  let(:collection) { "bitklavier" }
```

but every other spec uses "Research Data".

```
  let(:collection) { "Research Data" }
```

## Acceptance Criteria
- [ ] Change this to `let(:collection_tags) { ["bitklavier"] }`
- [ ] Ensure the `collection_tags` are populated with this value
- [ ] Update collection to `let(:collection) { "Research Data" }` and ensure this object goes into the Research Data collection

**Comment by carolyncole** [comment]
I wonder if that was eventually supposed to go into collection tags.  The collection is being set to Research Data https://github.com/pulibrary/pdc_describe/blob/main/spec/system/data_migration/bitklavierimage_form_submission_spec.rb#L62 @bess or @Twade968 any ideas?

**Comment by bess** [comment]
I think that's supposed to go into collection tags. The DataSpace objects contain 

```
Appears in Collections: bitKlavier
```

With a link to all the other bitKlavier objects.

**Comment by bess** [comment]
This should be changed to `let(:collection_tags) { ["bitklavier"] }`
