### ISSUE TITLE
Contributors in DataCite 

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#832]
Systems throw an error when creating the DataCite representation of a record with contributors. The culprit seems to be the code to map the resource value to the `::Datacite::Mapping::ContributorType` (https://github.com/pulibrary/pdc_describe/blob/main/app/models/pdc_serialization/datacite.rb#L110-L112)

This code:
```
def datacite_contributor_type(value)
  ::Datacite::Mapping::ContributorType.find_by_value(value)
end
```

should look like this:
```
def datacite_contributor_type(type)
  contributor_types = ::Datacite::Mapping::ContributorType.to_a.index_by { |x| x.key.to_s }
  contributor_types[type]
end
```

Related to https://github.com/pulibrary/pdc_discovery/issues/340

**Comment by mccalluc** [comment]
Thanks. I'll look into this, and add more testing!

**Comment by hectorcorrea** [comment]
I didn't look closer to see why it works for the `datacite_resource_type` values, also defined in this class (https://github.com/pulibrary/pdc_describe/blob/main/app/models/pdc_serialization/datacite.rb#L105-L108) but the problem seems to be the symbol to string conversion.

**Comment by mccalluc** [comment]
@hectorcorrea -- Can you give me more information about how to reproduce? I've made a record with two contributors:

<img width="430" alt="Screen Shot 2023-01-09 at 1 49 34 PM" src="https://user-images.githubusercontent.com/730388/211384913-cf1ab114-f27c-431d-8c3d-bfb54caa2b2e.png">

I then enter the rails console:
```
work = Work.find(8)
...
   "contributors"=>
    [{"type"=>"WorkPackageLeader",
      "value"=>"asdf, asdf",
      "sequence"=>0,
      "name_type"=>"Personal",
      "given_name"=>"asdf",
      "identifier"=>nil,
      "family_name"=>"asdf",
      "affiliations"=>[]},
     {"type"=>"Other",
      "value"=>"sdfg, dfg",
      "sequence"=>1,
      "name_type"=>"Personal",
      "given_name"=>"dfg",
      "identifier"=>nil,
      "family_name"=>"sdfg",
      "affiliations"=>[]}],
...
puts work.to_xml
...
  <contributors>
    <contributor contributorType='WorkPackageLeader'>
      <contributorName>asdf, asdf</contributorName>
    </contributor>
    <contributor contributorType='Other'>
      <contributorName>sdfg, dfg</contributorName>
    </contributor>
  </contributors>
```

Perhaps it's a problem with older records? Or maybe there's something else you're doing that I'm missing?

**Comment by hectorcorrea** [comment]
This was a problem with my local version having an old cache of the JavaScript :( -- bit thanks to @mccalluc for helping me troubleshoot it.
