### ISSUE TITLE
Include files in Work JSON

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#842]
The data that we expose for a work in JSON (e.g. http://localhost:3000/works/43.json) does not include the list of files in the Work and we need that value in PDC Discovery. 

Part of https://github.com/pulibrary/pdc_discovery/issues/340
See also https://github.com/pulibrary/pdc_describe/issues/841

**Comment by mccalluc** [comment]
Talking just now: We'll just need to stop delegating `to_json` entirely to the resource: Instead, work will have `to_json`, and it will use the data from resource, but also the information it has that the resource doesn't.
