### ISSUE TITLE
Show funder changes in change log

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/pdc_describe#867]
To reproduce, change the name of a funder. I would expect to see this in the change log, but I don't.

## Acceptance Criteria

- [ ] Change the change log to include funding
- [ ] Change the system test that modifies the funder to make sure the change log gets updated when the funder changes

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/867?planning-poker) with Zenhub @bess @hectorcorrea @jrgriffiniii @kelynch @mccalluc
