### ISSUE TITLE
Add Moderator Roles (staging)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#885]
## Description

In order to perform the system tests we need to assign moderator roles to the test takers in Describe staging. Please add the following people to the moderator role in Describe Staging:
- Neggin Kesavarzian
- Matt Chandler
- Sarah Reiff Conell
- Halle Burns
- Rishi Joshi

## Acceptance Criteria
- [ ] Those listed will have the moderator role in Describe staging

**Comment by carolyncole** [comment]
Adding UIDs to make this easier:
Neggin Kesavarzian (neggink)
Matt Chandler (mjc12)
Sarah Reiff Conell (sr7276)
Halle Burns (hb0344)
Rishi Joshi (rkj)

**Comment by carolyncole** [comment]
This can be done by any collection curator on the collection page:
https://pdc-describe-staging.princeton.edu/describe/collections
I wonder how one gets to the page without the direct URL? Maybe we need a ticket to add the link to the drop down menu.

**Comment by hhkitsune** [comment]
Note: I'm able to complete this task thanks to @carolyncole 's excellent tutorial.
