### ISSUE TITLE
Globus Directories have a date of 1969

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#901]
I'm unsure if we can fix this, but...  All directories have the date of 1969 in globus.  This seems weird...

![Screen Shot 2023-01-25 at 9.59.46 AM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/53e8ab77-3791-4930-aafb-bcc934c0d548)

**Comment by hectorcorrea** [comment]
Notice that the folders that we setup manually on the bucket directly in S3 (namely `pdc-describe-staging-precuration`, `10.34770`, and `10.80021`) also show the incorrect year in Globus. 

![pdc-describe-staging-precuration](https://user-images.githubusercontent.com/568286/215816299-ae468064-1e05-47ee-bd14-0f9de84b4489.png)

![doi-prefixes](https://user-images.githubusercontent.com/568286/215816310-47767fa5-e448-4a8d-8661-c98d8b1b295a.png)

The same is true if we manually create a folder inside this bucket directly on the Amazon S3 web page.

**Comment by hectorcorrea** [comment]
Information about AWS S3 folders in general that seems relevant to this issue: https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html

> Amazon S3 has a flat structure instead of a hierarchy like you would see in a file system. However, for the sake of organizational simplicity, the Amazon S3 console supports the folder concept as a means of grouping objects. It does this by using a shared name prefix for objects (that is, objects have names that begin with a common string). Object names are also referred to as key names.

**Comment by carolyncole** [comment]
@hectorcorrea will time box this issue and if he can not fix it we will discuss again.

**Comment by hectorcorrea** [comment]
Below is an example to let S3 automatically create the folder and another that manually creates the folder and in both instances the 1969 date shows in the Globus File Manager:

```
    # References:
    # https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html
    # https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html
    key_id = ENV["AWS_S3_KEY_ID"]
    secret_key = ENV["AWS_S3_SECRET_KEY"]
    region = ENV["AWS_S3_PRE_CURATE_REGION"]
    bucket = ENV["AWS_S3_PRE_CURATE_BUCKET"]
    s3_credentials = Aws::Credentials.new(key_id, secret_key)
    s3_client = Aws::S3::Client.new(region: region, credentials: s3_credentials)

    # Example 1 - let S3 automatically create the folder
    #
    # Upload the file to a "folder" named "hector-fake-folder-four"
    # The "folder" is automatically created with date 1969
    file_key = "hector-fake-folder-four/feb-1-405.txt"
    file_name = "/Users/correah/Downloads/small.txt"
    options = {client: s3_client}
    object = Aws::S3::Object.new(bucket, file_key, options)
    object.upload_file(file_name)

    # Example 2 - create the folder manually ahead of time
    #
    # Force the creation of a folder (notice the trailing / in the file_key)
    # The folder will have the 1969 date.
    file_key = "hector-fake-folder-six/"
    options = {client: s3_client}
    object = Aws::S3::Object.new(bucket, file_key, options)
    object.put({content_length: 0})

    # ...and the upload a file to it
    #
    file_key = "hector-fake-folder-six/feb-1-409"
    file_name = "/Users/correah/Downloads/small.txt"
    object = Aws::S3::Object.new(bucket, file_key, options)
    object.upload_file(file_name)
```

![Screenshot 2023-02-01 at 4 30 12 PM](https://user-images.githubusercontent.com/568286/216172681-a25b9cd1-5d94-4473-8e0d-3b9b8eeff521.png)

**Comment by hectorcorrea** [comment]
I've posted the question to the Globus discussion group to see if this is a known-issue https://groups.google.com/a/globus.org/g/discuss/c/OB33LKFkzlA/m/6hwsuzrNAwAJ

**Comment by hectorcorrea** [comment]
The folks from Globus confirmed that this is a known-issue (https://groups.google.com/a/globus.org/g/discuss/c/OB33LKFkzlA) and a limitation due to the way AWS S3 manages folders.
