### ISSUE TITLE
New logger noise during test runs

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/pdc_describe#914]
Tests runs used to just be `.....` etc., but with  the latest changes, I see this a dozen times:
```
INFO -- : EZID GetIdentifierMetadata -- success: ark:/88435/dsp01h415pd457
```
Not the end of the world, but with a lot of log noise during test runs it can be a bit harder to spot the real problems.

- Is this message set at the appropriate logging level?
- Or maybe the filter on log messages during tests can change?
- or ...

**Comment by hectorcorrea** [comment]
I hope we are not really minting new ARKs every time we run the tests.

**Comment by mccalluc** [comment]
- All the messages are the same: Pretty sure IDs are not being minted.
- Checking out earlier versions, I believe this was introduced by #907.

**Comment by bess** [comment]
Not really an issue. We aren't minting real ARKs every time, we're faking it with webmock. Having these messages in the test logs isn't an issue.
