### ISSUE TITLE
Some migration fixtures have a DOI of doc-1 when loaded into staging

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#922]
`doc-1` is definitely not a valid DOI, not even in the test DOI minting system. 

## Acceptance Criteria
- [ ] Figure out why this is happening
- [ ] Update our migration specs / description process to prevent this happening again

**Comment by mccalluc** [comment]
PR message had typo, so this issue wasn't linked, but it is fixed with 
- #970
