### ISSUE TITLE
The total number of files for large datasets is not correct

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pdc_describe#938]
This data set should end up with around 2,659 (minus 4 for the four folders, I think) files in the object.  It is consistently loading just under 1000.

This is a pagination issue: https://github.com/pulibrary/pdc_describe/blob/main/app/services/s3_query_service.rb#L143

![Screenshot 2023-02-02 at 7 48 03 AM](https://user-images.githubusercontent.com/1599081/216329203-226a13ac-c8dd-4785-a687-f373f0adb51f.png)

**Comment by hectorcorrea** [comment]
As a reference, this is the breakdown of files by subfolder for this work (roughly 665 per folder)

![file-breakdown](https://user-images.githubusercontent.com/568286/216389770-ce8c28dc-8b07-47bd-853a-2cdeb1b18791.png)
