### ISSUE TITLE
Load file list directly from AWS

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#941]
In the show page load the file list directly from AWS rather than using ActiveStorage to cache the information and then display it from ActiveStorage's cache. 

The reason for this is that loading the ActiveStorage cache is too slow. @carolyncole has found that it can take 7+ minutes to cache 1000 files (see https://github.com/pulibrary/pdc_describe/issues/933) whereas AWS returns the entire list of files in just a couple of seconds.

**Comment by carolyncole** [comment]
@hectorcorrea you may want to merge this (or review) prior to starting work.  Otherwise they may conflict and you will not get all the items.

**Comment by hectorcorrea** [comment]
Related PR: https://github.com/pulibrary/pdc_describe/pull/939

**Comment by carolyncole** [comment]
We can get a download url from an [aws presigner](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Presigner.html). It works by default for 15 minutes.
```
work = Work.first
service = S3QueryService.new(work)
files = service.client_s3_files
signer = Aws::S3::Presigner.new(client: service.client)
url = signer.presigned_url(:get_object, bucket: service.bucket_name, key: files[0].key)
```
