### ISSUE TITLE
Describe Form: New Upload/Data Pages Series

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#966]
## Description

After entering the metadata to the form, depositors will need to upload a README and either upload data (under 100mb) or tell the curators where to locate and access their data. This ticket describes a refinement to this sequence.

**Note:** The image shows an additional step added to the status bar. Another ticket will be written for adding this step. The images below show when the specific part of the bar is activated.
 
### Page 1
After entering metadata, the depositor will be taken to a page where they are required to deposit a README file. The page includes links to find help for creating a README and a link to a README template.
 
![Screen Shot 2023-02-08 at 9 16 05 AM](https://user-images.githubusercontent.com/50670293/217559235-342746c0-d1d7-46ab-96ea-e79a3da4ba71.jpeg)

### Page 2
After the README is deposited, the depositor will go to the next page to choose the pathway for data deposit that is based on their submission size. (Note: this is a screen that already exists in Describe, but refinements to the help text may have changed)

![Screen Shot 2023-02-08 at 9 16 09 AM](https://user-images.githubusercontent.com/50670293/217560316-12b2798e-8e20-4124-8efb-d376115d899c.jpeg)

### Page 3 (Option 1: Data less than 100mb)
Data under 100mb may be deposited to this screen. (Note: this is a screen that already exists in Describe, but refinements to the help text may have changed)

![Screen Shot 2023-02-08 at 9 16 13 AM](https://user-images.githubusercontent.com/50670293/217560786-1824984a-44b6-4175-9516-ec12901d9b15.jpeg)

### Page 3 (Option 2: Data is too big to upload to the form)
Please note important changes to the help text. It should be required to write something into the box before the submission can be completed. (Note: this is a screen that already exists in Describe, but refinements to the help text may have changed)

![Screen Shot 2023-02-08 at 9 16 21 AM](https://user-images.githubusercontent.com/50670293/217561273-cb29876c-a85e-4f54-ab19-38653ac486fc.jpeg)

## Acceptance Criteria
- [ ] The sequenced pages that come after metadata entry will be changed as described in this ticket
- [ ] Help text is added as shown in the image
- [ ] README allow an upload of a single file.  
- [ ] The README will be required, before hitting continue

**Comment by carolyncole** [comment]
Plan to rename the file to README. extension so that we know this IS the README.  No database field will be utilized to mark this file.  Any type is allowed.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-Workcycles-61a4f1a12a399b001730f65a/issues/pulibrary/pdc_describe/966?planning-poker) with Zenhub @jrgriffiniii @bess
