### ISSUE TITLE
Describe Form: Status Bar Change

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#968]
## Description

This ticket goes with #966. 

The status bar should have another section that correlates with uploading a README. The page is shown in ticket #966.

## Image shows the additional section in the status bar. It will be highlighted on the README deposit page.

![Screen Shot 2023-02-08 at 9 16 05 AM](https://user-images.githubusercontent.com/50670293/217565583-369220c2-b056-4705-b623-76c820d044f6.jpeg)

## Detail of text

Please upload the README file for this submission. 

If you have not created a README, a template may be [found here](https://cornell.app.box.com/v/ReadmeTemplate). See [this page](https://data.research.cornell.edu/content/readme) for more guidance on how to create a README. 

We will ask about your data files on the next screen.

## Acceptance Criteria
- [ ] The additional page has been added (Ticket #966)
- [ ] The additional status bar section labelled README has been added
- [ ] This section is highlighted when on the README deposit page

**Comment by carolyncole** [comment]
@hhkitsune Do you have the text from the page above some place you can copy and paste?  I'd like to know where the URLs point to.

**Comment by hhkitsune** [comment]
@carolyncole Sorry, here it is:

Please upload the README file for this submission. 

If you have not created a README, a template may be [found here](https://cornell.app.box.com/v/ReadmeTemplate). See [this page](https://data.research.cornell.edu/content/readme) for more guidance on how to create a README. 

We will ask about your data files on the next screen.

**Comment by hectorcorrea** [comment]
Closed with #1044
