### ISSUE TITLE
Describe Form: Move ROR field (Funding Property set)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#969]
## Description

We want to emphasize certain components in the funding property set that are a lower barrier to enter. For this reason, the ROR field should be placed last in this set. The help text will also need to be reordered.

## Desired Order for this set
1. Funder Name
2. Award Number
3. Award URI
4. ROR

## Acceptance Criteria
- [x] Place the ROR field at the end of this set
- [x] The set will follow the desired order listed above
- [x] The help text will also follow this order

**Comment by kelynch** [comment]
<img width="1255" alt="Screenshot 2023-03-29 at 10 18 16 AM" src="https://user-images.githubusercontent.com/7795797/228568456-192d0dda-033a-419e-964f-452dd4102e5b.png">

**Comment by carolyncole** [comment]
We noted this was not done on the edit screen.  I wonder where my changes went...
