### ISSUE TITLE
Describe Form: Provide pause/notification between two areas of the form

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#999]
## Description

When creating a new submission, the depositor goes through two themed areas (1. metadata entry 2. data upload/reporting) before accepting the publisher's agreement and creating the submission. If a depositor missed a required metadata field, the form currently allows depositors to go to the data uploading/reporting section before it notifies them a requirement was missed. This caused a problem with a test user who noticed they had to go all the way back to fix something in the first area of the form after feeling they were done. If a depositor has missed filling out a required metadata entry, we want to provide some kind of pause/notification before they can go on to the data upload/reporting section.

## User Journey
 * After the initial screen
 * On the metadata edit field, make sure the required fields are filled in (currently only description)

## Acceptance Criteria
- [ ] On step 2 of the wizard the user should be stopped if the required metadata is not filled in
- [ ] There should be an automated test

**Comment by carolyncole** [comment]
Make the error the same as the initial page
![Screenshot 2023-02-22 at 10 14 46 AM](https://user-images.githubusercontent.com/1599081/220665784-1f6a5d1f-89cf-4346-8bd9-e6e13ae8b962.png)
